$axure.loadCurrentPage({
  "url":"应用添加.html",
  "generationDate":new Date(1458553416682.42),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f3942a52a639405ea3e433fefc2bd8a4",
    "type":"Axure:Page",
    "name":"应用添加",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a23bcaac5f824b06bb04476cfcf4aa4d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":200}},
          "adaptiveStyles":{
},
          "masterId":"ce194b8bf61742aea7475dad35671852"},
{
          "id":"6f45857a5f87477894369463e66ebec7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":336},
            "size":{
              "width":210,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e85dc9b0b28241008c4843a453035e4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":336},
                "size":{
                  "width":210,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u0.png"}},
{
          "id":"5fe2beaaebdb4562b9f36539b60ac56a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":322,
              "y":374},
            "size":{
              "width":118,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66bf5e0f862e4a639bf8151ad064705f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":322,
                  "y":374},
                "size":{
                  "width":118,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14b03ff2bcc8459fbba79060d371cc0c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":541},
            "size":{
              "width":45,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"918a61206d5d4501845b34c54c4a11bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":541},
                "size":{
                  "width":45,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 支付查询",
                      "target":{
                        "targetType":"page",
                        "url":"支付查询.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u6.png"}},
{
          "id":"37fe040905464402baaddfb4966eb39d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":327,
              "y":578},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38388012474d4f118bae2d80596d9785",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":327,
                  "y":578},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1689767961354ff8b837258588ea05c0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":541},
            "size":{
              "width":45,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e9930dc0c6543579dcab1216ae328ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":387,
                  "y":541},
                "size":{
                  "width":45,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 应用设置",
                      "target":{
                        "targetType":"page",
                        "url":"应用设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u14.png"}},
{
          "id":"e063b7a9d88547aebc4161f2b24ace7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":395,
              "y":578},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36ec8705865046af8883e36cfcaf1ffd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":395,
                  "y":578},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"988bb1ea7cc8407aa56e49b2ba47b020",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":340},
            "size":{
              "width":210,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fedaf301cf8c41d18b91d66da14a35f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":340},
                "size":{
                  "width":210,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u0.png"}},
{
          "id":"e2f8a7984c92461998e05fd9edecc4cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":628,
              "y":378},
            "size":{
              "width":97,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"809e590b645e477b8407e3d9ecec0e48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":628,
                  "y":378},
                "size":{
                  "width":97,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd4bb77535e44a36a3a7b39fa01d9011",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":623,
              "y":546},
            "size":{
              "width":45,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9eb25eac8060461680ff631f33b24fc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":623,
                  "y":546},
                "size":{
                  "width":45,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u6.png"}},
{
          "id":"4d040f21021e4ccc9f5f9ee8c9e5ca67",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":631,
              "y":582},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1348f8a4d2d4a9f86c9d6a2f1d11cba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":631,
                  "y":582},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"070e15a8320646ae885ac81fa08eff46",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":686,
              "y":546},
            "size":{
              "width":45,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93937ef9fbac4c37b83712b81c51d928",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":686,
                  "y":546},
                "size":{
                  "width":45,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u14.png"}},
{
          "id":"ea1a1bc866d543ae8372af72ebe9c7aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":694,
              "y":582},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1519e3794b154748a9e7767845fb50ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":694,
                  "y":582},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50061855aabe4348b2fc4577af2410a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":340},
            "size":{
              "width":210,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e6488b607c34147b14da8138e18202f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":870,
                  "y":340},
                "size":{
                  "width":210,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u0.png"}},
{
          "id":"80a54b62cf724819a6288096fff7e85e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":937,
              "y":434},
            "size":{
              "width":90,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd838767c0a44b93833d7849eb6768b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":937,
                  "y":434},
                "size":{
                  "width":90,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 应用添加",
                      "target":{
                        "targetType":"page",
                        "url":"应用添加.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u38.png"}},
{
          "id":"7cdea02fbaab4d44a9df39e869816f44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":1450,
              "y":210},
            "size":{
              "width":430,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b747a163ee0946068a423a89fcdfd4b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":1450,
                  "y":210},
                "size":{
                  "width":430,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u88.png"}},
{
          "id":"72c0a7ee572b4f07a845a35f98d3e325",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":432},
            "size":{
              "width":54,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6865fc9d88114b9d9570ade68d14e091",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":296,
                  "y":432},
                "size":{
                  "width":54,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页（控制台）/u58.png"}},
{
          "id":"e56a2cf37ce74789be758bcabda67e16",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":440},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"596513712f1d4895b6ba153cc63105dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":440},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fffeb137f5fd403995cbca4bfbc13115",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":474},
            "size":{
              "width":78,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d21569f3defa49bc934eb08bbda1e3a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":285,
                  "y":474},
                "size":{
                  "width":78,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页（控制台）/u62.png"}},
{
          "id":"a1ccff40d14944d1a73b3368bcdb4d19",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":385,
              "y":482},
            "size":{
              "width":36,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95afb423ac2346399986ea4a005fa583",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":385,
                  "y":482},
                "size":{
                  "width":36,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e11edcb8df564184bf459e33ddca3a9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":686,
              "y":440},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7ba2aa309a24ddeacd529cdd9fe4bfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":686,
                  "y":440},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43d836f9feb146598e960f8b2cf33d4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":694,
              "y":482},
            "size":{
              "width":36,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27c333584d5e4e8a81358ffa751c4ca6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":694,
                  "y":482},
                "size":{
                  "width":36,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40b5504a050f442591a666279fca098c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":609,
              "y":438},
            "size":{
              "width":54,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e508eff58d443569660156d880fb4d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":609,
                  "y":438},
                "size":{
                  "width":54,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页（控制台）/u58.png"}},
{
          "id":"b71078b7d0a445718860d54653ada3ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":598,
              "y":480},
            "size":{
              "width":78,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db25f6851fc64d9e8f04752567eb067c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":598,
                  "y":480},
                "size":{
                  "width":78,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页（控制台）/u62.png"}},
{
          "id":"ef37ec28aa9e41289a44efc6127581b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":203,
              "y":200},
            "size":{
              "width":1216,
              "height":740}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f1cbdf4ef7d414bab40e059f7477748",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":203,
                  "y":200},
                "size":{
                  "width":1216,
                  "height":740}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用添加/u74.png"}},
{
          "id":"5f2ae8645da64d99a3edc636cae17e9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":699,
              "y":418},
            "size":{
              "width":247,
              "height":292}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52e187c6090c496990bed51a14f86c5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":699,
                  "y":418},
                "size":{
                  "width":247,
                  "height":292}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用添加/u76.png"}},
{
          "id":"ff3b4f6e8ce24ca39123f7e333bfdb67",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":773,
              "y":438},
            "size":{
              "width":101,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38e0a1cfb9614417909eee6742b0551c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":773,
                  "y":438},
                "size":{
                  "width":101,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"720c9f84ba974b79bc6186b71768e835",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.6",
            "location":{
              "x":699,
              "y":472},
            "size":{
              "width":249,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/应用添加/u80_line.png"}},
{
          "id":"feac1198b24748f78f58012b31a0cb1f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":729,
              "y":508},
            "size":{
              "width":194,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"1f6a2f9a95284cbbbd80c7a80ce5fa6a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.6",
            "location":{
              "x":698,
              "y":626},
            "size":{
              "width":249,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/应用添加/u80_line.png"}},
{
          "id":"e29e633af7d9430dbb9dcc43d5431cc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":803,
              "y":660},
            "size":{
              "width":60,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"568a767fbec44b4e93c23a0013ef602b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":803,
                  "y":660},
                "size":{
                  "width":60,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 应用设置",
                      "target":{
                        "targetType":"page",
                        "url":"应用设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/应用添加/u83.png"}},
{
          "id":"2ad363d6163c4cee8f7e71a9a6e8c8e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":873,
              "y":660},
            "size":{
              "width":60,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f34602d99fd4233a1e8d36ae5289482",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":873,
                  "y":660},
                "size":{
                  "width":60,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页（控制台）",
                      "target":{
                        "targetType":"page",
                        "url":"首页（控制台）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/应用添加/u83.png"}},
{
          "id":"603ed788a8e64cae81b09b795563ed01",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":726,
              "y":583},
            "size":{
              "width":200,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"2b1c45b564604a28ac7716248b2d8f9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":1450,
              "y":210},
            "size":{
              "width":430,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c5107027c914e91be20fac31d74b857",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":1450,
                  "y":210},
                "size":{
                  "width":430,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u88.png"}},
{
          "id":"0243a2957345416f86210ae39f42a6cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":777,
              "y":548},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45fe3208d86a4361abbf629b4afce3be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":777,
                  "y":548},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2651cf43d5d34f6d8fca492403bc83c0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":759,
              "y":548},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5fb3df716f74077acb0726d1ffdc28c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":759,
                  "y":548},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u81.png"}}]}},
  "masters":{
    "ce194b8bf61742aea7475dad35671852":{
      "packageId":"ce194b8bf61742aea7475dad35671852",
      "type":"Axure:Master",
      "name":"头部框架",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1a8ee24928a94860889c9b047390fbf5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "opacity":"0.3",
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "size":{
                "width":1219,
                "height":740},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f6d5da329001418bad0c45f297bae802",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "opacity":"0.3",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "size":{
                    "width":1219,
                    "height":740},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/帮助/u41.png"}},
{
            "id":"2b596599a1a2483d84e1634a29aaddec",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":100},
              "size":{
                "width":1219,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/帮助/u43_line.png"}},
{
            "id":"06a4f09ba941472c84ee4ff1c0e16d57",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":797,
                "y":41},
              "size":{
                "width":235,
                "height":33}},
            "adaptiveStyles":{
}},
{
            "id":"2d1981c2bb3a4bbf98d29d5eb4a95f05",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":1031,
                "y":41},
              "size":{
                "width":44,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5c489b146ee44a60b5c40b1930b87fea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":1031,
                    "y":41},
                  "size":{
                    "width":44,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 支付查询",
                        "target":{
                          "targetType":"page",
                          "url":"支付查询.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u45.png"}},
{
            "id":"014e382808854576ac2a5acf6f38b3a2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":35,
                "y":20},
              "size":{
                "width":125,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f984bdbcccaa4abf9aac379604b9f79d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":35,
                    "y":20},
                  "size":{
                    "width":125,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/帮助/u47.png"}},
{
            "id":"bececc72e4864233aa56bbeb0067e5a5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":187,
                "y":37},
              "size":{
                "width":113,
                "height":43},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"665d02781c8d4d96a2ccf54f489faf8d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":187,
                    "y":37},
                  "size":{
                    "width":113,
                    "height":43},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页（控制台）",
                        "target":{
                          "targetType":"page",
                          "url":"首页（控制台）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u49.png"}},
{
            "id":"5677bc86a0564221862e5fb5edc25a28",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":321,
                "y":37},
              "size":{
                "width":113,
                "height":43},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a67b7f0a523b4de4af12f9a03eba2cc1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":321,
                    "y":37},
                  "size":{
                    "width":113,
                    "height":43},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 渠道管理",
                        "target":{
                          "targetType":"page",
                          "url":"渠道管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u49.png"}},
{
            "id":"40f50ee05dec42038ace8903a7be2aa8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":455,
                "y":37},
              "size":{
                "width":113,
                "height":43},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"209a6b3bfa1a42e38bc030da67bf54fa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":455,
                    "y":37},
                  "size":{
                    "width":113,
                    "height":43},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 提现",
                        "target":{
                          "targetType":"page",
                          "url":"提现.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u49.png"}},
{
            "id":"f7852bcc4c5a4921802ef94e6d848264",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":623,
                "y":40},
              "size":{
                "width":50,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da463ba93a7b4aec8326c16acf8da252",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":623,
                    "y":40},
                  "size":{
                    "width":50,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 帮助",
                        "target":{
                          "targetType":"page",
                          "url":"帮助.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u55.png"}},
{
            "id":"75f88fef079b47a09a5869837b83bf72",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1150,
                "y":30},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e78ad31a00344180aede2de040f4a718",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1150,
                    "y":30},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle 右侧边栏",
                        "objectsToFades":[{
                            "objectPath":["4c67581e5b9c41d2bed24e008a7eaf41"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u57.png"}},
{
            "id":"4c67581e5b9c41d2bed24e008a7eaf41",
            "label":"右侧边栏",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":1019,
                "y":105},
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"735f9a5466874ed29256b29c16e25def",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"718082d5a20f450d9c84bd2103096cf6",
                    "label":"",
                    "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":200,
                        "height":205}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b1ccd05daa8b42a3bfb0dbd5953ba989",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":200,
                            "height":205}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/帮助/u60.png"}},
{
                    "id":"9654f5fb424e410187206b64ad418cc3",
                    "label":"",
                    "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Negreta', 'Arial'",
                      "fontSize":"18px",
                      "fontWeight":"700",
                      "location":{
                        "x":12,
                        "y":26},
                      "size":{
                        "width":174,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"90a4735f986b4a6182c99e43389f1406",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Negreta', 'Arial'",
                          "fontSize":"18px",
                          "fontWeight":"700",
                          "location":{
                            "x":12,
                            "y":26},
                          "size":{
                            "width":174,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"b8ee2d90d06e4e538a40ae52e9ffc07e",
                    "label":"",
                    "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontSize":"16px",
                      "location":{
                        "x":41,
                        "y":73},
                      "size":{
                        "width":120,
                        "height":30},
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2d867bb2072e457e8c918d09ae3ddac6",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"16px",
                          "location":{
                            "x":41,
                            "y":73},
                          "size":{
                            "width":120,
                            "height":30},
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 基本信息（个人呈现）",
                                "target":{
                                  "targetType":"page",
                                  "url":"基本信息（个人呈现）.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/帮助/u64.png"}},
{
                    "id":"09c4937ed6844893bf4a19ae7fcb6637",
                    "label":"",
                    "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":75,
                        "y":128},
                      "size":{
                        "width":50,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"aa7310f048d8440d82e9fb58dffe258a",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":75,
                            "y":128},
                          "size":{
                            "width":50,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/帮助/u66.png"}}]}]}]}}},
  "objectPaths":{
    "a23bcaac5f824b06bb04476cfcf4aa4d":{
      "scriptId":"u0",
      "1a8ee24928a94860889c9b047390fbf5":{
        "scriptId":"u1"},
      "f6d5da329001418bad0c45f297bae802":{
        "scriptId":"u2"},
      "2b596599a1a2483d84e1634a29aaddec":{
        "scriptId":"u3"},
      "06a4f09ba941472c84ee4ff1c0e16d57":{
        "scriptId":"u4"},
      "2d1981c2bb3a4bbf98d29d5eb4a95f05":{
        "scriptId":"u5"},
      "5c489b146ee44a60b5c40b1930b87fea":{
        "scriptId":"u6"},
      "014e382808854576ac2a5acf6f38b3a2":{
        "scriptId":"u7"},
      "f984bdbcccaa4abf9aac379604b9f79d":{
        "scriptId":"u8"},
      "bececc72e4864233aa56bbeb0067e5a5":{
        "scriptId":"u9"},
      "665d02781c8d4d96a2ccf54f489faf8d":{
        "scriptId":"u10"},
      "5677bc86a0564221862e5fb5edc25a28":{
        "scriptId":"u11"},
      "a67b7f0a523b4de4af12f9a03eba2cc1":{
        "scriptId":"u12"},
      "40f50ee05dec42038ace8903a7be2aa8":{
        "scriptId":"u13"},
      "209a6b3bfa1a42e38bc030da67bf54fa":{
        "scriptId":"u14"},
      "f7852bcc4c5a4921802ef94e6d848264":{
        "scriptId":"u15"},
      "da463ba93a7b4aec8326c16acf8da252":{
        "scriptId":"u16"},
      "75f88fef079b47a09a5869837b83bf72":{
        "scriptId":"u17"},
      "e78ad31a00344180aede2de040f4a718":{
        "scriptId":"u18"},
      "4c67581e5b9c41d2bed24e008a7eaf41":{
        "scriptId":"u19"},
      "718082d5a20f450d9c84bd2103096cf6":{
        "scriptId":"u20"},
      "b1ccd05daa8b42a3bfb0dbd5953ba989":{
        "scriptId":"u21"},
      "9654f5fb424e410187206b64ad418cc3":{
        "scriptId":"u22"},
      "90a4735f986b4a6182c99e43389f1406":{
        "scriptId":"u23"},
      "b8ee2d90d06e4e538a40ae52e9ffc07e":{
        "scriptId":"u24"},
      "2d867bb2072e457e8c918d09ae3ddac6":{
        "scriptId":"u25"},
      "09c4937ed6844893bf4a19ae7fcb6637":{
        "scriptId":"u26"},
      "aa7310f048d8440d82e9fb58dffe258a":{
        "scriptId":"u27"}},
    "6f45857a5f87477894369463e66ebec7":{
      "scriptId":"u28"},
    "e85dc9b0b28241008c4843a453035e4e":{
      "scriptId":"u29"},
    "5fe2beaaebdb4562b9f36539b60ac56a":{
      "scriptId":"u30"},
    "66bf5e0f862e4a639bf8151ad064705f":{
      "scriptId":"u31"},
    "14b03ff2bcc8459fbba79060d371cc0c":{
      "scriptId":"u32"},
    "918a61206d5d4501845b34c54c4a11bb":{
      "scriptId":"u33"},
    "37fe040905464402baaddfb4966eb39d":{
      "scriptId":"u34"},
    "38388012474d4f118bae2d80596d9785":{
      "scriptId":"u35"},
    "1689767961354ff8b837258588ea05c0":{
      "scriptId":"u36"},
    "4e9930dc0c6543579dcab1216ae328ca":{
      "scriptId":"u37"},
    "e063b7a9d88547aebc4161f2b24ace7a":{
      "scriptId":"u38"},
    "36ec8705865046af8883e36cfcaf1ffd":{
      "scriptId":"u39"},
    "988bb1ea7cc8407aa56e49b2ba47b020":{
      "scriptId":"u40"},
    "fedaf301cf8c41d18b91d66da14a35f8":{
      "scriptId":"u41"},
    "e2f8a7984c92461998e05fd9edecc4cc":{
      "scriptId":"u42"},
    "809e590b645e477b8407e3d9ecec0e48":{
      "scriptId":"u43"},
    "bd4bb77535e44a36a3a7b39fa01d9011":{
      "scriptId":"u44"},
    "9eb25eac8060461680ff631f33b24fc8":{
      "scriptId":"u45"},
    "4d040f21021e4ccc9f5f9ee8c9e5ca67":{
      "scriptId":"u46"},
    "a1348f8a4d2d4a9f86c9d6a2f1d11cba":{
      "scriptId":"u47"},
    "070e15a8320646ae885ac81fa08eff46":{
      "scriptId":"u48"},
    "93937ef9fbac4c37b83712b81c51d928":{
      "scriptId":"u49"},
    "ea1a1bc866d543ae8372af72ebe9c7aa":{
      "scriptId":"u50"},
    "1519e3794b154748a9e7767845fb50ab":{
      "scriptId":"u51"},
    "50061855aabe4348b2fc4577af2410a1":{
      "scriptId":"u52"},
    "7e6488b607c34147b14da8138e18202f":{
      "scriptId":"u53"},
    "80a54b62cf724819a6288096fff7e85e":{
      "scriptId":"u54"},
    "dd838767c0a44b93833d7849eb6768b7":{
      "scriptId":"u55"},
    "7cdea02fbaab4d44a9df39e869816f44":{
      "scriptId":"u56"},
    "b747a163ee0946068a423a89fcdfd4b7":{
      "scriptId":"u57"},
    "72c0a7ee572b4f07a845a35f98d3e325":{
      "scriptId":"u58"},
    "6865fc9d88114b9d9570ade68d14e091":{
      "scriptId":"u59"},
    "e56a2cf37ce74789be758bcabda67e16":{
      "scriptId":"u60"},
    "596513712f1d4895b6ba153cc63105dc":{
      "scriptId":"u61"},
    "fffeb137f5fd403995cbca4bfbc13115":{
      "scriptId":"u62"},
    "d21569f3defa49bc934eb08bbda1e3a7":{
      "scriptId":"u63"},
    "a1ccff40d14944d1a73b3368bcdb4d19":{
      "scriptId":"u64"},
    "95afb423ac2346399986ea4a005fa583":{
      "scriptId":"u65"},
    "e11edcb8df564184bf459e33ddca3a9e":{
      "scriptId":"u66"},
    "c7ba2aa309a24ddeacd529cdd9fe4bfb":{
      "scriptId":"u67"},
    "43d836f9feb146598e960f8b2cf33d4d":{
      "scriptId":"u68"},
    "27c333584d5e4e8a81358ffa751c4ca6":{
      "scriptId":"u69"},
    "40b5504a050f442591a666279fca098c":{
      "scriptId":"u70"},
    "8e508eff58d443569660156d880fb4d6":{
      "scriptId":"u71"},
    "b71078b7d0a445718860d54653ada3ab":{
      "scriptId":"u72"},
    "db25f6851fc64d9e8f04752567eb067c":{
      "scriptId":"u73"},
    "ef37ec28aa9e41289a44efc6127581b6":{
      "scriptId":"u74"},
    "6f1cbdf4ef7d414bab40e059f7477748":{
      "scriptId":"u75"},
    "5f2ae8645da64d99a3edc636cae17e9b":{
      "scriptId":"u76"},
    "52e187c6090c496990bed51a14f86c5a":{
      "scriptId":"u77"},
    "ff3b4f6e8ce24ca39123f7e333bfdb67":{
      "scriptId":"u78"},
    "38e0a1cfb9614417909eee6742b0551c":{
      "scriptId":"u79"},
    "720c9f84ba974b79bc6186b71768e835":{
      "scriptId":"u80"},
    "feac1198b24748f78f58012b31a0cb1f":{
      "scriptId":"u81"},
    "1f6a2f9a95284cbbbd80c7a80ce5fa6a":{
      "scriptId":"u82"},
    "e29e633af7d9430dbb9dcc43d5431cc1":{
      "scriptId":"u83"},
    "568a767fbec44b4e93c23a0013ef602b":{
      "scriptId":"u84"},
    "2ad363d6163c4cee8f7e71a9a6e8c8e3":{
      "scriptId":"u85"},
    "0f34602d99fd4233a1e8d36ae5289482":{
      "scriptId":"u86"},
    "603ed788a8e64cae81b09b795563ed01":{
      "scriptId":"u87"},
    "2b1c45b564604a28ac7716248b2d8f9e":{
      "scriptId":"u88"},
    "1c5107027c914e91be20fac31d74b857":{
      "scriptId":"u89"},
    "0243a2957345416f86210ae39f42a6cf":{
      "scriptId":"u90"},
    "45fe3208d86a4361abbf629b4afce3be":{
      "scriptId":"u91"},
    "2651cf43d5d34f6d8fca492403bc83c0":{
      "scriptId":"u92"},
    "a5fb3df716f74077acb0726d1ffdc28c":{
      "scriptId":"u93"}}});