$axure.loadCurrentPage({
  "url":"应用删除确认.html",
  "generationDate":new Date(1461745757001.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"19eb1cc1f6494a129e2bb7a8118fb347",
    "type":"Axure:Page",
    "name":"应用删除确认",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7d571a3607e34f6cbdfa6e3734d60b96",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":210}},
          "adaptiveStyles":{
},
          "masterId":"f73d698e06464df78e2f277ca77e6c60"},
{
          "id":"fbf244d07fa040f3b757b4e535eded9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":213,
              "y":315},
            "size":{
              "width":210,
              "height":784}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff040280c0e945fca137b3da94311a02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":213,
                  "y":315},
                "size":{
                  "width":210,
                  "height":784}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u29.png"}},
{
          "id":"e522985a185c4eb7868884bd74c59d55",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":213,
              "y":469},
            "size":{
              "width":210,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息（个人呈现）/u33_line.png"}},
{
          "id":"78baf31fba2d49c3a4299f215329adfd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":615},
            "size":{
              "width":200,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息（个人呈现）/u34_line.png"}},
{
          "id":"6d7532285d194cd4b4256a09198f058d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":231,
              "y":571},
            "size":{
              "width":42,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e8b0805583547afa79017e2b1fdf2f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":231,
                  "y":571},
                "size":{
                  "width":42,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u35.png"}},
{
          "id":"b02192f03fc74ebe8d1e58069d64caaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":285,
              "y":583},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7df9bbc163da442ebaa727e24cce3ca7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":285,
                  "y":583},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2ea1dc1acfc45c890c45f7056f7b1d1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":583},
            "size":{
              "width":32,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bb3f438a3044d339165347c5769b044",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":379,
                  "y":583},
                "size":{
                  "width":32,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u39.png"}},
{
          "id":"3988d2f1a3c4496e9bd04adc51052244",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":215,
              "y":685},
            "size":{
              "width":200,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息（个人呈现）/u34_line.png"}},
{
          "id":"36cbfe82ff014decafef98e56d1dcded",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":641},
            "size":{
              "width":42,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"755e490d12cb4ad7bc948915c0131840",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":641},
                "size":{
                  "width":42,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u35.png"}},
{
          "id":"efc875b506ec41719a263394cd7c1242",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":282,
              "y":653},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df962c0fa129478abbf6005a329d341d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":282,
                  "y":653},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84eda9cad05f4b8aad8534d702170656",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":376,
              "y":653},
            "size":{
              "width":32,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4819f6de297d4700ba3c3bf2a00209c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":376,
                  "y":653},
                "size":{
                  "width":32,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u39.png"}},
{
          "id":"9d619459ecad4baa955d727b59053962",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":337},
            "size":{
              "width":150,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d360850753994add852693cbeb2fda06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":337},
                "size":{
                  "width":150,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用删除确认/u69.png"}},
{
          "id":"203eb47f9fb54241b0ff351b5540caa9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":417},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"998bbc9099f2439b8fe3c21c560b6eb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":282,
                  "y":417},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad29a26a55c9468d818ef4307349541f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":533},
            "size":{
              "width":200,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息（个人呈现）/u34_line.png"}},
{
          "id":"9607c357e9954694b5933639eaf8b7ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":233,
              "y":489},
            "size":{
              "width":42,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ef6b6711b504798a22de2adfa1896b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":233,
                  "y":489},
                "size":{
                  "width":42,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u35.png"}},
{
          "id":"5b425f080e6c488a8c53ac5e528974bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":287,
              "y":501},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a971fcb3b345422eacde3ff9c764bf40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":287,
                  "y":501},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2359ba0fa72423ab7381b3d14c4532b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":381,
              "y":501},
            "size":{
              "width":32,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17772166247343d4bdbffe164a38c9d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":381,
                  "y":501},
                "size":{
                  "width":32,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u39.png"}},
{
          "id":"261c59e8b47a48dbb07e22b6cddd69fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":315},
            "size":{
              "width":1006,
              "height":752}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a63a7a8bce474ebc9f42ab8e8b3ab92d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":315},
                "size":{
                  "width":1006,
                  "height":752}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用删除确认/u80.png"}},
{
          "id":"2cd34ae33eaa4d1cb515659b312504a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":315},
            "size":{
              "width":1006,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdb5505578f4472bad5e163499e64b74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":315},
                "size":{
                  "width":1006,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用删除确认/u82.png"}},
{
          "id":"9aa610d0febc4be29234f5e649f0697c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":464,
              "y":351},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae9fd6908d4248d887b91084e97b0070",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":464,
                  "y":351},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3849528937da4c088854a88579bdb4a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":586,
              "y":465},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7437fe7996b44364ab11a6a36bfb8749",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":586,
                  "y":465},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b6b630783bd4d72a1f8ab6e91bed154",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":583,
              "y":551},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d8df416dcf5462882774948dd19b3f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":583,
                  "y":551},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e20848c82e024c5f8cbfde40fec41130",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":556},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"782cc3c575094e988bae24c61930cdd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":890,
                  "y":556},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u124.png"}},
{
          "id":"120cefc1a1f8431196a11611c3492816",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":726,
              "y":469},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8210d19783fc4a9485119c4e7e817757",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":726,
                  "y":469},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db82ccdb43244b52a3ed79b5bae97c69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":726,
              "y":556},
            "size":{
              "width":122,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0044657691394b63b9a2b7fb4e364e76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":726,
                  "y":556},
                "size":{
                  "width":122,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fd5d5fc369f4e3fb9f1f24404cacdec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":508,
              "y":640},
            "size":{
              "width":173,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee642f7ef0cc40df81c692f6c14d7ff1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":508,
                  "y":640},
                "size":{
                  "width":173,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0db1babf277141f7acaf359c76066d8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":726,
              "y":645},
            "size":{
              "width":93,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ce81a68a650429f81221598ece4eba8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":726,
                  "y":645},
                "size":{
                  "width":93,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1ab2fbac8194d60b5aa97fbdebbc6fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":277,
              "y":439},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f83f515a311f478b9a48842a7045adec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":277,
                  "y":439},
                "size":{
                  "width":70,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用删除确认/u100.png"}},
{
          "id":"3bf937779deb4fc8857adc844785fece",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":634},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"598f7ee78f504b00b7fbc0b431c2ba54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":890,
                  "y":634},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u124.png"}},
{
          "id":"cb11d4744fca48d49eb0f9aeb12e0b76",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":469},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a7b6a970f554cb59df3c0c92ba8b6d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":890,
                  "y":469},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u124.png"}},
{
          "id":"d3c1c79020334d9db76c2b36485ecd3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":1450,
              "y":210},
            "size":{
              "width":430,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"008a88ba5e0e4b9f84bf087a34491aec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":1450,
                  "y":210},
                "size":{
                  "width":430,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u88.png"}},
{
          "id":"8b722a16e345452fa42a39002369a196",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.4",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":210,
              "y":210},
            "size":{
              "width":1220,
              "height":930}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7499a416a15456b9c59c4b5b227e843",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.4",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":210,
                  "y":210},
                "size":{
                  "width":1220,
                  "height":930}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/不可修改提醒/u91.png"}},
{
          "id":"343000c327c64c77a20117083befbc43",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":527.5,
              "y":410},
            "size":{
              "width":519,
              "height":342}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57ff23e8536c4e24ac908f48cf15da50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":527.5,
                  "y":410},
                "size":{
                  "width":519,
                  "height":342}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/隐私数据删除确认_p2/u53.png"}},
{
          "id":"0cae2040fd1845ffb8456f8f92512b78",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":527.5,
              "y":410},
            "size":{
              "width":519,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de2182543b7e4acb84c80cb36a0fbdd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":527.5,
                  "y":410},
                "size":{
                  "width":519,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找回原安全密码/u63.png"}},
{
          "id":"06718dfd9ed44036af88dcafe13027cf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":976.5,
              "y":421},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b52b33b676d428499ebd051505b22e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":976.5,
                  "y":421},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u74.png"}},
{
          "id":"e12e7b0776084834ad52f35fc5e84132",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":572,
              "y":512},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"729425bcca344685be64144b858ae0b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":572,
                  "y":512},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f969ae5bec8f4f16b0600840892cec92",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":699.5,
              "y":512},
            "size":{
              "width":200,
              "height":34}},
          "adaptiveStyles":{
}},
{
          "id":"4efaf6fe606d423d826e49e6c06db664",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":548,
              "y":592},
            "size":{
              "width":121,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fce9456199e54395bde69d9b3c5a0127",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":548,
                  "y":592},
                "size":{
                  "width":121,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5110f3ba766c4591b1cccfe7fe0b14fe",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":699.5,
              "y":586},
            "size":{
              "width":200,
              "height":34}},
          "adaptiveStyles":{
}},
{
          "id":"e0f10a318d584319a916648f8c5ea2dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":926.5,
              "y":590},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a296b39d3e334222b342146ae0cfb2c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":926.5,
                  "y":590},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u124.png"}},
{
          "id":"a4bf96a4871e4081b1e6a87d5a29fc37",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":527.5,
              "y":671},
            "size":{
              "width":519,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户签约-提交成功提醒/u83_line.png"}},
{
          "id":"520fc28906f0401dbb9bd0e6d2e96c76",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":716.5,
              "y":699},
            "size":{
              "width":120,
              "height":37},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e44ae1ae5a84b0e8a15536440dd6fc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":716.5,
                  "y":699},
                "size":{
                  "width":120,
                  "height":37},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页（控制台）",
                      "target":{
                        "targetType":"page",
                        "url":"首页（控制台）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户签约-提交成功提醒/u84.png"}},
{
          "id":"3bd16e7f9dbb4c79b63622fa8f28dc6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":716,
              "y":556},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"467c0ed7656b4209b5847d4ef526d2cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":716,
                  "y":556},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"904c0d736d6a403eb51f0e5f0d1ae549",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":698.5,
              "y":556},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8cea1778b3c4b8abdb0dee357424bd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":698.5,
                  "y":556},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u69.png"}},
{
          "id":"7fb0410243574e468dc9f5c75abb48b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":716,
              "y":637},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53d7987332d8469d90597c1147a0bfcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":716,
                  "y":637},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfecb8f6b5df4f9891551059d1b797b8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":698.5,
              "y":637},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d03cbcc9e6b4be19556f8e55c347bf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":698.5,
                  "y":637},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u69.png"}}]}},
  "masters":{
    "f73d698e06464df78e2f277ca77e6c60":{
      "packageId":"f73d698e06464df78e2f277ca77e6c60",
      "type":"Axure:Master",
      "name":"控制台头部框架",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1a8ee24928a94860889c9b047390fbf5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "opacity":"0.3",
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "size":{
                "width":1219,
                "height":930},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f6d5da329001418bad0c45f297bae802",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "opacity":"0.3",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "size":{
                    "width":1219,
                    "height":930},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/应用删除确认/u1.png"}},
{
            "id":"2b596599a1a2483d84e1634a29aaddec",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":100},
              "size":{
                "width":1219,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/帮助/u43_line.png"}},
{
            "id":"06a4f09ba941472c84ee4ff1c0e16d57",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":797,
                "y":41},
              "size":{
                "width":235,
                "height":33}},
            "adaptiveStyles":{
}},
{
            "id":"2d1981c2bb3a4bbf98d29d5eb4a95f05",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":1031,
                "y":41},
              "size":{
                "width":44,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5c489b146ee44a60b5c40b1930b87fea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":1031,
                    "y":41},
                  "size":{
                    "width":44,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 支付查询",
                        "target":{
                          "targetType":"page",
                          "url":"支付查询.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u45.png"}},
{
            "id":"014e382808854576ac2a5acf6f38b3a2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":35,
                "y":20},
              "size":{
                "width":125,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f984bdbcccaa4abf9aac379604b9f79d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":35,
                    "y":20},
                  "size":{
                    "width":125,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/帮助/u47.png"}},
{
            "id":"34dbe10428ea41ee8cdbb51d7c3ed73a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "location":{
                "x":200,
                "y":41},
              "size":{
                "width":85,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"75e5676d5e144345b4afc81cd6c00d1e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "location":{
                    "x":200,
                    "y":41},
                  "size":{
                    "width":85,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页（控制台）",
                        "target":{
                          "targetType":"page",
                          "url":"首页（控制台）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1ca0ab308cb043d29a39532870348bc8",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":297,
                "y":51},
              "size":{
                "width":23,
                "height":18}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e5cb1b54f0444dcaa8287c88b30ce81b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":297,
                    "y":51},
                  "size":{
                    "width":23,
                    "height":18}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/基本信息（个人呈现）/u39.png"}},
{
            "id":"59565fd155404fd087e51bcb3b8ceb97",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":323,
                "y":45},
              "size":{
                "width":97,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13823699df9d415380fe6b2f3d00fb35",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":323,
                    "y":45},
                  "size":{
                    "width":97,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"605de75946a24d95b684f993a7f6ad55",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":442,
                "y":49},
              "size":{
                "width":23,
                "height":18}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e8228405980441f7a72035454d5f7935",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":442,
                    "y":49},
                  "size":{
                    "width":23,
                    "height":18}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/基本信息（个人呈现）/u39.png"}},
{
            "id":"820860e588cd4af3ae78284ddd63919b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":465,
                "y":44},
              "size":{
                "width":41,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7b2310bbfbdc40dbb3e46fb905d8dfde",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":465,
                    "y":44},
                  "size":{
                    "width":41,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a2a9edf511b04234929b917b016ddb6b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":422,
                "y":50},
              "size":{
                "width":16,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"43226eb6ed254f369986d85d7e2dfe5c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":422,
                    "y":50},
                  "size":{
                    "width":16,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle 应用选择",
                        "objectsToFades":[{
                            "objectPath":["fb749e8082bd4d74bd5870d3c68d974f"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/应用删除确认/u19.png"}},
{
            "id":"5d81d9693543430bba2efaf7426207c8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":680,
                "y":36},
              "size":{
                "width":50,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dcd37788d84c4d47bfcf05ff917c206f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":680,
                    "y":36},
                  "size":{
                    "width":50,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/帮助/u51.png"}},
{
            "id":"fcdd9f24623747709c69b6ad0e7e80dd",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":508,
                "y":50},
              "size":{
                "width":16,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4313aa7229094c86965ae8cb0a0adb14",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":508,
                    "y":50},
                  "size":{
                    "width":16,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle 操作方式",
                        "objectsToFades":[{
                            "objectPath":["ae1fcf57d46043f98c2706608c5e2f95"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/应用删除确认/u19.png"}},
{
            "id":"ae1fcf57d46043f98c2706608c5e2f95",
            "label":"操作方式",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":453,
                "y":97},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"d3219cc2308d47a4aa9b4893dca6c30c",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"b3edda47af754c9ebbefbe5fad270a06",
                    "label":"",
                    "parentDynamicPanel":"ae1fcf57d46043f98c2706608c5e2f95",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":74,
                        "height":85}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"fc35079c726e4782ae1d4e64b728b325",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ae1fcf57d46043f98c2706608c5e2f95",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":74,
                            "height":85}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/应用删除确认/u26.png"}},
{
                    "id":"0253fe835bc541b580ec72a73e5fa3ca",
                    "label":"",
                    "parentDynamicPanel":"ae1fcf57d46043f98c2706608c5e2f95",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "location":{
                        "x":22,
                        "y":10},
                      "size":{
                        "width":29,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"cf6774928fd0438a87ba99c728246f8a",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ae1fcf57d46043f98c2706608c5e2f95",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "location":{
                            "x":22,
                            "y":10},
                          "size":{
                            "width":29,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"033f189a92924add82ab0b12ad78bcda",
                    "label":"",
                    "parentDynamicPanel":"ae1fcf57d46043f98c2706608c5e2f95",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "location":{
                        "x":21,
                        "y":44},
                      "size":{
                        "width":29,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"eb2a1e33f7d84607b955cb8d0bf054ec",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ae1fcf57d46043f98c2706608c5e2f95",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "location":{
                            "x":21,
                            "y":44},
                          "size":{
                            "width":29,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}]}]},
{
            "id":"fb749e8082bd4d74bd5870d3c68d974f",
            "label":"应用选择",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":323,
                "y":93},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"f9f4098dfa334d0a885953b7a55dda9a",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"aef104deff654441937f3c6b24d0466b",
                    "label":"",
                    "parentDynamicPanel":"fb749e8082bd4d74bd5870d3c68d974f",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":96,
                        "height":120}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a5884c74b73a432fbda3c35b22e24923",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fb749e8082bd4d74bd5870d3c68d974f",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":96,
                            "height":120}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/应用删除确认/u33.png"}},
{
                    "id":"688e10527eb0438eb943179c46e019c3",
                    "label":"",
                    "parentDynamicPanel":"fb749e8082bd4d74bd5870d3c68d974f",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "location":{
                        "x":2,
                        "y":10},
                      "size":{
                        "width":84,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2289a2646d2f4e56a4a2d208d087e8f8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fb749e8082bd4d74bd5870d3c68d974f",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "location":{
                            "x":2,
                            "y":10},
                          "size":{
                            "width":84,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"f44c87262221477eb55f76e75d1e584a",
                    "label":"",
                    "parentDynamicPanel":"fb749e8082bd4d74bd5870d3c68d974f",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "location":{
                        "x":2,
                        "y":44},
                      "size":{
                        "width":84,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a4042af3879e4086a09b3d6543575371",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fb749e8082bd4d74bd5870d3c68d974f",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "location":{
                            "x":2,
                            "y":44},
                          "size":{
                            "width":84,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"1e08709d4afa44e79996463013d6b875",
                    "label":"",
                    "parentDynamicPanel":"fb749e8082bd4d74bd5870d3c68d974f",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "location":{
                        "x":6,
                        "y":80},
                      "size":{
                        "width":84,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"985d0e9376ed43b2a2b871e489e7e707",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fb749e8082bd4d74bd5870d3c68d974f",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "location":{
                            "x":6,
                            "y":80},
                          "size":{
                            "width":84,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}]}]},
{
            "id":"ee8d90f878df4fd6b60480043b5e69f2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1150,
                "y":30},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cd1053b1be44480c8e68703e58a1a991",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1150,
                    "y":30},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle 右侧边栏",
                        "objectsToFades":[{
                            "objectPath":["eb4c09396e3340e88f0993078ab10ac4"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u53.png"}},
{
            "id":"eb4c09396e3340e88f0993078ab10ac4",
            "label":"右侧边栏",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":1019,
                "y":105},
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"02fa60b966c0415b90ecb350ac749437",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"ffd51f1dc88147c786e1f7f37d9e1bc1",
                    "label":"",
                    "parentDynamicPanel":"eb4c09396e3340e88f0993078ab10ac4",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":200,
                        "height":205}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f022651d3ba547d1865b0cb53d81d2ff",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"eb4c09396e3340e88f0993078ab10ac4",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":200,
                            "height":205}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/帮助/u56.png"}},
{
                    "id":"58d99ea10de74cdd91624c93faa09ec4",
                    "label":"",
                    "parentDynamicPanel":"eb4c09396e3340e88f0993078ab10ac4",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Negreta', 'Arial'",
                      "fontSize":"18px",
                      "fontWeight":"700",
                      "location":{
                        "x":12,
                        "y":26},
                      "size":{
                        "width":174,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"be2956459a5c46158023b331d558b41f",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"eb4c09396e3340e88f0993078ab10ac4",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Negreta', 'Arial'",
                          "fontSize":"18px",
                          "fontWeight":"700",
                          "location":{
                            "x":12,
                            "y":26},
                          "size":{
                            "width":174,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"8ba7a10c7f2340258197e5e0c49474d8",
                    "label":"",
                    "parentDynamicPanel":"eb4c09396e3340e88f0993078ab10ac4",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontSize":"16px",
                      "location":{
                        "x":41,
                        "y":73},
                      "size":{
                        "width":120,
                        "height":30},
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"51b1c8ab4cd249758f11eff4ed718f6c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"eb4c09396e3340e88f0993078ab10ac4",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"16px",
                          "location":{
                            "x":41,
                            "y":73},
                          "size":{
                            "width":120,
                            "height":30},
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 基本信息（个人呈现）",
                                "target":{
                                  "targetType":"page",
                                  "url":"基本信息（个人呈现）.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/帮助/u60.png"}},
{
                    "id":"aba194cc22864490ab97f123bf259f84",
                    "label":"",
                    "parentDynamicPanel":"eb4c09396e3340e88f0993078ab10ac4",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":75,
                        "y":128},
                      "size":{
                        "width":50,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"84f0aed9e6ca46abbda9efbddaf5e0d3",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"eb4c09396e3340e88f0993078ab10ac4",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":75,
                            "y":128},
                          "size":{
                            "width":50,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/帮助/u62.png"}}]}]}]}}},
  "objectPaths":{
    "7d571a3607e34f6cbdfa6e3734d60b96":{
      "scriptId":"u0",
      "1a8ee24928a94860889c9b047390fbf5":{
        "scriptId":"u1"},
      "f6d5da329001418bad0c45f297bae802":{
        "scriptId":"u2"},
      "2b596599a1a2483d84e1634a29aaddec":{
        "scriptId":"u3"},
      "06a4f09ba941472c84ee4ff1c0e16d57":{
        "scriptId":"u4"},
      "2d1981c2bb3a4bbf98d29d5eb4a95f05":{
        "scriptId":"u5"},
      "5c489b146ee44a60b5c40b1930b87fea":{
        "scriptId":"u6"},
      "014e382808854576ac2a5acf6f38b3a2":{
        "scriptId":"u7"},
      "f984bdbcccaa4abf9aac379604b9f79d":{
        "scriptId":"u8"},
      "34dbe10428ea41ee8cdbb51d7c3ed73a":{
        "scriptId":"u9"},
      "75e5676d5e144345b4afc81cd6c00d1e":{
        "scriptId":"u10"},
      "1ca0ab308cb043d29a39532870348bc8":{
        "scriptId":"u11"},
      "e5cb1b54f0444dcaa8287c88b30ce81b":{
        "scriptId":"u12"},
      "59565fd155404fd087e51bcb3b8ceb97":{
        "scriptId":"u13"},
      "13823699df9d415380fe6b2f3d00fb35":{
        "scriptId":"u14"},
      "605de75946a24d95b684f993a7f6ad55":{
        "scriptId":"u15"},
      "e8228405980441f7a72035454d5f7935":{
        "scriptId":"u16"},
      "820860e588cd4af3ae78284ddd63919b":{
        "scriptId":"u17"},
      "7b2310bbfbdc40dbb3e46fb905d8dfde":{
        "scriptId":"u18"},
      "a2a9edf511b04234929b917b016ddb6b":{
        "scriptId":"u19"},
      "43226eb6ed254f369986d85d7e2dfe5c":{
        "scriptId":"u20"},
      "5d81d9693543430bba2efaf7426207c8":{
        "scriptId":"u21"},
      "dcd37788d84c4d47bfcf05ff917c206f":{
        "scriptId":"u22"},
      "fcdd9f24623747709c69b6ad0e7e80dd":{
        "scriptId":"u23"},
      "4313aa7229094c86965ae8cb0a0adb14":{
        "scriptId":"u24"},
      "ae1fcf57d46043f98c2706608c5e2f95":{
        "scriptId":"u25"},
      "b3edda47af754c9ebbefbe5fad270a06":{
        "scriptId":"u26"},
      "fc35079c726e4782ae1d4e64b728b325":{
        "scriptId":"u27"},
      "0253fe835bc541b580ec72a73e5fa3ca":{
        "scriptId":"u28"},
      "cf6774928fd0438a87ba99c728246f8a":{
        "scriptId":"u29"},
      "033f189a92924add82ab0b12ad78bcda":{
        "scriptId":"u30"},
      "eb2a1e33f7d84607b955cb8d0bf054ec":{
        "scriptId":"u31"},
      "fb749e8082bd4d74bd5870d3c68d974f":{
        "scriptId":"u32"},
      "aef104deff654441937f3c6b24d0466b":{
        "scriptId":"u33"},
      "a5884c74b73a432fbda3c35b22e24923":{
        "scriptId":"u34"},
      "688e10527eb0438eb943179c46e019c3":{
        "scriptId":"u35"},
      "2289a2646d2f4e56a4a2d208d087e8f8":{
        "scriptId":"u36"},
      "f44c87262221477eb55f76e75d1e584a":{
        "scriptId":"u37"},
      "a4042af3879e4086a09b3d6543575371":{
        "scriptId":"u38"},
      "1e08709d4afa44e79996463013d6b875":{
        "scriptId":"u39"},
      "985d0e9376ed43b2a2b871e489e7e707":{
        "scriptId":"u40"},
      "ee8d90f878df4fd6b60480043b5e69f2":{
        "scriptId":"u41"},
      "cd1053b1be44480c8e68703e58a1a991":{
        "scriptId":"u42"},
      "eb4c09396e3340e88f0993078ab10ac4":{
        "scriptId":"u43"},
      "ffd51f1dc88147c786e1f7f37d9e1bc1":{
        "scriptId":"u44"},
      "f022651d3ba547d1865b0cb53d81d2ff":{
        "scriptId":"u45"},
      "58d99ea10de74cdd91624c93faa09ec4":{
        "scriptId":"u46"},
      "be2956459a5c46158023b331d558b41f":{
        "scriptId":"u47"},
      "8ba7a10c7f2340258197e5e0c49474d8":{
        "scriptId":"u48"},
      "51b1c8ab4cd249758f11eff4ed718f6c":{
        "scriptId":"u49"},
      "aba194cc22864490ab97f123bf259f84":{
        "scriptId":"u50"},
      "84f0aed9e6ca46abbda9efbddaf5e0d3":{
        "scriptId":"u51"}},
    "fbf244d07fa040f3b757b4e535eded9f":{
      "scriptId":"u52"},
    "ff040280c0e945fca137b3da94311a02":{
      "scriptId":"u53"},
    "e522985a185c4eb7868884bd74c59d55":{
      "scriptId":"u54"},
    "78baf31fba2d49c3a4299f215329adfd":{
      "scriptId":"u55"},
    "6d7532285d194cd4b4256a09198f058d":{
      "scriptId":"u56"},
    "8e8b0805583547afa79017e2b1fdf2f3":{
      "scriptId":"u57"},
    "b02192f03fc74ebe8d1e58069d64caaa":{
      "scriptId":"u58"},
    "7df9bbc163da442ebaa727e24cce3ca7":{
      "scriptId":"u59"},
    "b2ea1dc1acfc45c890c45f7056f7b1d1":{
      "scriptId":"u60"},
    "7bb3f438a3044d339165347c5769b044":{
      "scriptId":"u61"},
    "3988d2f1a3c4496e9bd04adc51052244":{
      "scriptId":"u62"},
    "36cbfe82ff014decafef98e56d1dcded":{
      "scriptId":"u63"},
    "755e490d12cb4ad7bc948915c0131840":{
      "scriptId":"u64"},
    "efc875b506ec41719a263394cd7c1242":{
      "scriptId":"u65"},
    "df962c0fa129478abbf6005a329d341d":{
      "scriptId":"u66"},
    "84eda9cad05f4b8aad8534d702170656":{
      "scriptId":"u67"},
    "4819f6de297d4700ba3c3bf2a00209c5":{
      "scriptId":"u68"},
    "9d619459ecad4baa955d727b59053962":{
      "scriptId":"u69"},
    "d360850753994add852693cbeb2fda06":{
      "scriptId":"u70"},
    "203eb47f9fb54241b0ff351b5540caa9":{
      "scriptId":"u71"},
    "998bbc9099f2439b8fe3c21c560b6eb4":{
      "scriptId":"u72"},
    "ad29a26a55c9468d818ef4307349541f":{
      "scriptId":"u73"},
    "9607c357e9954694b5933639eaf8b7ba":{
      "scriptId":"u74"},
    "0ef6b6711b504798a22de2adfa1896b2":{
      "scriptId":"u75"},
    "5b425f080e6c488a8c53ac5e528974bb":{
      "scriptId":"u76"},
    "a971fcb3b345422eacde3ff9c764bf40":{
      "scriptId":"u77"},
    "c2359ba0fa72423ab7381b3d14c4532b":{
      "scriptId":"u78"},
    "17772166247343d4bdbffe164a38c9d1":{
      "scriptId":"u79"},
    "261c59e8b47a48dbb07e22b6cddd69fe":{
      "scriptId":"u80"},
    "a63a7a8bce474ebc9f42ab8e8b3ab92d":{
      "scriptId":"u81"},
    "2cd34ae33eaa4d1cb515659b312504a9":{
      "scriptId":"u82"},
    "fdb5505578f4472bad5e163499e64b74":{
      "scriptId":"u83"},
    "9aa610d0febc4be29234f5e649f0697c":{
      "scriptId":"u84"},
    "ae9fd6908d4248d887b91084e97b0070":{
      "scriptId":"u85"},
    "3849528937da4c088854a88579bdb4a6":{
      "scriptId":"u86"},
    "7437fe7996b44364ab11a6a36bfb8749":{
      "scriptId":"u87"},
    "0b6b630783bd4d72a1f8ab6e91bed154":{
      "scriptId":"u88"},
    "7d8df416dcf5462882774948dd19b3f9":{
      "scriptId":"u89"},
    "e20848c82e024c5f8cbfde40fec41130":{
      "scriptId":"u90"},
    "782cc3c575094e988bae24c61930cdd0":{
      "scriptId":"u91"},
    "120cefc1a1f8431196a11611c3492816":{
      "scriptId":"u92"},
    "8210d19783fc4a9485119c4e7e817757":{
      "scriptId":"u93"},
    "db82ccdb43244b52a3ed79b5bae97c69":{
      "scriptId":"u94"},
    "0044657691394b63b9a2b7fb4e364e76":{
      "scriptId":"u95"},
    "5fd5d5fc369f4e3fb9f1f24404cacdec":{
      "scriptId":"u96"},
    "ee642f7ef0cc40df81c692f6c14d7ff1":{
      "scriptId":"u97"},
    "0db1babf277141f7acaf359c76066d8a":{
      "scriptId":"u98"},
    "8ce81a68a650429f81221598ece4eba8":{
      "scriptId":"u99"},
    "a1ab2fbac8194d60b5aa97fbdebbc6fc":{
      "scriptId":"u100"},
    "f83f515a311f478b9a48842a7045adec":{
      "scriptId":"u101"},
    "3bf937779deb4fc8857adc844785fece":{
      "scriptId":"u102"},
    "598f7ee78f504b00b7fbc0b431c2ba54":{
      "scriptId":"u103"},
    "cb11d4744fca48d49eb0f9aeb12e0b76":{
      "scriptId":"u104"},
    "1a7b6a970f554cb59df3c0c92ba8b6d8":{
      "scriptId":"u105"},
    "d3c1c79020334d9db76c2b36485ecd3f":{
      "scriptId":"u106"},
    "008a88ba5e0e4b9f84bf087a34491aec":{
      "scriptId":"u107"},
    "8b722a16e345452fa42a39002369a196":{
      "scriptId":"u108"},
    "d7499a416a15456b9c59c4b5b227e843":{
      "scriptId":"u109"},
    "343000c327c64c77a20117083befbc43":{
      "scriptId":"u110"},
    "57ff23e8536c4e24ac908f48cf15da50":{
      "scriptId":"u111"},
    "0cae2040fd1845ffb8456f8f92512b78":{
      "scriptId":"u112"},
    "de2182543b7e4acb84c80cb36a0fbdd1":{
      "scriptId":"u113"},
    "06718dfd9ed44036af88dcafe13027cf":{
      "scriptId":"u114"},
    "1b52b33b676d428499ebd051505b22e4":{
      "scriptId":"u115"},
    "e12e7b0776084834ad52f35fc5e84132":{
      "scriptId":"u116"},
    "729425bcca344685be64144b858ae0b6":{
      "scriptId":"u117"},
    "f969ae5bec8f4f16b0600840892cec92":{
      "scriptId":"u118"},
    "4efaf6fe606d423d826e49e6c06db664":{
      "scriptId":"u119"},
    "fce9456199e54395bde69d9b3c5a0127":{
      "scriptId":"u120"},
    "5110f3ba766c4591b1cccfe7fe0b14fe":{
      "scriptId":"u121"},
    "e0f10a318d584319a916648f8c5ea2dd":{
      "scriptId":"u122"},
    "a296b39d3e334222b342146ae0cfb2c7":{
      "scriptId":"u123"},
    "a4bf96a4871e4081b1e6a87d5a29fc37":{
      "scriptId":"u124"},
    "520fc28906f0401dbb9bd0e6d2e96c76":{
      "scriptId":"u125"},
    "1e44ae1ae5a84b0e8a15536440dd6fc1":{
      "scriptId":"u126"},
    "3bd16e7f9dbb4c79b63622fa8f28dc6a":{
      "scriptId":"u127"},
    "467c0ed7656b4209b5847d4ef526d2cc":{
      "scriptId":"u128"},
    "904c0d736d6a403eb51f0e5f0d1ae549":{
      "scriptId":"u129"},
    "d8cea1778b3c4b8abdb0dee357424bd9":{
      "scriptId":"u130"},
    "7fb0410243574e468dc9f5c75abb48b8":{
      "scriptId":"u131"},
    "53d7987332d8469d90597c1147a0bfcc":{
      "scriptId":"u132"},
    "bfecb8f6b5df4f9891551059d1b797b8":{
      "scriptId":"u133"},
    "8d03cbcc9e6b4be19556f8e55c347bf8":{
      "scriptId":"u134"}}});