$axure.loadCurrentPage({
  "url":"详情.html",
  "generationDate":new Date(1469168370175.6),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e113ca0240234a71abb0f99d0546b441",
    "type":"Axure:Page",
    "name":"详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0879989fbe0a4254ae1605f475c2df9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":142},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f993413c40249b2a59e5ae1d57b06ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":142},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56041d1a63264d0f9d7e2cdab3c50b4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":632},
            "size":{
              "width":121,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2e6d46e65d14ee5a3edeaeed8a4206a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":632},
                "size":{
                  "width":121,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8cf609a5af2d465eaccd8b173913bc14",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":840},
            "size":{
              "width":121,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db4d91ab5d474172a286c978ff434177",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":840},
                "size":{
                  "width":121,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d5d9e032e4c4153a7112b53db950270",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":175},
            "size":{
              "width":938,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/详情/u6_line.png"}},
{
          "id":"80e8b8802b744bc2911f23c40379f440",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":670},
            "size":{
              "width":938,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/详情/u6_line.png"}},
{
          "id":"54ddf83fc11944e09b69575442cb136f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":109,
              "y":885},
            "size":{
              "width":938,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/详情/u6_line.png"}},
{
          "id":"3d901c9b5a2947f2a68a27f40b58a6fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":168,
              "y":926},
            "size":{
              "width":79,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9e885ac762c4004a6aeba7e62c84b62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":168,
                  "y":926},
                "size":{
                  "width":79,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a852d003e734e35a1b1f9d64e3154a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":152,
              "y":712},
            "size":{
              "width":79,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a103c41837394ee7bc2c455fa0aadfb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":152,
                  "y":712},
                "size":{
                  "width":79,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98962f7efda44523ac3762730bdf2fbc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":131,
              "y":203},
            "size":{
              "width":105,
              "height":384}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75e616dbcb124e8daa47163d43c30256",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":131,
                  "y":203},
                "size":{
                  "width":105,
                  "height":384}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c545ecc9fadc40eeb55a176df3123278",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":60},
            "size":{
              "width":1180,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6a9b5be3def40ca8f71b595e8a516cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":60},
                "size":{
                  "width":1180,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收款账号管理/u0.png"}},
{
          "id":"ecb1f42e60c5434e83c54b0059bdb883",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":81},
            "size":{
              "width":46,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"567c9c98a3e04e25b2dfbc070960dc02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":98,
                  "y":81},
                "size":{
                  "width":46,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"513c3385e08546eeb5fbe4aee9c12d90",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":82},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60762168f675416581f5578d3fdb7069",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":82},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a276438dc1dc49c180937f302b3b70ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1150,
              "y":81},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5b85ad485c6462abc28095d91738615",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1150,
                  "y":81},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff903221b5544b619a67d373ed467bd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":203},
            "size":{
              "width":251,
              "height":384}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e73e4fa537a643fdb4caaa72a816085c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":203},
                "size":{
                  "width":251,
                  "height":384}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"010ac90ea4724751aee0287fc2583ab2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":712},
            "size":{
              "width":70,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52e15e46f9cc4c0791da35011bc618f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":712},
                "size":{
                  "width":70,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93a971e054104a1db009a3c478dbac10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":926},
            "size":{
              "width":78,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3317858905f4f2795a347307153a14e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":926},
                "size":{
                  "width":78,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "0879989fbe0a4254ae1605f475c2df9c":{
      "scriptId":"u0"},
    "5f993413c40249b2a59e5ae1d57b06ab":{
      "scriptId":"u1"},
    "56041d1a63264d0f9d7e2cdab3c50b4b":{
      "scriptId":"u2"},
    "e2e6d46e65d14ee5a3edeaeed8a4206a":{
      "scriptId":"u3"},
    "8cf609a5af2d465eaccd8b173913bc14":{
      "scriptId":"u4"},
    "db4d91ab5d474172a286c978ff434177":{
      "scriptId":"u5"},
    "1d5d9e032e4c4153a7112b53db950270":{
      "scriptId":"u6"},
    "80e8b8802b744bc2911f23c40379f440":{
      "scriptId":"u7"},
    "54ddf83fc11944e09b69575442cb136f":{
      "scriptId":"u8"},
    "3d901c9b5a2947f2a68a27f40b58a6fc":{
      "scriptId":"u9"},
    "e9e885ac762c4004a6aeba7e62c84b62":{
      "scriptId":"u10"},
    "2a852d003e734e35a1b1f9d64e3154a8":{
      "scriptId":"u11"},
    "a103c41837394ee7bc2c455fa0aadfb4":{
      "scriptId":"u12"},
    "98962f7efda44523ac3762730bdf2fbc":{
      "scriptId":"u13"},
    "75e616dbcb124e8daa47163d43c30256":{
      "scriptId":"u14"},
    "c545ecc9fadc40eeb55a176df3123278":{
      "scriptId":"u15"},
    "c6a9b5be3def40ca8f71b595e8a516cf":{
      "scriptId":"u16"},
    "ecb1f42e60c5434e83c54b0059bdb883":{
      "scriptId":"u17"},
    "567c9c98a3e04e25b2dfbc070960dc02":{
      "scriptId":"u18"},
    "513c3385e08546eeb5fbe4aee9c12d90":{
      "scriptId":"u19"},
    "60762168f675416581f5578d3fdb7069":{
      "scriptId":"u20"},
    "a276438dc1dc49c180937f302b3b70ca":{
      "scriptId":"u21"},
    "f5b85ad485c6462abc28095d91738615":{
      "scriptId":"u22"},
    "ff903221b5544b619a67d373ed467bd3":{
      "scriptId":"u23"},
    "e73e4fa537a643fdb4caaa72a816085c":{
      "scriptId":"u24"},
    "010ac90ea4724751aee0287fc2583ab2":{
      "scriptId":"u25"},
    "52e15e46f9cc4c0791da35011bc618f5":{
      "scriptId":"u26"},
    "93a971e054104a1db009a3c478dbac10":{
      "scriptId":"u27"},
    "f3317858905f4f2795a347307153a14e":{
      "scriptId":"u28"}}});