$axure.loadCurrentPage({
  "url":"侦测系统安装包.html",
  "generationDate":new Date(1469168369748.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9bc42aa15cdc42e681e755913fdec4a0",
    "type":"Axure:Page",
    "name":"侦测系统安装包",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c50c4b3630c34cb1af1c5fe98928f4f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":234,
              "y":150},
            "size":{
              "width":529,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79b6b68feca24caa94f8ea587220e7b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":234,
                  "y":150},
                "size":{
                  "width":529,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c47aaafe5bb14a3b882f9afd39c0c754",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":231,
              "y":592},
            "size":{
              "width":411,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b5c93de19b34351b00601be711319e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":231,
                  "y":592},
                "size":{
                  "width":411,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50bf40ad946a498b8385fbb816a720c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":234,
              "y":290},
            "size":{
              "width":788,
              "height":112}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24f0ebf68a074185b45c1f1e8094bb5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":234,
                  "y":290},
                "size":{
                  "width":788,
                  "height":112}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20768f6e68a34e95a95cb22286294e7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1084,
              "y":306},
            "size":{
              "width":209,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f561b2cdbd6a42c6a0ceeeff4f649fe4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1084,
                  "y":306},
                "size":{
                  "width":209,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ddcb984255f44f5a8c153d535c40820e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":235,
              "y":452},
            "size":{
              "width":229,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2851dc4b41694c52802c4807ccf46f73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":235,
                  "y":452},
                "size":{
                  "width":229,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "c50c4b3630c34cb1af1c5fe98928f4f3":{
      "scriptId":"u0"},
    "79b6b68feca24caa94f8ea587220e7b6":{
      "scriptId":"u1"},
    "c47aaafe5bb14a3b882f9afd39c0c754":{
      "scriptId":"u2"},
    "0b5c93de19b34351b00601be711319e8":{
      "scriptId":"u3"},
    "50bf40ad946a498b8385fbb816a720c0":{
      "scriptId":"u4"},
    "24f0ebf68a074185b45c1f1e8094bb5e":{
      "scriptId":"u5"},
    "20768f6e68a34e95a95cb22286294e7b":{
      "scriptId":"u6"},
    "f561b2cdbd6a42c6a0ceeeff4f649fe4":{
      "scriptId":"u7"},
    "ddcb984255f44f5a8c153d535c40820e":{
      "scriptId":"u8"},
    "2851dc4b41694c52802c4807ccf46f73":{
      "scriptId":"u9"}}});