$axure.loadCurrentPage({
  "url":"商户签约-结算信息.html",
  "generationDate":new Date(1458553410015.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"aefb652522e841c2964fc9070246360b",
    "type":"Axure:Page",
    "name":"商户签约-结算信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0fb23047301148e09583a60ccb229b40",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":200},
            "size":{
              "width":1360,
              "height":810}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bf00121b4a243b18e290d2d2486fc49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":200},
                "size":{
                  "width":1360,
                  "height":810}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-结算信息/u0.png"}},
{
          "id":"b598508e51054d9ca344157f2304c7dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":472,
              "y":497},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81d49d15cf534b7c970c27d12d0227e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":472,
                  "y":497},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"642eada149b240c89a7f6d29083d01a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":472,
              "y":434},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72867ee314b742d4aad83216b02f0f75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":472,
                  "y":434},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89fbb191210b4574a1cef8efa5dd51c7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":582,
              "y":497},
            "size":{
              "width":220,
              "height":23}},
          "adaptiveStyles":{
}},
{
          "id":"c9f7ff7cc05e44a3981ef0e22c753afd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":944,
              "y":435},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8951a6e5dcd546799cf953092e1d8da0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":944,
                  "y":435},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab627149002a4ec1bbd9dab6f8070336",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":1055,
              "y":435},
            "size":{
              "width":220,
              "height":23}},
          "adaptiveStyles":{
}},
{
          "id":"19ef5993aabe463396b33e437a963557",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":485,
              "y":377},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a573fdc988c4466ca18feb6cbb2248e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":485,
                  "y":377},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8a9455413da4c99860acc2e92d9a2de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":442,
              "y":569},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7422a9300364799b5337a90165b1abc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":442,
                  "y":569},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cce16aecdf784038aa87c6e3ca476822",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":582,
              "y":569},
            "size":{
              "width":195,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ea8856242e904c48a57726574f88d624",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":797,
              "y":569},
            "size":{
              "width":180,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"0783fdfc48e44b75847be23fa1f96f70",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":446,
              "y":660},
            "size":{
              "width":838,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户签约-基本信息（个人）/u35_line.png"}},
{
          "id":"d7c7c793da2e423987c789c1c137ece2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":811},
            "size":{
              "width":838,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户签约-基本信息（个人）/u35_line.png"}},
{
          "id":"939d2229676f46ccb7e4b6b6a72ade2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":705,
              "y":896},
            "size":{
              "width":272,
              "height":42},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fcdc8f96a344bc787bfee42e012d7cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":705,
                  "y":896},
                "size":{
                  "width":272,
                  "height":42},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u68.png"}},
{
          "id":"e8af2dd0584145e99659a71d66e8d47a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":927,
              "y":380},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c1b4d374ace46c498e254a5707b96fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":927,
                  "y":380},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d5bdadd6627450eb6f393394c961901",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1145,
              "y":383},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a745eec77cf046dabf2160b4aa603708",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1145,
                  "y":383},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"5683a23ef4ba4d1e8d8d20d3237e7040",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1045,
              "y":383},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c46b2e13926f4754bab03c61d6087385",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1045,
                  "y":383},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"3669e1ee37c84591b757bcabb5ceff9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":587,
              "y":379},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2aa78bd855245caaf3fb222b591a9eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":587,
                  "y":379},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fede94889c784fc2b0077f5f81b3d6d9",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":582,
              "y":434},
            "size":{
              "width":220,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"57998208ba65465da802be6ec8301819",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":454,
              "y":701},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b95aa3c8e5fd4259a15038a06c5cd34c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":454,
                  "y":701},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9449e51486334ba58b2c22e79e05213b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":578,
              "y":703},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6248099dd63b48e781a773710c4fc1a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":578,
                  "y":703},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58d7417586554da4ab7487cf6dce7f7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":928,
              "y":704},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cfe94bb809742398455fbfb3705f968",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":928,
                  "y":704},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ffa9ba7f13f84aeeaec402da56dbeefd",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":1042,
              "y":704},
            "size":{
              "width":220,
              "height":23}},
          "adaptiveStyles":{
}},
{
          "id":"ee377557bbcd40d7b852d9751044ef44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":1660,
              "y":230},
            "size":{
              "width":430,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b576f756922441f98f9e1174da7497b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":1660,
                  "y":230},
                "size":{
                  "width":430,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u88.png"}},
{
          "id":"8d666c81098946329401de3330d288c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":467},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1aef4875f524800917a8eb7137cab23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":467},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7a87f62f43a4293b4a04cfb380c0258",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":582,
              "y":467},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f867aeb47a064e9e949ab0037a052a97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":582,
                  "y":467},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u81.png"}},
{
          "id":"b4f4916d106347d8a149389f3f2dd5bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1073,
              "y":468},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7fbc9abaaf343d3aa42955b8fad7643",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1073,
                  "y":468},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2bdbb091eaa2455fbb3fd338b19f883f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1055,
              "y":468},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60b9b6cdc4a748eda73ad3b0efc67017",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1055,
                  "y":468},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u81.png"}},
{
          "id":"641bb72932b14cbd9827d2bcc40debd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":520},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f402f8d6f561428682445e031215213a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":520},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c280f767c4784fdc871582e011e12326",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":582,
              "y":520},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d743579bd5364a98b7659dc2ecc04322",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":582,
                  "y":520},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u81.png"}},
{
          "id":"e386c7e4c2564b93a6924576cfd34496",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":608},
            "size":{
              "width":131,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df18602123ed48b9b3c23c569ef61ca0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":608},
                "size":{
                  "width":131,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5f38cfaa14349ddbab7b940cb81c444",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":582,
              "y":608},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"707d3869bb9d408cbb0e065b173c0478",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":582,
                  "y":608},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u81.png"}},
{
          "id":"6090ca4356694189857e50b457ac9c8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":553},
            "size":{
              "width":37,
              "height":39},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22ebb905205a4e66beec3541b13f2695",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":553},
                "size":{
                  "width":37,
                  "height":39},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-结算信息/u54.png"}},
{
          "id":"f9e79e529200459db8b7b81b60a78369",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":292,
              "y":565},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f8710ea58f14a0aaf0310193dd6ad6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":292,
                  "y":565},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe05c48b64544210885192d77e72df6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":247,
              "y":782},
            "size":{
              "width":37,
              "height":39},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ff1fc9f78174f06ae1df52191d6a073",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":247,
                  "y":782},
                "size":{
                  "width":37,
                  "height":39},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-结算信息/u58.png"}},
{
          "id":"32ed15d5d0964d29ab844cc81f1f2476",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":292,
              "y":787},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69ff51283eda49448e4ab9b980fdae6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":292,
                  "y":787},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7885cf07c4c4b9caccb9692b7a4e03e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":595},
            "size":{
              "width":10,
              "height":182}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户签约-结算信息/u62_line.png"}},
{
          "id":"dea257ea03354191a1bb18379e8bb1de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":329},
            "size":{
              "width":37,
              "height":39},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db3f1d5ce0cc498fbb2c4444f31812cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":329},
                "size":{
                  "width":37,
                  "height":39},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-结算信息/u54.png"}},
{
          "id":"2ef05997cca04026a079941256d0c518",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":292,
              "y":335},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8d0bb4fb6324e9b881f464c5b222a9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":292,
                  "y":335},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ab2b3aa640047eaa16ce97846094430",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":371},
            "size":{
              "width":10,
              "height":182}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户签约-结算信息/u62_line.png"}},
{
          "id":"84a348733d414da9ba14b1b316268a2e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":337},
            "size":{
              "width":23,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"276ec81fcbcc44ef8c5f9a6bd55f676a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":337},
                "size":{
                  "width":23,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u132.png"}},
{
          "id":"d2921fbb59474f44a32ea0ecdf661162",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":254,
              "y":558},
            "size":{
              "width":23,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb80319a2dc94f8e8e3c6d7145acbb85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":254,
                  "y":558},
                "size":{
                  "width":23,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u132.png"}},
{
          "id":"c35ca05465dd41fba46dac820209057a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":871,
              "y":232},
            "size":{
              "width":145,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90aa6db803e94055b5803ed6fd5f08d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":871,
                  "y":232},
                "size":{
                  "width":145,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96374e49c45c4f35993b462958868ca3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":220},
            "size":{
              "width":126,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f27dbd71b976457386ef062ad499c175",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":235,
                  "y":220},
                "size":{
                  "width":126,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户管理-签约协议/u23.png"}},
{
          "id":"0ab706dce1294ba8861d02ba4160ce96",
          "label":"右侧边栏",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":1351,
              "y":300},
            "size":{
              "width":200,
              "height":205}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"82fe3494d90b4593ba88f74336649abb",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"13abf49902344611a40220bf36d47722",
                  "label":"",
                  "parentDynamicPanel":"0ab706dce1294ba8861d02ba4160ce96",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":205}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"821a67ec834a49e1870a313520b1b607",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ab706dce1294ba8861d02ba4160ce96",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":205}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/帮助/u60.png"}},
{
                  "id":"009993495e224bf495c7b408de042677",
                  "label":"",
                  "parentDynamicPanel":"0ab706dce1294ba8861d02ba4160ce96",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"700",
                    "location":{
                      "x":12,
                      "y":26},
                    "size":{
                      "width":174,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3fe9747c43424c5381b2358b5183f955",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ab706dce1294ba8861d02ba4160ce96",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"700",
                        "location":{
                          "x":12,
                          "y":26},
                        "size":{
                          "width":174,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"39edbe12f0094af8bcc355a4183c334b",
                  "label":"",
                  "parentDynamicPanel":"0ab706dce1294ba8861d02ba4160ce96",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":41,
                      "y":73},
                    "size":{
                      "width":120,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b73408560ec44201b9280d951b806d53",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ab706dce1294ba8861d02ba4160ce96",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":41,
                          "y":73},
                        "size":{
                          "width":120,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 商户管理-签约协议",
                              "target":{
                                "targetType":"page",
                                "url":"商户管理-签约协议.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/帮助/u64.png"}},
{
                  "id":"24df3dc590334ea5a063e1f9fc87cbfe",
                  "label":"",
                  "parentDynamicPanel":"0ab706dce1294ba8861d02ba4160ce96",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":75,
                      "y":128},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"496814635886413ba1eacd358272f332",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ab706dce1294ba8861d02ba4160ce96",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":75,
                          "y":128},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/帮助/u66.png"}}]}]},
{
          "id":"9a9d75f9b56442e9b79a614f56903f9c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1469,
              "y":230},
            "size":{
              "width":51,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02a23185c5804fe391f1bfe2d8f6ed7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1469,
                  "y":230},
                "size":{
                  "width":51,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle 右侧边栏",
                      "objectsToFades":[{
                          "objectPath":["0ab706dce1294ba8861d02ba4160ce96"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u57.png"}},
{
          "id":"cf59b34fcb294fb7a90d8fcd2d4d278b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":298},
            "size":{
              "width":1350,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户签约-基本信息（企业）/u192_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0fb23047301148e09583a60ccb229b40":{
      "scriptId":"u0"},
    "3bf00121b4a243b18e290d2d2486fc49":{
      "scriptId":"u1"},
    "b598508e51054d9ca344157f2304c7dd":{
      "scriptId":"u2"},
    "81d49d15cf534b7c970c27d12d0227e1":{
      "scriptId":"u3"},
    "642eada149b240c89a7f6d29083d01a8":{
      "scriptId":"u4"},
    "72867ee314b742d4aad83216b02f0f75":{
      "scriptId":"u5"},
    "89fbb191210b4574a1cef8efa5dd51c7":{
      "scriptId":"u6"},
    "c9f7ff7cc05e44a3981ef0e22c753afd":{
      "scriptId":"u7"},
    "8951a6e5dcd546799cf953092e1d8da0":{
      "scriptId":"u8"},
    "ab627149002a4ec1bbd9dab6f8070336":{
      "scriptId":"u9"},
    "19ef5993aabe463396b33e437a963557":{
      "scriptId":"u10"},
    "a573fdc988c4466ca18feb6cbb2248e6":{
      "scriptId":"u11"},
    "b8a9455413da4c99860acc2e92d9a2de":{
      "scriptId":"u12"},
    "f7422a9300364799b5337a90165b1abc":{
      "scriptId":"u13"},
    "cce16aecdf784038aa87c6e3ca476822":{
      "scriptId":"u14"},
    "ea8856242e904c48a57726574f88d624":{
      "scriptId":"u15"},
    "0783fdfc48e44b75847be23fa1f96f70":{
      "scriptId":"u16"},
    "d7c7c793da2e423987c789c1c137ece2":{
      "scriptId":"u17"},
    "939d2229676f46ccb7e4b6b6a72ade2e":{
      "scriptId":"u18"},
    "5fcdc8f96a344bc787bfee42e012d7cc":{
      "scriptId":"u19"},
    "e8af2dd0584145e99659a71d66e8d47a":{
      "scriptId":"u20"},
    "3c1b4d374ace46c498e254a5707b96fe":{
      "scriptId":"u21"},
    "8d5bdadd6627450eb6f393394c961901":{
      "scriptId":"u22"},
    "a745eec77cf046dabf2160b4aa603708":{
      "scriptId":"u23"},
    "5683a23ef4ba4d1e8d8d20d3237e7040":{
      "scriptId":"u24"},
    "c46b2e13926f4754bab03c61d6087385":{
      "scriptId":"u25"},
    "3669e1ee37c84591b757bcabb5ceff9f":{
      "scriptId":"u26"},
    "c2aa78bd855245caaf3fb222b591a9eb":{
      "scriptId":"u27"},
    "fede94889c784fc2b0077f5f81b3d6d9":{
      "scriptId":"u28"},
    "57998208ba65465da802be6ec8301819":{
      "scriptId":"u29"},
    "b95aa3c8e5fd4259a15038a06c5cd34c":{
      "scriptId":"u30"},
    "9449e51486334ba58b2c22e79e05213b":{
      "scriptId":"u31"},
    "6248099dd63b48e781a773710c4fc1a3":{
      "scriptId":"u32"},
    "58d7417586554da4ab7487cf6dce7f7c":{
      "scriptId":"u33"},
    "1cfe94bb809742398455fbfb3705f968":{
      "scriptId":"u34"},
    "ffa9ba7f13f84aeeaec402da56dbeefd":{
      "scriptId":"u35"},
    "ee377557bbcd40d7b852d9751044ef44":{
      "scriptId":"u36"},
    "1b576f756922441f98f9e1174da7497b":{
      "scriptId":"u37"},
    "8d666c81098946329401de3330d288c9":{
      "scriptId":"u38"},
    "b1aef4875f524800917a8eb7137cab23":{
      "scriptId":"u39"},
    "c7a87f62f43a4293b4a04cfb380c0258":{
      "scriptId":"u40"},
    "f867aeb47a064e9e949ab0037a052a97":{
      "scriptId":"u41"},
    "b4f4916d106347d8a149389f3f2dd5bc":{
      "scriptId":"u42"},
    "b7fbc9abaaf343d3aa42955b8fad7643":{
      "scriptId":"u43"},
    "2bdbb091eaa2455fbb3fd338b19f883f":{
      "scriptId":"u44"},
    "60b9b6cdc4a748eda73ad3b0efc67017":{
      "scriptId":"u45"},
    "641bb72932b14cbd9827d2bcc40debd2":{
      "scriptId":"u46"},
    "f402f8d6f561428682445e031215213a":{
      "scriptId":"u47"},
    "c280f767c4784fdc871582e011e12326":{
      "scriptId":"u48"},
    "d743579bd5364a98b7659dc2ecc04322":{
      "scriptId":"u49"},
    "e386c7e4c2564b93a6924576cfd34496":{
      "scriptId":"u50"},
    "df18602123ed48b9b3c23c569ef61ca0":{
      "scriptId":"u51"},
    "c5f38cfaa14349ddbab7b940cb81c444":{
      "scriptId":"u52"},
    "707d3869bb9d408cbb0e065b173c0478":{
      "scriptId":"u53"},
    "6090ca4356694189857e50b457ac9c8e":{
      "scriptId":"u54"},
    "22ebb905205a4e66beec3541b13f2695":{
      "scriptId":"u55"},
    "f9e79e529200459db8b7b81b60a78369":{
      "scriptId":"u56"},
    "0f8710ea58f14a0aaf0310193dd6ad6b":{
      "scriptId":"u57"},
    "fe05c48b64544210885192d77e72df6d":{
      "scriptId":"u58"},
    "0ff1fc9f78174f06ae1df52191d6a073":{
      "scriptId":"u59"},
    "32ed15d5d0964d29ab844cc81f1f2476":{
      "scriptId":"u60"},
    "69ff51283eda49448e4ab9b980fdae6d":{
      "scriptId":"u61"},
    "b7885cf07c4c4b9caccb9692b7a4e03e":{
      "scriptId":"u62"},
    "dea257ea03354191a1bb18379e8bb1de":{
      "scriptId":"u63"},
    "db3f1d5ce0cc498fbb2c4444f31812cc":{
      "scriptId":"u64"},
    "2ef05997cca04026a079941256d0c518":{
      "scriptId":"u65"},
    "e8d0bb4fb6324e9b881f464c5b222a9f":{
      "scriptId":"u66"},
    "6ab2b3aa640047eaa16ce97846094430":{
      "scriptId":"u67"},
    "84a348733d414da9ba14b1b316268a2e":{
      "scriptId":"u68"},
    "276ec81fcbcc44ef8c5f9a6bd55f676a":{
      "scriptId":"u69"},
    "d2921fbb59474f44a32ea0ecdf661162":{
      "scriptId":"u70"},
    "bb80319a2dc94f8e8e3c6d7145acbb85":{
      "scriptId":"u71"},
    "c35ca05465dd41fba46dac820209057a":{
      "scriptId":"u72"},
    "90aa6db803e94055b5803ed6fd5f08d1":{
      "scriptId":"u73"},
    "96374e49c45c4f35993b462958868ca3":{
      "scriptId":"u74"},
    "f27dbd71b976457386ef062ad499c175":{
      "scriptId":"u75"},
    "0ab706dce1294ba8861d02ba4160ce96":{
      "scriptId":"u76"},
    "13abf49902344611a40220bf36d47722":{
      "scriptId":"u77"},
    "821a67ec834a49e1870a313520b1b607":{
      "scriptId":"u78"},
    "009993495e224bf495c7b408de042677":{
      "scriptId":"u79"},
    "3fe9747c43424c5381b2358b5183f955":{
      "scriptId":"u80"},
    "39edbe12f0094af8bcc355a4183c334b":{
      "scriptId":"u81"},
    "b73408560ec44201b9280d951b806d53":{
      "scriptId":"u82"},
    "24df3dc590334ea5a063e1f9fc87cbfe":{
      "scriptId":"u83"},
    "496814635886413ba1eacd358272f332":{
      "scriptId":"u84"},
    "9a9d75f9b56442e9b79a614f56903f9c":{
      "scriptId":"u85"},
    "02a23185c5804fe391f1bfe2d8f6ed7e":{
      "scriptId":"u86"},
    "cf59b34fcb294fb7a90d8fcd2d4d278b":{
      "scriptId":"u87"}}});