$axure.loadCurrentPage({
  "url":"批量代付_p2.html",
  "generationDate":new Date(1461745769795.78),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0b3f531d916e427abf046e667a965bb4",
    "type":"Axure:Page",
    "name":"批量代付 p2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"740c4cb3753346a283769e7d83b292b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":75},
            "size":{
              "width":1223,
              "height":1005}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb7d1cc62a414bd38d610bff945ea708",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":75},
                "size":{
                  "width":1223,
                  "height":1005}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/未实名认证提醒/u0.jpg"}},
{
          "id":"4f1b698a5a484a888fcbf2a5031248fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.4",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":110,
              "y":75},
            "size":{
              "width":1220,
              "height":1005}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25a25bea5b3f421cbd36965be7fa2f11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.4",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":110,
                  "y":75},
                "size":{
                  "width":1220,
                  "height":1005}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/未实名认证提醒/u9.png"}},
{
          "id":"5f3b3947505d46d484937dc382517e1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":1457,
              "y":210},
            "size":{
              "width":430,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f1a67393e3e4bc382b5574ff0c86583",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":1457,
                  "y":210},
                "size":{
                  "width":430,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u88.png"}},
{
          "id":"25e5e8da566f4e378aecc3192d694a35",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":302},
            "size":{
              "width":978,
              "height":298}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e1e5fdcd694453097778b7688b1b09a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":232,
                  "y":302},
                "size":{
                  "width":978,
                  "height":298}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/批量代付_p2/u6.png"}},
{
          "id":"3db386a6d0be4471a2f032a7c180c870",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":483},
            "size":{
              "width":989,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/批量代付_p2/u8_line.png"}},
{
          "id":"1659181ca606465a9a80193773a7e502",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":649,
              "y":530},
            "size":{
              "width":120,
              "height":37},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31b3eca738724575b1b3e598dbc3f156",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":649,
                  "y":530},
                "size":{
                  "width":120,
                  "height":37},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 批量复核 p2",
                      "target":{
                        "targetType":"page",
                        "url":"批量复核_p2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户签约-提交成功提醒/u84.png"}},
{
          "id":"6efbca93e9e04f5086c784a940d8e600",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":370,
              "y":360},
            "size":{
              "width":145,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cab13fbd7e4e421fa06e831de86b8ab1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":370,
                  "y":360},
                "size":{
                  "width":145,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a80057c9ca1e460f9027b8085ff2d2eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":356},
            "size":{
              "width":240,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daff98b59b2541cfab39387eacc7d6dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":356},
                "size":{
                  "width":240,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/批量代付_p2/u13.png"}},
{
          "id":"0c9e72a2e8f54fdcb9f45f0e2da52b93",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":890,
              "y":360},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d36cec49358e41ba98a724e4b8ae42a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":890,
                  "y":360},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u124.png"}},
{
          "id":"711793bb39b04ac3a2e6feb2d2d11768",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":410},
            "size":{
              "width":199,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cca59c8e3a1472bb5d30b6138158c65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":410},
                "size":{
                  "width":199,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/批量代付_p2/u17.png"}},
{
          "id":"5b6222d9ccd94637add81ead6f1d0c2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":232,
              "y":212},
            "size":{
              "width":980,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14406166dec8498baa1ee18fe8f66174",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":232,
                  "y":212},
                "size":{
                  "width":980,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现/u6.png"}},
{
          "id":"0a3a6ea00eb343fe8e07fd7d7fb4b6ac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1142.5,
              "y":232.5},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5a34e409152494f80387c2c66460e6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1142.5,
                  "y":232.5},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页（控制台）",
                      "target":{
                        "targetType":"page",
                        "url":"首页（控制台）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u74.png"}},
{
          "id":"e53a46fdf04748aea142a3547df86888",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":242},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9003bc72e55d4161aa414455c9b3481e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":242},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 代付 p2",
                      "target":{
                        "targetType":"page",
                        "url":"代付_p2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/批量代付_p2/u23.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "740c4cb3753346a283769e7d83b292b2":{
      "scriptId":"u0"},
    "bb7d1cc62a414bd38d610bff945ea708":{
      "scriptId":"u1"},
    "4f1b698a5a484a888fcbf2a5031248fa":{
      "scriptId":"u2"},
    "25a25bea5b3f421cbd36965be7fa2f11":{
      "scriptId":"u3"},
    "5f3b3947505d46d484937dc382517e1e":{
      "scriptId":"u4"},
    "5f1a67393e3e4bc382b5574ff0c86583":{
      "scriptId":"u5"},
    "25e5e8da566f4e378aecc3192d694a35":{
      "scriptId":"u6"},
    "7e1e5fdcd694453097778b7688b1b09a":{
      "scriptId":"u7"},
    "3db386a6d0be4471a2f032a7c180c870":{
      "scriptId":"u8"},
    "1659181ca606465a9a80193773a7e502":{
      "scriptId":"u9"},
    "31b3eca738724575b1b3e598dbc3f156":{
      "scriptId":"u10"},
    "6efbca93e9e04f5086c784a940d8e600":{
      "scriptId":"u11"},
    "cab13fbd7e4e421fa06e831de86b8ab1":{
      "scriptId":"u12"},
    "a80057c9ca1e460f9027b8085ff2d2eb":{
      "scriptId":"u13"},
    "daff98b59b2541cfab39387eacc7d6dd":{
      "scriptId":"u14"},
    "0c9e72a2e8f54fdcb9f45f0e2da52b93":{
      "scriptId":"u15"},
    "d36cec49358e41ba98a724e4b8ae42a4":{
      "scriptId":"u16"},
    "711793bb39b04ac3a2e6feb2d2d11768":{
      "scriptId":"u17"},
    "6cca59c8e3a1472bb5d30b6138158c65":{
      "scriptId":"u18"},
    "5b6222d9ccd94637add81ead6f1d0c2a":{
      "scriptId":"u19"},
    "14406166dec8498baa1ee18fe8f66174":{
      "scriptId":"u20"},
    "0a3a6ea00eb343fe8e07fd7d7fb4b6ac":{
      "scriptId":"u21"},
    "a5a34e409152494f80387c2c66460e6a":{
      "scriptId":"u22"},
    "e53a46fdf04748aea142a3547df86888":{
      "scriptId":"u23"},
    "9003bc72e55d4161aa414455c9b3481e":{
      "scriptId":"u24"}}});