$axure.loadCurrentPage({
  "url":"技术协议.html",
  "generationDate":new Date(1461745756450.54),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b20364a0814c4a86a3a18178a2aba76b",
    "type":"Axure:Page",
    "name":"技术协议",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0011aaad26bf41ef90c9cc28664ea17e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":208}},
          "adaptiveStyles":{
},
          "masterId":"ce194b8bf61742aea7475dad35671852"},
{
          "id":"1feda4c5088b4baa89064249513ddc69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":434,
              "y":328},
            "size":{
              "width":946,
              "height":622}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cc7cd1043984afa93a0335beb2eebd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":434,
                  "y":328},
                "size":{
                  "width":946,
                  "height":622}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/结算信息/u28.png"}},
{
          "id":"fb8971b8576c4daaa66fe23fb9113730",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":434,
              "y":328},
            "size":{
              "width":946,
              "height":92}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24ea531f6dc843cb96b455954172ab3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":434,
                  "y":328},
                "size":{
                  "width":946,
                  "height":92}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u68.png"}},
{
          "id":"85f3f81802eb4ac0a57edbb97d508bf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":475,
              "y":364},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edbdd266af5442658c03b52ce073c115",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":475,
                  "y":364},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"291c1e7564504292805f8c327bb4db9d",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":450},
            "size":{
              "width":910,
              "height":470}},
          "adaptiveStyles":{
}},
{
          "id":"2bfc20ffa1744de6bf9e65d669c5223d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":316}},
          "adaptiveStyles":{
},
          "masterId":"9174c8aff58e4ee48fd3d1e6d813dce8"}]}},
  "masters":{
    "ce194b8bf61742aea7475dad35671852":{
      "packageId":"ce194b8bf61742aea7475dad35671852",
      "type":"Axure:Master",
      "name":"头部框架",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1a8ee24928a94860889c9b047390fbf5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "opacity":"0.3",
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "size":{
                "width":1219,
                "height":1020},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f6d5da329001418bad0c45f297bae802",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "opacity":"0.3",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "size":{
                    "width":1219,
                    "height":1020},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/帮助/u41.png"}},
{
            "id":"2b596599a1a2483d84e1634a29aaddec",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":100},
              "size":{
                "width":1219,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/帮助/u43_line.png"}},
{
            "id":"06a4f09ba941472c84ee4ff1c0e16d57",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":855,
                "y":41},
              "size":{
                "width":203,
                "height":33}},
            "adaptiveStyles":{
}},
{
            "id":"2d1981c2bb3a4bbf98d29d5eb4a95f05",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":1058,
                "y":41},
              "size":{
                "width":38,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5c489b146ee44a60b5c40b1930b87fea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":1058,
                    "y":41},
                  "size":{
                    "width":38,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 支付查询",
                        "target":{
                          "targetType":"page",
                          "url":"支付查询.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u45.png"}},
{
            "id":"014e382808854576ac2a5acf6f38b3a2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":35,
                "y":20},
              "size":{
                "width":125,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f984bdbcccaa4abf9aac379604b9f79d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":35,
                    "y":20},
                  "size":{
                    "width":125,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/帮助/u47.png"}},
{
            "id":"bececc72e4864233aa56bbeb0067e5a5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":187,
                "y":37},
              "size":{
                "width":73,
                "height":43},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"665d02781c8d4d96a2ccf54f489faf8d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":187,
                    "y":37},
                  "size":{
                    "width":73,
                    "height":43},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页（控制台）",
                        "target":{
                          "targetType":"page",
                          "url":"首页（控制台）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u49.png"}},
{
            "id":"f7852bcc4c5a4921802ef94e6d848264",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":747,
                "y":40},
              "size":{
                "width":50,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da463ba93a7b4aec8326c16acf8da252",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":747,
                    "y":40},
                  "size":{
                    "width":50,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 帮助",
                        "target":{
                          "targetType":"page",
                          "url":"帮助.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u51.png"}},
{
            "id":"75f88fef079b47a09a5869837b83bf72",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1150,
                "y":30},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e78ad31a00344180aede2de040f4a718",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1150,
                    "y":30},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle 右侧边栏",
                        "objectsToFades":[{
                            "objectPath":["4c67581e5b9c41d2bed24e008a7eaf41"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u53.png"}},
{
            "id":"4c67581e5b9c41d2bed24e008a7eaf41",
            "label":"右侧边栏",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":1019,
                "y":105},
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"735f9a5466874ed29256b29c16e25def",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"718082d5a20f450d9c84bd2103096cf6",
                    "label":"",
                    "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":200,
                        "height":205}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b1ccd05daa8b42a3bfb0dbd5953ba989",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":200,
                            "height":205}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/帮助/u56.png"}},
{
                    "id":"9654f5fb424e410187206b64ad418cc3",
                    "label":"",
                    "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Negreta', 'Arial'",
                      "fontSize":"18px",
                      "fontWeight":"700",
                      "location":{
                        "x":12,
                        "y":26},
                      "size":{
                        "width":174,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"90a4735f986b4a6182c99e43389f1406",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Negreta', 'Arial'",
                          "fontSize":"18px",
                          "fontWeight":"700",
                          "location":{
                            "x":12,
                            "y":26},
                          "size":{
                            "width":174,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"b8ee2d90d06e4e538a40ae52e9ffc07e",
                    "label":"",
                    "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontSize":"16px",
                      "location":{
                        "x":41,
                        "y":73},
                      "size":{
                        "width":120,
                        "height":30},
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2d867bb2072e457e8c918d09ae3ddac6",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"16px",
                          "location":{
                            "x":41,
                            "y":73},
                          "size":{
                            "width":120,
                            "height":30},
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 基本信息（个人呈现）",
                                "target":{
                                  "targetType":"page",
                                  "url":"基本信息（个人呈现）.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/帮助/u60.png"}},
{
                    "id":"09c4937ed6844893bf4a19ae7fcb6637",
                    "label":"",
                    "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":75,
                        "y":128},
                      "size":{
                        "width":50,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"aa7310f048d8440d82e9fb58dffe258a",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":75,
                            "y":128},
                          "size":{
                            "width":50,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/帮助/u62.png"}}]}]},
{
            "id":"aaa8451fb0384ee78285cd70dbd3ac43",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":301,
                "y":41},
              "size":{
                "width":93,
                "height":40},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b70af69fec064387a9c5b3322fb2146a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":301,
                    "y":41},
                  "size":{
                    "width":93,
                    "height":40},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u64.png"}},
{
            "id":"861b3c8487af4ee0950251a48b2c6762",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":654,
                "y":46},
              "size":{
                "width":74,
                "height":30},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b711ccb25389454aa756897a2ff7e007",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":654,
                    "y":46},
                  "size":{
                    "width":74,
                    "height":30},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/帮助/u66.png"}}]}},
    "9174c8aff58e4ee48fd3d1e6d813dce8":{
      "packageId":"9174c8aff58e4ee48fd3d1e6d813dce8",
      "type":"Axure:Master",
      "name":"商户中心侧边栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fe68a47290e54e2c8cb5ef23fafad57a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":210,
                "height":784}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"693426459f8f40a386907aedd9793d5e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":210,
                    "height":784}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/基本信息（个人呈现）/u29.png"}},
{
            "id":"883ed10cb9fb4aa0a526d05c27ed09ac",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "location":{
                "x":18,
                "y":66},
              "size":{
                "width":174,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c60d40dd1f9146afb39d7fdaaf690256",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "location":{
                    "x":18,
                    "y":66},
                  "size":{
                    "width":174,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1ab799196cc0497aae263512729ce1b5",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":154},
              "size":{
                "width":210,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/基本信息（个人呈现）/u33_line.png"}},
{
            "id":"401c30b219154d97b3037964a0d6fe17",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":5,
                "y":218},
              "size":{
                "width":200,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/基本信息（个人呈现）/u34_line.png"}},
{
            "id":"1538fb03af3c473a888106ce0cd56283",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":18,
                "y":174},
              "size":{
                "width":42,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9b4fd040a32e43c4b8667ff48dcd798a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":18,
                    "y":174},
                  "size":{
                    "width":42,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/基本信息（个人呈现）/u35.png"}},
{
            "id":"f900e71c570d4057bd8352f9c5493d58",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "location":{
                "x":72,
                "y":186},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0b9ca5319512458380400c3d8284d937",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "location":{
                    "x":72,
                    "y":186},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d392aadaf65b44d3874c66af0b69301c",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":166,
                "y":186},
              "size":{
                "width":32,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d654ce115c0442c88d0fd0c2e2359206",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":166,
                    "y":186},
                  "size":{
                    "width":32,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/基本信息（个人呈现）/u39.png"}},
{
            "id":"99403f47bfe548ab84d739e915643973",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":5,
                "y":299},
              "size":{
                "width":200,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/基本信息（个人呈现）/u34_line.png"}},
{
            "id":"2e2e3aac1deb40998b3ceb0a47d15713",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":18,
                "y":255},
              "size":{
                "width":42,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7281e302fe6644ae97811c08af6aba5c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":18,
                    "y":255},
                  "size":{
                    "width":42,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/基本信息（个人呈现）/u35.png"}},
{
            "id":"731d6a41502543c4b43c9f28ab45ee08",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "location":{
                "x":72,
                "y":267},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"87e824dd19d742508f921d062005f8f7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "location":{
                    "x":72,
                    "y":267},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5d8f67e9cc8d4628be6e67e2e38518f8",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":4,
                "y":383},
              "size":{
                "width":200,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/基本信息（个人呈现）/u34_line.png"}},
{
            "id":"9f90b205d78b4428a91fe70ae4a12955",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":17,
                "y":339},
              "size":{
                "width":42,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"70afacedbfec47f3b1fc94f59eb1c6c6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":17,
                    "y":339},
                  "size":{
                    "width":42,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/基本信息（个人呈现）/u35.png"}},
{
            "id":"887e1f3f292c46c5996971f2cbbfb475",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "location":{
                "x":71,
                "y":351},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f930f1439a81440cab4b96ada525f1b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "location":{
                    "x":71,
                    "y":351},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2cdd7f8c6e164320a27cb219c8daafd1",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":5,
                "y":259},
              "size":{
                "width":188,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 结算信息",
                        "target":{
                          "targetType":"page",
                          "url":"结算信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"c2bfbef632f243ba8c3633a696782695",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":168},
              "size":{
                "width":188,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 结算信息",
                        "target":{
                          "targetType":"page",
                          "url":"结算信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"03fbc04f0c4444a0b96ff277789d3f0b",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":11,
                "y":333},
              "size":{
                "width":188,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 密码管理",
                        "target":{
                          "targetType":"page",
                          "url":"密码管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"2f3d02644d244c6e893d31bcc9fc9265",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":11,
                "y":510},
              "size":{
                "width":188,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 技术协议",
                        "target":{
                          "targetType":"page",
                          "url":"技术协议.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"cb593addeafb4c40b841d59666afb14a",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":463},
              "size":{
                "width":200,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/基本信息（个人呈现）/u34_line.png"}},
{
            "id":"1d043bdb9b44456a8c2153eea1ac442b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":23,
                "y":419},
              "size":{
                "width":42,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"83146be885e54753be0d2a59debca390",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":23,
                    "y":419},
                  "size":{
                    "width":42,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/基本信息（个人呈现）/u35.png"}},
{
            "id":"d738557ee1b6480aad05a5b1ea667c6d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "location":{
                "x":77,
                "y":431},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aecfdaa527d34133aa94562848fd55e3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "location":{
                    "x":77,
                    "y":431},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a9f3f45977be4604be466b4865a298ae",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":11,
                "y":552},
              "size":{
                "width":200,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/基本信息（个人呈现）/u34_line.png"}},
{
            "id":"cc3842a9471e4305957366cafa94ae06",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":24,
                "y":508},
              "size":{
                "width":42,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9cdfd4e19a604f4f8876ee66aa9bbc53",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":24,
                    "y":508},
                  "size":{
                    "width":42,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/基本信息（个人呈现）/u35.png"}},
{
            "id":"7a79a28ea60e4604855cd1eeaf6eea46",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "location":{
                "x":78,
                "y":520},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"47d4397c008a4f0aad5761d955ff62a7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "location":{
                    "x":78,
                    "y":520},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"917cf09202db430ebe1c35fd29cb8b8d",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":15.5,
                "y":415.5},
              "size":{
                "width":188,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 隐私数据管理（订单数据） p2",
                        "target":{
                          "targetType":"page",
                          "url":"隐私数据管理（订单数据）_p2.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "0011aaad26bf41ef90c9cc28664ea17e":{
      "scriptId":"u0",
      "1a8ee24928a94860889c9b047390fbf5":{
        "scriptId":"u1"},
      "f6d5da329001418bad0c45f297bae802":{
        "scriptId":"u2"},
      "2b596599a1a2483d84e1634a29aaddec":{
        "scriptId":"u3"},
      "06a4f09ba941472c84ee4ff1c0e16d57":{
        "scriptId":"u4"},
      "2d1981c2bb3a4bbf98d29d5eb4a95f05":{
        "scriptId":"u5"},
      "5c489b146ee44a60b5c40b1930b87fea":{
        "scriptId":"u6"},
      "014e382808854576ac2a5acf6f38b3a2":{
        "scriptId":"u7"},
      "f984bdbcccaa4abf9aac379604b9f79d":{
        "scriptId":"u8"},
      "bececc72e4864233aa56bbeb0067e5a5":{
        "scriptId":"u9"},
      "665d02781c8d4d96a2ccf54f489faf8d":{
        "scriptId":"u10"},
      "f7852bcc4c5a4921802ef94e6d848264":{
        "scriptId":"u11"},
      "da463ba93a7b4aec8326c16acf8da252":{
        "scriptId":"u12"},
      "75f88fef079b47a09a5869837b83bf72":{
        "scriptId":"u13"},
      "e78ad31a00344180aede2de040f4a718":{
        "scriptId":"u14"},
      "4c67581e5b9c41d2bed24e008a7eaf41":{
        "scriptId":"u15"},
      "718082d5a20f450d9c84bd2103096cf6":{
        "scriptId":"u16"},
      "b1ccd05daa8b42a3bfb0dbd5953ba989":{
        "scriptId":"u17"},
      "9654f5fb424e410187206b64ad418cc3":{
        "scriptId":"u18"},
      "90a4735f986b4a6182c99e43389f1406":{
        "scriptId":"u19"},
      "b8ee2d90d06e4e538a40ae52e9ffc07e":{
        "scriptId":"u20"},
      "2d867bb2072e457e8c918d09ae3ddac6":{
        "scriptId":"u21"},
      "09c4937ed6844893bf4a19ae7fcb6637":{
        "scriptId":"u22"},
      "aa7310f048d8440d82e9fb58dffe258a":{
        "scriptId":"u23"},
      "aaa8451fb0384ee78285cd70dbd3ac43":{
        "scriptId":"u24"},
      "b70af69fec064387a9c5b3322fb2146a":{
        "scriptId":"u25"},
      "861b3c8487af4ee0950251a48b2c6762":{
        "scriptId":"u26"},
      "b711ccb25389454aa756897a2ff7e007":{
        "scriptId":"u27"}},
    "1feda4c5088b4baa89064249513ddc69":{
      "scriptId":"u28"},
    "4cc7cd1043984afa93a0335beb2eebd6":{
      "scriptId":"u29"},
    "fb8971b8576c4daaa66fe23fb9113730":{
      "scriptId":"u30"},
    "24ea531f6dc843cb96b455954172ab3f":{
      "scriptId":"u31"},
    "85f3f81802eb4ac0a57edbb97d508bf1":{
      "scriptId":"u32"},
    "edbdd266af5442658c03b52ce073c115":{
      "scriptId":"u33"},
    "291c1e7564504292805f8c327bb4db9d":{
      "scriptId":"u34"},
    "2bfc20ffa1744de6bf9e65d669c5223d":{
      "scriptId":"u35",
      "fe68a47290e54e2c8cb5ef23fafad57a":{
        "scriptId":"u36"},
      "693426459f8f40a386907aedd9793d5e":{
        "scriptId":"u37"},
      "883ed10cb9fb4aa0a526d05c27ed09ac":{
        "scriptId":"u38"},
      "c60d40dd1f9146afb39d7fdaaf690256":{
        "scriptId":"u39"},
      "1ab799196cc0497aae263512729ce1b5":{
        "scriptId":"u40"},
      "401c30b219154d97b3037964a0d6fe17":{
        "scriptId":"u41"},
      "1538fb03af3c473a888106ce0cd56283":{
        "scriptId":"u42"},
      "9b4fd040a32e43c4b8667ff48dcd798a":{
        "scriptId":"u43"},
      "f900e71c570d4057bd8352f9c5493d58":{
        "scriptId":"u44"},
      "0b9ca5319512458380400c3d8284d937":{
        "scriptId":"u45"},
      "d392aadaf65b44d3874c66af0b69301c":{
        "scriptId":"u46"},
      "d654ce115c0442c88d0fd0c2e2359206":{
        "scriptId":"u47"},
      "99403f47bfe548ab84d739e915643973":{
        "scriptId":"u48"},
      "2e2e3aac1deb40998b3ceb0a47d15713":{
        "scriptId":"u49"},
      "7281e302fe6644ae97811c08af6aba5c":{
        "scriptId":"u50"},
      "731d6a41502543c4b43c9f28ab45ee08":{
        "scriptId":"u51"},
      "87e824dd19d742508f921d062005f8f7":{
        "scriptId":"u52"},
      "5d8f67e9cc8d4628be6e67e2e38518f8":{
        "scriptId":"u53"},
      "9f90b205d78b4428a91fe70ae4a12955":{
        "scriptId":"u54"},
      "70afacedbfec47f3b1fc94f59eb1c6c6":{
        "scriptId":"u55"},
      "887e1f3f292c46c5996971f2cbbfb475":{
        "scriptId":"u56"},
      "f930f1439a81440cab4b96ada525f1b4":{
        "scriptId":"u57"},
      "2cdd7f8c6e164320a27cb219c8daafd1":{
        "scriptId":"u58"},
      "c2bfbef632f243ba8c3633a696782695":{
        "scriptId":"u59"},
      "03fbc04f0c4444a0b96ff277789d3f0b":{
        "scriptId":"u60"},
      "2f3d02644d244c6e893d31bcc9fc9265":{
        "scriptId":"u61"},
      "cb593addeafb4c40b841d59666afb14a":{
        "scriptId":"u62"},
      "1d043bdb9b44456a8c2153eea1ac442b":{
        "scriptId":"u63"},
      "83146be885e54753be0d2a59debca390":{
        "scriptId":"u64"},
      "d738557ee1b6480aad05a5b1ea667c6d":{
        "scriptId":"u65"},
      "aecfdaa527d34133aa94562848fd55e3":{
        "scriptId":"u66"},
      "a9f3f45977be4604be466b4865a298ae":{
        "scriptId":"u67"},
      "cc3842a9471e4305957366cafa94ae06":{
        "scriptId":"u68"},
      "9cdfd4e19a604f4f8876ee66aa9bbc53":{
        "scriptId":"u69"},
      "7a79a28ea60e4604855cd1eeaf6eea46":{
        "scriptId":"u70"},
      "47d4397c008a4f0aad5761d955ff62a7":{
        "scriptId":"u71"},
      "917cf09202db430ebe1c35fd29cb8b8d":{
        "scriptId":"u72"}}}});