$axure.loadCurrentPage({
  "url":"修改.html",
  "generationDate":new Date(1469168369194.91),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a8450b723a3d45c4b8dd4bf9fcc0d209",
    "type":"Axure:Page",
    "name":"修改",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c4461264786141558ad9d9a02fc2754b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":51},
            "size":{
              "width":1180,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cf56f39b82e4cb08a790b32b0cd0972",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":51},
                "size":{
                  "width":1180,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收款账号管理/u0.png"}},
{
          "id":"32d579524da54474ae54ef3b5f9070cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":72},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56dc86f497294449b481652501734deb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":98,
                  "y":72},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a71ce01fea554604a92787f2cf36f7ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":73},
            "size":{
              "width":328,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a826697ce66e4442a5033a93b186f094",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":73},
                "size":{
                  "width":328,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff324ef83fbe4ae8a777dabf7e2da776",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1150,
              "y":72},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4456e059433141c09a4aabdbce6271e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1150,
                  "y":72},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c1f1d423cb34d90886324af161d37d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":210},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30c12efefaba4c2986f7055946315d65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":210},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"006709067dd04765951deaf10692e80b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":136},
            "size":{
              "width":145,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce1b98993255444fb20050e1e711005b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":136},
                "size":{
                  "width":145,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2101bc962dd41f3bc81a58a53e01fcf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":135,
              "y":244},
            "size":{
              "width":157,
              "height":191}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebc321fa01864cf6954c1a4e09f17dfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":135,
                  "y":244},
                "size":{
                  "width":157,
                  "height":191}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d73cf9e34e640a99bdec83e0b6ac53c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":240},
            "size":{
              "width":321,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"86f72c7bb82749f8bbb7fe1f81e5cc81",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":510},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"662c8b5b30c84528b30cafaa6a61edb8",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":474},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60614bfb41eb4aa19dbe93b3d3117be2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":309,
                  "y":474},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4059c3e52f354f9085c915235ab6c39d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":373},
            "size":{
              "width":320,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"cd5dcc7d10ba495fa637d4eed0c235e9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":418},
            "size":{
              "width":110,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8b663900fb96429db88141e4a92e2db1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":484,
              "y":718},
            "size":{
              "width":353,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d051b0b11eda4110b353a6ef39047983",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":484,
                  "y":718},
                "size":{
                  "width":353,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa52ab275cd04e9a8d24e007441cc6a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":877,
              "y":446},
            "size":{
              "width":313,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ac9580cf255469ea4af07fb7a1e5b1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":877,
                  "y":446},
                "size":{
                  "width":313,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"388acddfe9a24835a7ca6ba29db57eb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":654,
              "y":378},
            "size":{
              "width":157,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b53b7b3cf38d43d6bc155a012a02218d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":654,
                  "y":378},
                "size":{
                  "width":157,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1a779a2b5b84cc2b83f150baff77868",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":291},
            "size":{
              "width":111,
              "height":39}},
          "adaptiveStyles":{
}},
{
          "id":"473839e66178448390f3e5e1c442641f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":447,
              "y":303},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75f573860c72479cad174d023e9d48cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":447,
                  "y":303},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64a0009f0e6a4787b28e143a04f49cf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":600,
              "y":302},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"321ec7c9be0846d789bdee8555125358",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":302},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce4b6ad8246e465690cc60b8cbd0ac89",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":510},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "c4461264786141558ad9d9a02fc2754b":{
      "scriptId":"u0"},
    "7cf56f39b82e4cb08a790b32b0cd0972":{
      "scriptId":"u1"},
    "32d579524da54474ae54ef3b5f9070cb":{
      "scriptId":"u2"},
    "56dc86f497294449b481652501734deb":{
      "scriptId":"u3"},
    "a71ce01fea554604a92787f2cf36f7ed":{
      "scriptId":"u4"},
    "a826697ce66e4442a5033a93b186f094":{
      "scriptId":"u5"},
    "ff324ef83fbe4ae8a777dabf7e2da776":{
      "scriptId":"u6"},
    "4456e059433141c09a4aabdbce6271e0":{
      "scriptId":"u7"},
    "6c1f1d423cb34d90886324af161d37d4":{
      "scriptId":"u8"},
    "30c12efefaba4c2986f7055946315d65":{
      "scriptId":"u9"},
    "006709067dd04765951deaf10692e80b":{
      "scriptId":"u10"},
    "ce1b98993255444fb20050e1e711005b":{
      "scriptId":"u11"},
    "a2101bc962dd41f3bc81a58a53e01fcf":{
      "scriptId":"u12"},
    "ebc321fa01864cf6954c1a4e09f17dfe":{
      "scriptId":"u13"},
    "8d73cf9e34e640a99bdec83e0b6ac53c":{
      "scriptId":"u14"},
    "86f72c7bb82749f8bbb7fe1f81e5cc81":{
      "scriptId":"u15"},
    "662c8b5b30c84528b30cafaa6a61edb8":{
      "scriptId":"u16"},
    "60614bfb41eb4aa19dbe93b3d3117be2":{
      "scriptId":"u17"},
    "4059c3e52f354f9085c915235ab6c39d":{
      "scriptId":"u18"},
    "cd5dcc7d10ba495fa637d4eed0c235e9":{
      "scriptId":"u19"},
    "8b663900fb96429db88141e4a92e2db1":{
      "scriptId":"u20"},
    "d051b0b11eda4110b353a6ef39047983":{
      "scriptId":"u21"},
    "aa52ab275cd04e9a8d24e007441cc6a2":{
      "scriptId":"u22"},
    "9ac9580cf255469ea4af07fb7a1e5b1b":{
      "scriptId":"u23"},
    "388acddfe9a24835a7ca6ba29db57eb9":{
      "scriptId":"u24"},
    "b53b7b3cf38d43d6bc155a012a02218d":{
      "scriptId":"u25"},
    "f1a779a2b5b84cc2b83f150baff77868":{
      "scriptId":"u26"},
    "473839e66178448390f3e5e1c442641f":{
      "scriptId":"u27"},
    "75f573860c72479cad174d023e9d48cc":{
      "scriptId":"u28"},
    "64a0009f0e6a4787b28e143a04f49cf8":{
      "scriptId":"u29"},
    "321ec7c9be0846d789bdee8555125358":{
      "scriptId":"u30"},
    "ce4b6ad8246e465690cc60b8cbd0ac89":{
      "scriptId":"u31"}}});