$axure.loadCurrentPage({
  "url":"版本改动记录.html",
  "generationDate":new Date(1461745743551.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f92cc83e35414008b6b42449b2119856",
    "type":"Axure:Page",
    "name":"版本改动记录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c5ceba36700e42ff99c59f3fe5177abb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":140},
            "size":{
              "width":420,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"285aa8ff2ce4432bbadbc3a48bc97258",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":140},
                "size":{
                  "width":420,
                  "height":300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/版本改动记录/u0.png"}},
{
          "id":"b0ce1823fb7c4d72a3f95aa5254f03b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":170,
              "y":140},
            "size":{
              "width":420,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17a82d9254a34410a11ba5225ac25c6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":170,
                  "y":140},
                "size":{
                  "width":420,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/版本改动记录/u2.png"}},
{
          "id":"aa270ac23fa944fe9433ea21c131a216",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":170,
              "y":180},
            "size":{
              "width":90,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7290747756be4d0eb2dcf52684de73d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":170,
                  "y":180},
                "size":{
                  "width":90,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/版本改动记录/u4.png"}},
{
          "id":"1ede5d73528c4108bec4a25050abfe7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":260,
              "y":180},
            "size":{
              "width":330,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccba0f7dc3a7417f803c11231167d10d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":260,
                  "y":180},
                "size":{
                  "width":330,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/版本改动记录/u6.png"}},
{
          "id":"c95b5e9b9e104533909b7e69fd32975a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":210},
            "size":{
              "width":10,
              "height":230}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/版本改动记录/u8_line.png"}},
{
          "id":"488111a3136f4f8fac90083cc1a31865",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":210},
            "size":{
              "width":330,
              "height":160}},
          "adaptiveStyles":{
}},
{
          "id":"06de60ce7528435cb0b9acee6daa38fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":210},
            "size":{
              "width":90,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1700fa3a44694c3c9e0922415a7b1ae9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":210},
                "size":{
                  "width":90,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/版本改动记录/u10.png"}},
{
          "id":"599931a2e4e448b4bcc9c459f870b9e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":370},
            "size":{
              "width":90,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bbe50ef3cdd4c969df9f2465020c463",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":370},
                "size":{
                  "width":90,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/版本改动记录/u12.png"}},
{
          "id":"779c9386743241a69170b0d85bf8042a",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":370},
            "size":{
              "width":330,
              "height":70}},
          "adaptiveStyles":{
}},
{
          "id":"ede267d58fb3427b9a570476bf90c9ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":440},
            "size":{
              "width":90,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6252b18bee044b2b8fdf46f77a2dd763",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":440},
                "size":{
                  "width":90,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/版本改动记录/u12.png"}},
{
          "id":"f13788d7eee94d97a90fcc73cf3fc411",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":440},
            "size":{
              "width":330,
              "height":70}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "c5ceba36700e42ff99c59f3fe5177abb":{
      "scriptId":"u0"},
    "285aa8ff2ce4432bbadbc3a48bc97258":{
      "scriptId":"u1"},
    "b0ce1823fb7c4d72a3f95aa5254f03b6":{
      "scriptId":"u2"},
    "17a82d9254a34410a11ba5225ac25c6d":{
      "scriptId":"u3"},
    "aa270ac23fa944fe9433ea21c131a216":{
      "scriptId":"u4"},
    "7290747756be4d0eb2dcf52684de73d3":{
      "scriptId":"u5"},
    "1ede5d73528c4108bec4a25050abfe7a":{
      "scriptId":"u6"},
    "ccba0f7dc3a7417f803c11231167d10d":{
      "scriptId":"u7"},
    "c95b5e9b9e104533909b7e69fd32975a":{
      "scriptId":"u8"},
    "488111a3136f4f8fac90083cc1a31865":{
      "scriptId":"u9"},
    "06de60ce7528435cb0b9acee6daa38fc":{
      "scriptId":"u10"},
    "1700fa3a44694c3c9e0922415a7b1ae9":{
      "scriptId":"u11"},
    "599931a2e4e448b4bcc9c459f870b9e8":{
      "scriptId":"u12"},
    "6bbe50ef3cdd4c969df9f2465020c463":{
      "scriptId":"u13"},
    "779c9386743241a69170b0d85bf8042a":{
      "scriptId":"u14"},
    "ede267d58fb3427b9a570476bf90c9ad":{
      "scriptId":"u15"},
    "6252b18bee044b2b8fdf46f77a2dd763":{
      "scriptId":"u16"},
    "f13788d7eee94d97a90fcc73cf3fc411":{
      "scriptId":"u17"}}});