$axure.loadCurrentPage({
  "url":"代付_p2.html",
  "generationDate":new Date(1461745769609.54),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a279c6135ff9447aabb28225e606c7c5",
    "type":"Axure:Page",
    "name":"代付 p2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2080d8ba657e48ec93f85b4c98a602d9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":75},
            "size":{
              "width":1223,
              "height":1005}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4199bd35402f477aadc32f980d623563",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":75},
                "size":{
                  "width":1223,
                  "height":1005}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/未实名认证提醒/u0.jpg"}},
{
          "id":"39e354dcce00480788bf34feef371471",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.4",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":110,
              "y":75},
            "size":{
              "width":1220,
              "height":1005}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8dbf5a3be7f4abd954325050a364822",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.4",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":110,
                  "y":75},
                "size":{
                  "width":1220,
                  "height":1005}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/未实名认证提醒/u9.png"}},
{
          "id":"48d6fdacbdcc49c9afaa26fa19ba8ccb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":231.5,
              "y":212.5},
            "size":{
              "width":980,
              "height":730}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c370ccfed7844f60921deb9f492da703",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":231.5,
                  "y":212.5},
                "size":{
                  "width":980,
                  "height":730}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代付_p2/u4.png"}},
{
          "id":"8085f90ed58d42b184d0570457cbcbc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":231.5,
              "y":212.5},
            "size":{
              "width":980,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"816d45ad34544b2682547c64fe88bf06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":231.5,
                  "y":212.5},
                "size":{
                  "width":980,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现/u6.png"}},
{
          "id":"8503d38ee8c84d00bb6d97ba04424fe1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":288,
              "y":244},
            "size":{
              "width":169,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12a2b0d592f74ad39e9b0e0872662c42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":288,
                  "y":244},
                "size":{
                  "width":169,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8538ebf1f8c04440a05e0b72b4fe6f17",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":476,
              "y":250},
            "size":{
              "width":99,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30ec1e86bb7b41e1883943db2d06d388",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":476,
                  "y":250},
                "size":{
                  "width":99,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f3b3947505d46d484937dc382517e1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":1457,
              "y":210},
            "size":{
              "width":430,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f1a67393e3e4bc382b5574ff0c86583",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":1457,
                  "y":210},
                "size":{
                  "width":430,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u88.png"}},
{
          "id":"8862309f9b0d4550b47b7bc0bd88ccf3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":584,
              "y":252},
            "size":{
              "width":181,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d3bd68a473d4306a715cd1603d77a2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":584,
                  "y":252},
                "size":{
                  "width":181,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1674b1d3e4f44091a4dbcfae4d727b8b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1142.5,
              "y":232.5},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a16be1fec6148ecbddc35e3e6e3fad1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1142.5,
                  "y":232.5},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页（控制台）",
                      "target":{
                        "targetType":"page",
                        "url":"首页（控制台）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u74.png"}},
{
          "id":"418df01df0a04f7b83f7f242e14b3af0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":367.5,
              "y":331.5},
            "size":{
              "width":616,
              "height":581}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb52af163c7f47e387daa951e6fff4b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":367.5,
                  "y":331.5},
                "size":{
                  "width":616,
                  "height":581}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代付_p2/u18.png"}},
{
          "id":"0586837164d342b2883a9a240932be30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":908.5,
              "y":352.5},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95c11c23dd174240a34290fa73517576",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":908.5,
                  "y":352.5},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u124.png"}},
{
          "id":"dab47e300b294a728cd1b86bfd859c0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":523.5,
              "y":842.5},
            "size":{
              "width":188,
              "height":60},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"820b9bd493a2447fb67d0829f33fd91c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":523.5,
                  "y":842.5},
                "size":{
                  "width":188,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代付_p2/u22.png"}},
{
          "id":"436a0bc8138448ec9b54b8869c318a29",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":551.5,
              "y":857.5},
            "size":{
              "width":186,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38ac20919c3643f5972a3624bcb5aa2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":551.5,
                  "y":857.5},
                "size":{
                  "width":186,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 单笔复核",
                      "target":{
                        "targetType":"page",
                        "url":"单笔复核.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/代付_p2/u24.png"}},
{
          "id":"dfa27cb863e3484c95a1c3fcd46073c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":451.5,
              "y":692.5},
            "size":{
              "width":250,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d710a1c621543d6b233329b8ad91b72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":451.5,
                  "y":692.5},
                "size":{
                  "width":250,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代付_p2/u26.png"}},
{
          "id":"562947d025794fa48e8c04b2322a326f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":462,
              "y":440},
            "size":{
              "width":398,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d34017f320304abab43edf5a2c9be646",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":462,
                  "y":440},
                "size":{
                  "width":398,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代付_p2/u28.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2080d8ba657e48ec93f85b4c98a602d9":{
      "scriptId":"u0"},
    "4199bd35402f477aadc32f980d623563":{
      "scriptId":"u1"},
    "39e354dcce00480788bf34feef371471":{
      "scriptId":"u2"},
    "c8dbf5a3be7f4abd954325050a364822":{
      "scriptId":"u3"},
    "48d6fdacbdcc49c9afaa26fa19ba8ccb":{
      "scriptId":"u4"},
    "c370ccfed7844f60921deb9f492da703":{
      "scriptId":"u5"},
    "8085f90ed58d42b184d0570457cbcbc3":{
      "scriptId":"u6"},
    "816d45ad34544b2682547c64fe88bf06":{
      "scriptId":"u7"},
    "8503d38ee8c84d00bb6d97ba04424fe1":{
      "scriptId":"u8"},
    "12a2b0d592f74ad39e9b0e0872662c42":{
      "scriptId":"u9"},
    "8538ebf1f8c04440a05e0b72b4fe6f17":{
      "scriptId":"u10"},
    "30ec1e86bb7b41e1883943db2d06d388":{
      "scriptId":"u11"},
    "5f3b3947505d46d484937dc382517e1e":{
      "scriptId":"u12"},
    "5f1a67393e3e4bc382b5574ff0c86583":{
      "scriptId":"u13"},
    "8862309f9b0d4550b47b7bc0bd88ccf3":{
      "scriptId":"u14"},
    "0d3bd68a473d4306a715cd1603d77a2e":{
      "scriptId":"u15"},
    "1674b1d3e4f44091a4dbcfae4d727b8b":{
      "scriptId":"u16"},
    "2a16be1fec6148ecbddc35e3e6e3fad1":{
      "scriptId":"u17"},
    "418df01df0a04f7b83f7f242e14b3af0":{
      "scriptId":"u18"},
    "bb52af163c7f47e387daa951e6fff4b3":{
      "scriptId":"u19"},
    "0586837164d342b2883a9a240932be30":{
      "scriptId":"u20"},
    "95c11c23dd174240a34290fa73517576":{
      "scriptId":"u21"},
    "dab47e300b294a728cd1b86bfd859c0b":{
      "scriptId":"u22"},
    "820b9bd493a2447fb67d0829f33fd91c":{
      "scriptId":"u23"},
    "436a0bc8138448ec9b54b8869c318a29":{
      "scriptId":"u24"},
    "38ac20919c3643f5972a3624bcb5aa2c":{
      "scriptId":"u25"},
    "dfa27cb863e3484c95a1c3fcd46073c5":{
      "scriptId":"u26"},
    "4d710a1c621543d6b233329b8ad91b72":{
      "scriptId":"u27"},
    "562947d025794fa48e8c04b2322a326f":{
      "scriptId":"u28"},
    "d34017f320304abab43edf5a2c9be646":{
      "scriptId":"u29"}}});