$axure.loadCurrentPage({
  "url":"扫描付款.html",
  "generationDate":new Date(1469168368832.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e1302b33e998430ab7035403fa38961d",
    "type":"Axure:Page",
    "name":"扫描付款",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e6c40b6ac0c2481fbea835b4de493799",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":30},
            "size":{
              "width":860,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"424f0496c0de42abb9caeb2c551a5047",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":152,
                  "y":30},
                "size":{
                  "width":860,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/扫描付款/u0.png"}},
{
          "id":"6576eecc26c545c2ab79136c2b720659",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":54},
            "size":{
              "width":823,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"698ab2d042e040b3903634dcd3c71ea2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":54},
                "size":{
                  "width":823,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a70cbd442e640c9a897d07a5068229a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":465,
              "y":437},
            "size":{
              "width":80,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ce5d9a4538b45ef903d3e76fd0d92de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":465,
                  "y":437},
                "size":{
                  "width":80,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f02ac1bcf35b4166a7a5056806df23df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":437,
              "y":110},
            "size":{
              "width":273,
              "height":317}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"846f40e6dfd64dce926e1d9976ebea9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":437,
                  "y":110},
                "size":{
                  "width":273,
                  "height":317}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/扫描付款/u6.png"}},
{
          "id":"13adbf8918b24818b45a2abb3302327a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":555,
              "y":427},
            "size":{
              "width":135,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"201712d44c634c16b89f7a253bef79ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":555,
                  "y":427},
                "size":{
                  "width":135,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74e1c71213154ef189d2d3f49258f72b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":653},
            "size":{
              "width":922,
              "height":467}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4cdc546e49c43beb146c7df3a5072d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":135,
                  "y":653},
                "size":{
                  "width":922,
                  "height":467}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/扫描付款/u10.png"}},
{
          "id":"97816e1913a94ce182127da661395730",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":519,
              "y":598},
            "size":{
              "width":121,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88f492f0e9b04d5cae7412c3c899c1de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":519,
                  "y":598},
                "size":{
                  "width":121,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71a5efe82be84c7e830ce7d550c31309",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":856,
              "y":917},
            "size":{
              "width":94,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7c2d4b59b8f47fc9d39223ce773af71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":856,
                  "y":917},
                "size":{
                  "width":94,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/扫描付款/u14.png"}},
{
          "id":"7e4d9ed7a6584185b548c9b31068fef7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":859,
              "y":887},
            "size":{
              "width":84,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"653d3e6620a242849031e402b8cdda5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":859,
                  "y":887},
                "size":{
                  "width":84,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/扫描付款/u16.png"}},
{
          "id":"0b9d2b5574da49c2a8f06b6e88f4ddae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":867,
              "y":886},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8c9fb0c30aa4970a33b554ea00f5a00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":867,
                  "y":886},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3549608286bb47b7af55072cd8d0a197",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":461,
              "y":476},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdb5322c02e8445f8fa241acad806c03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":461,
                  "y":476},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7c0b1e33eef466c88c3972bbdb43e23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":968,
              "y":339},
            "size":{
              "width":561,
              "height":171}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f48c30f859ae4297bbabf8c59d089458",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":968,
                  "y":339},
                "size":{
                  "width":561,
                  "height":171}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d70ef8e93367456e9b8e08f12920ff27",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":416,
              "y":515},
            "size":{
              "width":327,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c60ea30d47814ba8aa1909113504d98f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":416,
                  "y":515},
                "size":{
                  "width":327,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6762fe208d37495080f32b907fbbe270",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":856,
              "y":882},
            "size":{
              "width":60,
              "height":25},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"198659dff6854c848d7fd3e49e138a72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":856,
                  "y":882},
                "size":{
                  "width":60,
                  "height":25},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/扫描付款/u26.png"}},
{
          "id":"579e48fdb1ac41b58ecbddb3d8131f47",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":865,
              "y":887},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"132dd9ac378b466380631aaf92ded760",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":865,
                  "y":887},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64f8f7c124214ad38a091fde3ef3c6e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":851,
              "y":911},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d18a471d37c440faf6bef7fbf7b5353",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":851,
                  "y":911},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d914077f739d45288cdeb11d28597047",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":653},
            "size":{
              "width":979,
              "height":485}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f79d9285af64e3e8f34296fc404d6c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":135,
                  "y":653},
                "size":{
                  "width":979,
                  "height":485}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/扫描付款/u32.png"}},
{
          "id":"f175a6946b814ba79b4fb8df55b4a752",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":968,
              "y":840},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28573fc5ccb54ef4b3fac07759c3a56b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":968,
                  "y":840},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5626d2d4ab4f4611b26c8203bcfbe8cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":974,
              "y":965},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d5eb35cb814455197560125feaa900d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":974,
                  "y":965},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c086545099204ef3b8d85db79ced90ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":416,
              "y":543},
            "size":{
              "width":215,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ef30d378ab14e9580f22e3b44819a8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":416,
                  "y":543},
                "size":{
                  "width":215,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e6c40b6ac0c2481fbea835b4de493799":{
      "scriptId":"u0"},
    "424f0496c0de42abb9caeb2c551a5047":{
      "scriptId":"u1"},
    "6576eecc26c545c2ab79136c2b720659":{
      "scriptId":"u2"},
    "698ab2d042e040b3903634dcd3c71ea2":{
      "scriptId":"u3"},
    "8a70cbd442e640c9a897d07a5068229a":{
      "scriptId":"u4"},
    "6ce5d9a4538b45ef903d3e76fd0d92de":{
      "scriptId":"u5"},
    "f02ac1bcf35b4166a7a5056806df23df":{
      "scriptId":"u6"},
    "846f40e6dfd64dce926e1d9976ebea9a":{
      "scriptId":"u7"},
    "13adbf8918b24818b45a2abb3302327a":{
      "scriptId":"u8"},
    "201712d44c634c16b89f7a253bef79ec":{
      "scriptId":"u9"},
    "74e1c71213154ef189d2d3f49258f72b":{
      "scriptId":"u10"},
    "e4cdc546e49c43beb146c7df3a5072d8":{
      "scriptId":"u11"},
    "97816e1913a94ce182127da661395730":{
      "scriptId":"u12"},
    "88f492f0e9b04d5cae7412c3c899c1de":{
      "scriptId":"u13"},
    "71a5efe82be84c7e830ce7d550c31309":{
      "scriptId":"u14"},
    "d7c2d4b59b8f47fc9d39223ce773af71":{
      "scriptId":"u15"},
    "7e4d9ed7a6584185b548c9b31068fef7":{
      "scriptId":"u16"},
    "653d3e6620a242849031e402b8cdda5d":{
      "scriptId":"u17"},
    "0b9d2b5574da49c2a8f06b6e88f4ddae":{
      "scriptId":"u18"},
    "b8c9fb0c30aa4970a33b554ea00f5a00":{
      "scriptId":"u19"},
    "3549608286bb47b7af55072cd8d0a197":{
      "scriptId":"u20"},
    "bdb5322c02e8445f8fa241acad806c03":{
      "scriptId":"u21"},
    "a7c0b1e33eef466c88c3972bbdb43e23":{
      "scriptId":"u22"},
    "f48c30f859ae4297bbabf8c59d089458":{
      "scriptId":"u23"},
    "d70ef8e93367456e9b8e08f12920ff27":{
      "scriptId":"u24"},
    "c60ea30d47814ba8aa1909113504d98f":{
      "scriptId":"u25"},
    "6762fe208d37495080f32b907fbbe270":{
      "scriptId":"u26"},
    "198659dff6854c848d7fd3e49e138a72":{
      "scriptId":"u27"},
    "579e48fdb1ac41b58ecbddb3d8131f47":{
      "scriptId":"u28"},
    "132dd9ac378b466380631aaf92ded760":{
      "scriptId":"u29"},
    "64f8f7c124214ad38a091fde3ef3c6e6":{
      "scriptId":"u30"},
    "4d18a471d37c440faf6bef7fbf7b5353":{
      "scriptId":"u31"},
    "d914077f739d45288cdeb11d28597047":{
      "scriptId":"u32"},
    "6f79d9285af64e3e8f34296fc404d6c1":{
      "scriptId":"u33"},
    "f175a6946b814ba79b4fb8df55b4a752":{
      "scriptId":"u34"},
    "28573fc5ccb54ef4b3fac07759c3a56b":{
      "scriptId":"u35"},
    "5626d2d4ab4f4611b26c8203bcfbe8cc":{
      "scriptId":"u36"},
    "7d5eb35cb814455197560125feaa900d":{
      "scriptId":"u37"},
    "c086545099204ef3b8d85db79ced90ac":{
      "scriptId":"u38"},
    "8ef30d378ab14e9580f22e3b44819a8a":{
      "scriptId":"u39"}}});