$axure.loadCurrentPage({
  "url":"收银台-pc.html",
  "generationDate":new Date(1469168368749.59),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"198884bd952e48ac980cbde90157c009",
    "type":"Axure:Page",
    "name":"收银台-PC",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"07bf05cfa01644419b7cec074bfb4139",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":470},
            "size":{
              "width":1119,
              "height":440}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"183dede7ba524fa9aafa36acb400834e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":470},
                "size":{
                  "width":1119,
                  "height":440}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收银台-pc/u0.png"}},
{
          "id":"e51eb3233af246b9ae772ab2072b6418",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":10},
            "size":{
              "width":169,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2f2ce077b6f423aafca537d8b9c7044",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":10},
                "size":{
                  "width":169,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f4663f263914249b40c667765a8ee2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":513},
            "size":{
              "width":193,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78a72e26d0394a5380a8288b6be34974",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":84,
                  "y":513},
                "size":{
                  "width":193,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"898b673fa8674635a0d32d937cb584dd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":62},
            "size":{
              "width":1205,
              "height":368}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"424c79ffdabf4d0882294d612be4bde0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":35,
                  "y":62},
                "size":{
                  "width":1205,
                  "height":368}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收银台-pc/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "07bf05cfa01644419b7cec074bfb4139":{
      "scriptId":"u0"},
    "183dede7ba524fa9aafa36acb400834e":{
      "scriptId":"u1"},
    "e51eb3233af246b9ae772ab2072b6418":{
      "scriptId":"u2"},
    "d2f2ce077b6f423aafca537d8b9c7044":{
      "scriptId":"u3"},
    "4f4663f263914249b40c667765a8ee2b":{
      "scriptId":"u4"},
    "78a72e26d0394a5380a8288b6be34974":{
      "scriptId":"u5"},
    "898b673fa8674635a0d32d937cb584dd":{
      "scriptId":"u6"},
    "424c79ffdabf4d0882294d612be4bde0":{
      "scriptId":"u7"}}});