$axure.loadCurrentPage({
  "url":"账号管理.html",
  "generationDate":new Date(1469168369585.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3dc330fac6eb4f7fa7ab71ffecaeab23",
    "type":"Axure:Page",
    "name":"账号管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"52c678aac1204324a566f2110c03fae0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":51},
            "size":{
              "width":1180,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99959126ad304c7db949c67f91fd235f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":51},
                "size":{
                  "width":1180,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收款账号管理/u0.png"}},
{
          "id":"986967cac73f43b7be1fc40e84520818",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":72},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cae9341afc94d0cb0cd91a7ebc796b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":98,
                  "y":72},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c28f24b5c25f4dc3b3a933f4dde657ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":73},
            "size":{
              "width":328,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4531e4c180214be793292718185d1266",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":73},
                "size":{
                  "width":328,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"660a9d66ca6c4f9fb3e1e215ced5d0b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1150,
              "y":72},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32970e6390fd4766904b0995155ba41f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1150,
                  "y":72},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7adb6089097047faa1ef2fee4f715c39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":137,
              "y":230},
            "size":{
              "width":92,
              "height":400}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77f72c54d4e343429357d9dafbb449ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":137,
                  "y":230},
                "size":{
                  "width":92,
                  "height":400}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a705c991f554081bd4429ebaabdc035",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":239,
              "y":230},
            "size":{
              "width":208,
              "height":272}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86695682c1c4498797acc469ea10459f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":239,
                  "y":230},
                "size":{
                  "width":208,
                  "height":272}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"919b2348cde144a8ac92d742f4ccdfc9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":136},
            "size":{
              "width":80,
              "height":31}},
          "adaptiveStyles":{
}},
{
          "id":"d48ebba2e1f1472587a50e0a529fdc57",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":328,
              "y":135},
            "size":{
              "width":100,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"c73816d73dff431f9a45e09d717ee4a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":136},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7404c5ea88e54093a02d7f4bbe92548a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":136},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f9ac34ca5b646d98a6116343ceabac0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":178},
            "size":{
              "width":1164,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/账号管理/u16_line.png"}},
{
          "id":"e66ac4a11a704187a4b1f01f4cc4d6a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":238,
              "y":642},
            "size":{
              "width":512,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19dbec7ba2b648199ef6507c7cdeb602",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":238,
                  "y":642},
                "size":{
                  "width":512,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0957f6f44a248fab657fa0c4fe41acd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":239,
              "y":615},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"676b9c6109c942f09efa5962a9c88b23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":239,
                  "y":615},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e65368159634437d929d1e800241d596",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":591,
              "y":610},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"43b15cbd0eca496bb1f2aa0ff989c7e0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":611},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f1d6cc15878444a791941cb72e7e2cb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":303,
              "y":615},
            "size":{
              "width":344,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76e0649ede604a1b8aa55127d5ed7914",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":303,
                  "y":615},
                "size":{
                  "width":344,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7954f6d7c7304734bccb2780daa15cf6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":521,
              "y":617},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38fa00bd623e4790ada3231bef7ab845",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":521,
                  "y":617},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05711650db81408ea4cb89e8e1455fd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":750,
              "y":230},
            "size":{
              "width":615,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19a06d67467244e081aa9c58393911cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":750,
                  "y":230},
                "size":{
                  "width":615,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dad1c4c9a61a4c90bedf3e9ffc325b80",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":239,
              "y":508},
            "size":{
              "width":248,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93005bf8c0da42828138290ab39305d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":239,
                  "y":508},
                "size":{
                  "width":248,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc025d3150b44adb9b3ff3f0b0e8378c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":239,
              "y":550},
            "size":{
              "width":31,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81d7135013c9419ab51c7f78c92caa7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":239,
                  "y":550},
                "size":{
                  "width":31,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f905e8150b6743abb8828f534e5a4397",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":239,
              "y":572},
            "size":{
              "width":408,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a9305b29527431c89e4c219e1f4b9b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":239,
                  "y":572},
                "size":{
                  "width":408,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15f48565d6cf4a7095ab15e6cc000433",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":303,
              "y":550},
            "size":{
              "width":344,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9bf9ac89a734c8cbbd1d20d0da9e4a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":303,
                  "y":550},
                "size":{
                  "width":344,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6db597b5f53544f5b1efcc933cfa54f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":521,
              "y":552},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"deb3ef16d9eb4e10b2c02c73820368c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":521,
                  "y":552},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"351b986b42a6467598899c09cb9d2bf1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":581,
              "y":545},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4c588ac23b2749cbbc80976bb532035d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":546},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "52c678aac1204324a566f2110c03fae0":{
      "scriptId":"u0"},
    "99959126ad304c7db949c67f91fd235f":{
      "scriptId":"u1"},
    "986967cac73f43b7be1fc40e84520818":{
      "scriptId":"u2"},
    "8cae9341afc94d0cb0cd91a7ebc796b0":{
      "scriptId":"u3"},
    "c28f24b5c25f4dc3b3a933f4dde657ef":{
      "scriptId":"u4"},
    "4531e4c180214be793292718185d1266":{
      "scriptId":"u5"},
    "660a9d66ca6c4f9fb3e1e215ced5d0b9":{
      "scriptId":"u6"},
    "32970e6390fd4766904b0995155ba41f":{
      "scriptId":"u7"},
    "7adb6089097047faa1ef2fee4f715c39":{
      "scriptId":"u8"},
    "77f72c54d4e343429357d9dafbb449ab":{
      "scriptId":"u9"},
    "9a705c991f554081bd4429ebaabdc035":{
      "scriptId":"u10"},
    "86695682c1c4498797acc469ea10459f":{
      "scriptId":"u11"},
    "919b2348cde144a8ac92d742f4ccdfc9":{
      "scriptId":"u12"},
    "d48ebba2e1f1472587a50e0a529fdc57":{
      "scriptId":"u13"},
    "c73816d73dff431f9a45e09d717ee4a1":{
      "scriptId":"u14"},
    "7404c5ea88e54093a02d7f4bbe92548a":{
      "scriptId":"u15"},
    "1f9ac34ca5b646d98a6116343ceabac0":{
      "scriptId":"u16"},
    "e66ac4a11a704187a4b1f01f4cc4d6a1":{
      "scriptId":"u17"},
    "19dbec7ba2b648199ef6507c7cdeb602":{
      "scriptId":"u18"},
    "c0957f6f44a248fab657fa0c4fe41acd":{
      "scriptId":"u19"},
    "676b9c6109c942f09efa5962a9c88b23":{
      "scriptId":"u20"},
    "e65368159634437d929d1e800241d596":{
      "scriptId":"u21"},
    "43b15cbd0eca496bb1f2aa0ff989c7e0":{
      "scriptId":"u22"},
    "f1d6cc15878444a791941cb72e7e2cb1":{
      "scriptId":"u23"},
    "76e0649ede604a1b8aa55127d5ed7914":{
      "scriptId":"u24"},
    "7954f6d7c7304734bccb2780daa15cf6":{
      "scriptId":"u25"},
    "38fa00bd623e4790ada3231bef7ab845":{
      "scriptId":"u26"},
    "05711650db81408ea4cb89e8e1455fd2":{
      "scriptId":"u27"},
    "19a06d67467244e081aa9c58393911cc":{
      "scriptId":"u28"},
    "dad1c4c9a61a4c90bedf3e9ffc325b80":{
      "scriptId":"u29"},
    "93005bf8c0da42828138290ab39305d3":{
      "scriptId":"u30"},
    "bc025d3150b44adb9b3ff3f0b0e8378c":{
      "scriptId":"u31"},
    "81d7135013c9419ab51c7f78c92caa7e":{
      "scriptId":"u32"},
    "f905e8150b6743abb8828f534e5a4397":{
      "scriptId":"u33"},
    "0a9305b29527431c89e4c219e1f4b9b5":{
      "scriptId":"u34"},
    "15f48565d6cf4a7095ab15e6cc000433":{
      "scriptId":"u35"},
    "d9bf9ac89a734c8cbbd1d20d0da9e4a3":{
      "scriptId":"u36"},
    "6db597b5f53544f5b1efcc933cfa54f0":{
      "scriptId":"u37"},
    "deb3ef16d9eb4e10b2c02c73820368c3":{
      "scriptId":"u38"},
    "351b986b42a6467598899c09cb9d2bf1":{
      "scriptId":"u39"},
    "4c588ac23b2749cbbc80976bb532035d":{
      "scriptId":"u40"}}});