$axure.loadCurrentPage({
  "url":"协议隐藏.html",
  "generationDate":new Date(1462525707728.32),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bc9f715fddfd470d82df136c197ae2b9",
    "type":"Axure:Page",
    "name":"协议隐藏",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fb00a95697164fc7a1ba3bd73c8b15ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":701},
            "size":{
              "width":1084,
              "height":585}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b1e35c3d6324db9af7991b790f80389",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":701},
                "size":{
                  "width":1084,
                  "height":585}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/协议隐藏/u0.png"}},
{
          "id":"ae606ef7f70f45019e56a52d0adfa548",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":38},
            "size":{
              "width":294,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4a0b84a30b24841a2d697a04a9a65a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":38},
                "size":{
                  "width":294,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0aa5c98a144b463ba6ad7b1dfa694e27",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":130},
            "size":{
              "width":869,
              "height":561}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c89bcc8f90844082b633617efbba14bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":130},
                "size":{
                  "width":869,
                  "height":561}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/协议隐藏/u4.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "fb00a95697164fc7a1ba3bd73c8b15ef":{
      "scriptId":"u0"},
    "5b1e35c3d6324db9af7991b790f80389":{
      "scriptId":"u1"},
    "ae606ef7f70f45019e56a52d0adfa548":{
      "scriptId":"u2"},
    "e4a0b84a30b24841a2d697a04a9a65a4":{
      "scriptId":"u3"},
    "0aa5c98a144b463ba6ad7b1dfa694e27":{
      "scriptId":"u4"},
    "c89bcc8f90844082b633617efbba14bb":{
      "scriptId":"u5"}}});