$axure.loadCurrentPage({
  "url":"重置密码.html",
  "generationDate":new Date(1458553419610.59),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"98081f68f3104459bde82968558ed0b3",
    "type":"Axure:Page",
    "name":"重置密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c06cb979ba8344a0b19400a034898d2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":210,
              "y":210},
            "size":{
              "width":1219,
              "height":610},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"885f1c1e46ac419f9876fad1516bf294",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.3",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":210,
                  "y":210},
                "size":{
                  "width":1219,
                  "height":610},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/重置密码/u0.png"}},
{
          "id":"b227eae1e04b4483999e95eb9ea9c9fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":740,
              "y":253},
            "size":{
              "width":145,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d2bb5618dfd424692f417e70fc90cde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":740,
                  "y":253},
                "size":{
                  "width":145,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93477da385564cbebeac005652a4effe",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":310},
            "size":{
              "width":1150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/渠道添加/u4_line.png"}},
{
          "id":"8938b492e5fb4e58b8ec743398516595",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":245},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74b3fbe8d3314be38c1ccc71012a9fa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":245},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 渠道管理",
                      "target":{
                        "targetType":"page",
                        "url":"渠道管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/渠道添加/u5.png"}},
{
          "id":"afac0beb672a46f39c326152f4eabb58",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":370},
            "size":{
              "width":833,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45347959fad142aa8799ca4405b022e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":370},
                "size":{
                  "width":833,
                  "height":300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/重置密码/u7.png"}},
{
          "id":"53ce8128763f4f928e112ab88a8d511d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":660,
              "y":720},
            "size":{
              "width":250,
              "height":40},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d04ba4cc56c44f56b5dfeb3cdfab6759",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":660,
                  "y":720},
                "size":{
                  "width":250,
                  "height":40},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 渠道管理",
                      "target":{
                        "targetType":"page",
                        "url":"渠道管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/渠道添加/u9.png"}},
{
          "id":"7a274f9e0e7c44428789276c9edcb615",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":599,
              "y":434},
            "size":{
              "width":85,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd7977f8bda44f6ebc4ab6920bfab76b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":599,
                  "y":434},
                "size":{
                  "width":85,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb9a4180cf4d475d93ffb88bb9c0470e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":728,
              "y":434},
            "size":{
              "width":312,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"4dfd0d9420c04c8fb0688d31e27eb7c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":567,
              "y":524},
            "size":{
              "width":141,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78cfd05df04340fd98847afc94a5608a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":567,
                  "y":524},
                "size":{
                  "width":141,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0921f4df1947486eae749ef7197901ec",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":728,
              "y":524},
            "size":{
              "width":312,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"227914ba8b2143d79446ab57ea876b87",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":1450,
              "y":210},
            "size":{
              "width":430,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64622c9c0d0e4579b9085906deee7f9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":1450,
                  "y":210},
                "size":{
                  "width":430,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u88.png"}},
{
          "id":"d3a982d6fa004a2898e1de9e4ada508f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1088,
              "y":445},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"254773203dc043c09342f58cbf65e1ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1088,
                  "y":445},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e47ee04c7164f7188fae473c0487890",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1070,
              "y":445},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"349acbe823534d5794abfdd3abee7b31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1070,
                  "y":445},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u81.png"}},
{
          "id":"2429be8978454f02aead60b6d01a2c67",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1088,
              "y":523},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61c79b1ca90e4d1188fc3a116db56854",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1088,
                  "y":523},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c90336b0e03447afb1b04630fb14d773",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1070,
              "y":523},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"722c62fd716f4b7491a25d25e62f24df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1070,
                  "y":523},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u81.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c06cb979ba8344a0b19400a034898d2e":{
      "scriptId":"u0"},
    "885f1c1e46ac419f9876fad1516bf294":{
      "scriptId":"u1"},
    "b227eae1e04b4483999e95eb9ea9c9fa":{
      "scriptId":"u2"},
    "2d2bb5618dfd424692f417e70fc90cde":{
      "scriptId":"u3"},
    "93477da385564cbebeac005652a4effe":{
      "scriptId":"u4"},
    "8938b492e5fb4e58b8ec743398516595":{
      "scriptId":"u5"},
    "74b3fbe8d3314be38c1ccc71012a9fa6":{
      "scriptId":"u6"},
    "afac0beb672a46f39c326152f4eabb58":{
      "scriptId":"u7"},
    "45347959fad142aa8799ca4405b022e8":{
      "scriptId":"u8"},
    "53ce8128763f4f928e112ab88a8d511d":{
      "scriptId":"u9"},
    "d04ba4cc56c44f56b5dfeb3cdfab6759":{
      "scriptId":"u10"},
    "7a274f9e0e7c44428789276c9edcb615":{
      "scriptId":"u11"},
    "dd7977f8bda44f6ebc4ab6920bfab76b":{
      "scriptId":"u12"},
    "fb9a4180cf4d475d93ffb88bb9c0470e":{
      "scriptId":"u13"},
    "4dfd0d9420c04c8fb0688d31e27eb7c7":{
      "scriptId":"u14"},
    "78cfd05df04340fd98847afc94a5608a":{
      "scriptId":"u15"},
    "0921f4df1947486eae749ef7197901ec":{
      "scriptId":"u16"},
    "227914ba8b2143d79446ab57ea876b87":{
      "scriptId":"u17"},
    "64622c9c0d0e4579b9085906deee7f9c":{
      "scriptId":"u18"},
    "d3a982d6fa004a2898e1de9e4ada508f":{
      "scriptId":"u19"},
    "254773203dc043c09342f58cbf65e1ee":{
      "scriptId":"u20"},
    "2e47ee04c7164f7188fae473c0487890":{
      "scriptId":"u21"},
    "349acbe823534d5794abfdd3abee7b31":{
      "scriptId":"u22"},
    "2429be8978454f02aead60b6d01a2c67":{
      "scriptId":"u23"},
    "61c79b1ca90e4d1188fc3a116db56854":{
      "scriptId":"u24"},
    "c90336b0e03447afb1b04630fb14d773":{
      "scriptId":"u25"},
    "722c62fd716f4b7491a25d25e62f24df":{
      "scriptId":"u26"}}});