$axure.loadCurrentPage({
  "url":"添加账号.html",
  "generationDate":new Date(1469168369167.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8e642788a2fa49d09b44fb5fcfa07a47",
    "type":"Axure:Page",
    "name":"添加账号",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ad09aa57798b49838cfba17af844211f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":51},
            "size":{
              "width":1180,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19117af7f35c4e2b9e9225be15f9f10b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":51},
                "size":{
                  "width":1180,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收款账号管理/u0.png"}},
{
          "id":"9cd30d35ed32407198ca89017fee94cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":72},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0632d9096ab84a449832d0ac259818da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":98,
                  "y":72},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4347e141ac64899b5cdd9c866901f25",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":73},
            "size":{
              "width":328,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3efaa647f4af4eaa863ab573ae1a0729",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":73},
                "size":{
                  "width":328,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1285452c282543b2bf7a0cb39afc47cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1150,
              "y":72},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"347bf37f57cc468bbb45dd45b0a217f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1150,
                  "y":72},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99da8d9e124248f6aabc64ef9bbb49ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":210},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09df733a8eb941c780ca0d8e641c0dde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":210},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43b7e9c9f2ae4cefbaa09e2e9dba7c69",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":136},
            "size":{
              "width":145,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e2af3fb45f94c068dbb7b8b1aead9f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":136},
                "size":{
                  "width":145,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfa9357f00c84a2bac13f514ebb8b550",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":135,
              "y":244},
            "size":{
              "width":157,
              "height":191}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56a9d31ef5cf4ad0ad0dae1ef0764bf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":135,
                  "y":244},
                "size":{
                  "width":157,
                  "height":191}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30324ca320ff4bccbf3f1bc6a4954830",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":240},
            "size":{
              "width":321,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"fbb5a882dcd946c08a6af8a3b514e83c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":510},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7cb63944b025451f99c3ebc5c48f5570",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":474},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"384cfbb1465f43dc91fdb5d017d2226e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":309,
                  "y":474},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"40679013df194479baa0a5fe013edff7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":373},
            "size":{
              "width":320,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"89365ea927f047d19c751401cca37b19",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":418},
            "size":{
              "width":110,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"15253ea819444cb7b5ef58270fb18112",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":484,
              "y":718},
            "size":{
              "width":353,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"413ae75eadb74bdbb2963207dc854268",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":484,
                  "y":718},
                "size":{
                  "width":353,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88bd470bf0e14ecdad302f8cb3f9b533",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":877,
              "y":446},
            "size":{
              "width":313,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4d1a29c740542ba94838e8958e6dc3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":877,
                  "y":446},
                "size":{
                  "width":313,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab00cb8301c64789807cf5217e958ee7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":295},
            "size":{
              "width":111,
              "height":39}},
          "adaptiveStyles":{
}},
{
          "id":"fac66c7e253e4000bc800c9c91ba2c1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":470,
              "y":306},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c5d92ab3b6541068e7aeeab01ea0b3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":306},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cabd2f63e4744c46b347b4324de257fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":654,
              "y":378},
            "size":{
              "width":157,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3d5002b46cd41a9b32b4f7e301e7bc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":654,
                  "y":378},
                "size":{
                  "width":157,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06e52ad2afcb47c5a211a021e57e1bb1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":287},
            "size":{
              "width":111,
              "height":39}},
          "adaptiveStyles":{
}},
{
          "id":"438a065676084e6284b106a2bb467d4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1007,
              "y":299},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69500b30e030405e9f8401e3e5682264",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1007,
                  "y":299},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e099e9bf49a34f8bb91e021ab5e70e46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1160,
              "y":298},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc741b276b7c41bb9bbccee5577d0577",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1160,
                  "y":298},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7d4fa1157624b52bf00fe4e87fdd77b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":510},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "ad09aa57798b49838cfba17af844211f":{
      "scriptId":"u0"},
    "19117af7f35c4e2b9e9225be15f9f10b":{
      "scriptId":"u1"},
    "9cd30d35ed32407198ca89017fee94cf":{
      "scriptId":"u2"},
    "0632d9096ab84a449832d0ac259818da":{
      "scriptId":"u3"},
    "c4347e141ac64899b5cdd9c866901f25":{
      "scriptId":"u4"},
    "3efaa647f4af4eaa863ab573ae1a0729":{
      "scriptId":"u5"},
    "1285452c282543b2bf7a0cb39afc47cb":{
      "scriptId":"u6"},
    "347bf37f57cc468bbb45dd45b0a217f2":{
      "scriptId":"u7"},
    "99da8d9e124248f6aabc64ef9bbb49ea":{
      "scriptId":"u8"},
    "09df733a8eb941c780ca0d8e641c0dde":{
      "scriptId":"u9"},
    "43b7e9c9f2ae4cefbaa09e2e9dba7c69":{
      "scriptId":"u10"},
    "6e2af3fb45f94c068dbb7b8b1aead9f1":{
      "scriptId":"u11"},
    "bfa9357f00c84a2bac13f514ebb8b550":{
      "scriptId":"u12"},
    "56a9d31ef5cf4ad0ad0dae1ef0764bf9":{
      "scriptId":"u13"},
    "30324ca320ff4bccbf3f1bc6a4954830":{
      "scriptId":"u14"},
    "fbb5a882dcd946c08a6af8a3b514e83c":{
      "scriptId":"u15"},
    "7cb63944b025451f99c3ebc5c48f5570":{
      "scriptId":"u16"},
    "384cfbb1465f43dc91fdb5d017d2226e":{
      "scriptId":"u17"},
    "40679013df194479baa0a5fe013edff7":{
      "scriptId":"u18"},
    "89365ea927f047d19c751401cca37b19":{
      "scriptId":"u19"},
    "15253ea819444cb7b5ef58270fb18112":{
      "scriptId":"u20"},
    "413ae75eadb74bdbb2963207dc854268":{
      "scriptId":"u21"},
    "88bd470bf0e14ecdad302f8cb3f9b533":{
      "scriptId":"u22"},
    "c4d1a29c740542ba94838e8958e6dc3a":{
      "scriptId":"u23"},
    "ab00cb8301c64789807cf5217e958ee7":{
      "scriptId":"u24"},
    "fac66c7e253e4000bc800c9c91ba2c1b":{
      "scriptId":"u25"},
    "4c5d92ab3b6541068e7aeeab01ea0b3d":{
      "scriptId":"u26"},
    "cabd2f63e4744c46b347b4324de257fe":{
      "scriptId":"u27"},
    "f3d5002b46cd41a9b32b4f7e301e7bc1":{
      "scriptId":"u28"},
    "06e52ad2afcb47c5a211a021e57e1bb1":{
      "scriptId":"u29"},
    "438a065676084e6284b106a2bb467d4e":{
      "scriptId":"u30"},
    "69500b30e030405e9f8401e3e5682264":{
      "scriptId":"u31"},
    "e099e9bf49a34f8bb91e021ab5e70e46":{
      "scriptId":"u32"},
    "bc741b276b7c41bb9bbccee5577d0577":{
      "scriptId":"u33"},
    "f7d4fa1157624b52bf00fe4e87fdd77b":{
      "scriptId":"u34"}}});