$axure.loadCurrentPage({
  "url":"批量复核_p2.html",
  "generationDate":new Date(1461745770174.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c00992344823473eab8cf3304fdbdd3d",
    "type":"Axure:Page",
    "name":"批量复核 p2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2c5cdbc3839e411f8e9c908bd6ae6308",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":210,
              "y":210},
            "size":{
              "width":1219,
              "height":830},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5adcb7cb9d7642d59bdb049782ff1f2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.3",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":210,
                  "y":210},
                "size":{
                  "width":1219,
                  "height":830},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/批量复核_p2/u0.png"}},
{
          "id":"30f796edb5144e28bd84e6277f215abe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":740,
              "y":253},
            "size":{
              "width":145,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfecc3e164104d6c8870c711c3c05f81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":740,
                  "y":253},
                "size":{
                  "width":145,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"726edcc1bf1645798eb615105d0c1659",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":310},
            "size":{
              "width":1150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/批量复核_p2/u4_line.png"}},
{
          "id":"36fb50b2fa2b4931a742466dcfe4e31c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":245},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5196182f17b14aa2a380a5c9b7263c19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":245},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/批量复核_p2/u5.png"}},
{
          "id":"850d752520f64a77adda398f267d91cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":305,
              "y":389},
            "size":{
              "width":1070,
              "height":458}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9973e389c2b34ad48b6e96f0115f2ebf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":305,
                  "y":389},
                "size":{
                  "width":1070,
                  "height":458}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/批量复核_p2/u7.png"}},
{
          "id":"59592c6a6d84407ca1178d59433df01e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1310,
              "y":230},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77e0ef8213684bbdb8f286a566345560",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1310,
                  "y":230},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页（控制台）",
                      "target":{
                        "targetType":"page",
                        "url":"首页（控制台）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u74.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2c5cdbc3839e411f8e9c908bd6ae6308":{
      "scriptId":"u0"},
    "5adcb7cb9d7642d59bdb049782ff1f2d":{
      "scriptId":"u1"},
    "30f796edb5144e28bd84e6277f215abe":{
      "scriptId":"u2"},
    "bfecc3e164104d6c8870c711c3c05f81":{
      "scriptId":"u3"},
    "726edcc1bf1645798eb615105d0c1659":{
      "scriptId":"u4"},
    "36fb50b2fa2b4931a742466dcfe4e31c":{
      "scriptId":"u5"},
    "5196182f17b14aa2a380a5c9b7263c19":{
      "scriptId":"u6"},
    "850d752520f64a77adda398f267d91cd":{
      "scriptId":"u7"},
    "9973e389c2b34ad48b6e96f0115f2ebf":{
      "scriptId":"u8"},
    "59592c6a6d84407ca1178d59433df01e":{
      "scriptId":"u9"},
    "77e0ef8213684bbdb8f286a566345560":{
      "scriptId":"u10"}}});