$axure.loadCurrentPage({
  "url":"大入口.html",
  "generationDate":new Date(1458553410645.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"58463720f2bc4f26bc78efd8ecc814bd",
    "type":"Axure:Page",
    "name":"大入口",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3964e2ea906048a09292f261ac387e0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":200,
              "y":200},
            "size":{
              "width":1219,
              "height":890},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e487af5aafc4006927b8be176830455",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.3",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":200,
                  "y":200},
                "size":{
                  "width":1219,
                  "height":890},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/大入口/u0.png"}},
{
          "id":"209f7ab4221d47079c138a3f7902eeb1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":300},
            "size":{
              "width":1219,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/帮助/u43_line.png"}},
{
          "id":"392d36b3a9204d02ae10c1eaf8dc1124",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":220},
            "size":{
              "width":125,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95a1f32e2e044a81b8e5c7e4a92f08e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":235,
                  "y":220},
                "size":{
                  "width":125,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u47.png"}},
{
          "id":"e972081874cb4d8abc980e388889bda0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1350,
              "y":230},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c60456cbc7834da19e5d68e69214d525",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1350,
                  "y":230},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle 右侧边栏",
                      "objectsToFades":[{
                          "objectPath":["1313c76049de4226b11e3c8869f9793f"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u57.png"}},
{
          "id":"c1cf03a3b4c142ebbb85df18ac63d34e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":410,
              "y":547},
            "size":{
              "width":320,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50819981045648548882ef1bbf03f4bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":410,
                  "y":547},
                "size":{
                  "width":320,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/大入口/u7.png"}},
{
          "id":"0cdcc5fd28c8400a8c0c78ef079b338a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":960,
              "y":547},
            "size":{
              "width":320,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c2d336dbc404acfbc74accf494aeb05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":960,
                  "y":547},
                "size":{
                  "width":320,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/大入口/u7.png"}},
{
          "id":"1313c76049de4226b11e3c8869f9793f",
          "label":"右侧边栏",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":1219,
              "y":300},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"88397ffe8816497886d64b6c396a5824",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"86e98a8946214c14aa6d8f1c8ca9c7c1",
                  "label":"",
                  "parentDynamicPanel":"1313c76049de4226b11e3c8869f9793f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":205}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7d140b87cf5b4b8d845fd7dfb51e9d2a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1313c76049de4226b11e3c8869f9793f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":205}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/帮助/u60.png"}},
{
                  "id":"e3bf1cffa7964d4c9b806dafa701359e",
                  "label":"",
                  "parentDynamicPanel":"1313c76049de4226b11e3c8869f9793f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"700",
                    "location":{
                      "x":12,
                      "y":26},
                    "size":{
                      "width":174,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"865af09fbfbc4dd098542205f01bcab5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1313c76049de4226b11e3c8869f9793f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"700",
                        "location":{
                          "x":12,
                          "y":26},
                        "size":{
                          "width":174,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"aa5416ea852a434ead5105212f9aba73",
                  "label":"",
                  "parentDynamicPanel":"1313c76049de4226b11e3c8869f9793f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":41,
                      "y":73},
                    "size":{
                      "width":120,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9fc8521423f94008bfaebcb434dfe7c9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1313c76049de4226b11e3c8869f9793f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":41,
                          "y":73},
                        "size":{
                          "width":120,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 基本信息（个人呈现）",
                              "target":{
                                "targetType":"page",
                                "url":"基本信息（个人呈现）.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/帮助/u64.png"}},
{
                  "id":"cb58d66ca9df4fc4bfd48516e7e393b9",
                  "label":"",
                  "parentDynamicPanel":"1313c76049de4226b11e3c8869f9793f",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":75,
                      "y":128},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3f004de2e2dc44dcb0b6f3d0b1ebe142",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1313c76049de4226b11e3c8869f9793f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":75,
                          "y":128},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/帮助/u66.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "3964e2ea906048a09292f261ac387e0f":{
      "scriptId":"u0"},
    "6e487af5aafc4006927b8be176830455":{
      "scriptId":"u1"},
    "209f7ab4221d47079c138a3f7902eeb1":{
      "scriptId":"u2"},
    "392d36b3a9204d02ae10c1eaf8dc1124":{
      "scriptId":"u3"},
    "95a1f32e2e044a81b8e5c7e4a92f08e2":{
      "scriptId":"u4"},
    "e972081874cb4d8abc980e388889bda0":{
      "scriptId":"u5"},
    "c60456cbc7834da19e5d68e69214d525":{
      "scriptId":"u6"},
    "c1cf03a3b4c142ebbb85df18ac63d34e":{
      "scriptId":"u7"},
    "50819981045648548882ef1bbf03f4bf":{
      "scriptId":"u8"},
    "0cdcc5fd28c8400a8c0c78ef079b338a":{
      "scriptId":"u9"},
    "4c2d336dbc404acfbc74accf494aeb05":{
      "scriptId":"u10"},
    "1313c76049de4226b11e3c8869f9793f":{
      "scriptId":"u11"},
    "86e98a8946214c14aa6d8f1c8ca9c7c1":{
      "scriptId":"u12"},
    "7d140b87cf5b4b8d845fd7dfb51e9d2a":{
      "scriptId":"u13"},
    "e3bf1cffa7964d4c9b806dafa701359e":{
      "scriptId":"u14"},
    "865af09fbfbc4dd098542205f01bcab5":{
      "scriptId":"u15"},
    "aa5416ea852a434ead5105212f9aba73":{
      "scriptId":"u16"},
    "9fc8521423f94008bfaebcb434dfe7c9":{
      "scriptId":"u17"},
    "cb58d66ca9df4fc4bfd48516e7e393b9":{
      "scriptId":"u18"},
    "3f004de2e2dc44dcb0b6f3d0b1ebe142":{
      "scriptId":"u19"}}});