$axure.loadCurrentPage({
  "url":"版本说明.html",
  "generationDate":new Date(1469168368684.55),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fb277297a82a47cdbd3967994253c38b",
    "type":"Axure:Page",
    "name":"版本说明",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4008e07c11c64b0bb1cbde18b5a42d83",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":100},
            "size":{
              "width":1060,
              "height":477}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e8e0e02bfd34a8c85aac5de1e0f593b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":147,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2cfdcb299f1340ce9df260b6af10b582",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":147,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/版本说明/u1.png"}},
{
              "id":"98c3c2eb621246d8bfa3ec3c5e5f54bd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":147,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8957d95d4ffc491bbe3115ac4cb82ce5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":147,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/版本说明/u7.png"}},
{
              "id":"c7ccaa63901943a0bce31dd66fb17f7e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":107},
                "size":{
                  "width":147,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0933afac0754471da561b170e4a25d44",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":107},
                    "size":{
                      "width":147,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/版本说明/u13.png"}},
{
              "id":"844c800f88df4b7d9214c63c5bd32545",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":147,
                  "y":0},
                "size":{
                  "width":174,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f8863f0e02f04c99bc1c8551a2dd3f79",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":147,
                      "y":0},
                    "size":{
                      "width":174,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/版本说明/u3.png"}},
{
              "id":"70f6d9aa157e42cb8a73e6658dd92d0f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":147,
                  "y":30},
                "size":{
                  "width":174,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2b659e1da2c04ba9bb5be19aee10e63e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":147,
                      "y":30},
                    "size":{
                      "width":174,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/版本说明/u9.png"}},
{
              "id":"be55935aea1a405cad74cfa33b2a993d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":147,
                  "y":107},
                "size":{
                  "width":174,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e4e4338d37574ae78ddea788808fc7ec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":147,
                      "y":107},
                    "size":{
                      "width":174,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/版本说明/u15.png"}},
{
              "id":"096584e0e768450fbf1a4f2deffac8c4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":321,
                  "y":0},
                "size":{
                  "width":739,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ccd26122aedd45808fa6ab8496a07b53",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":321,
                      "y":0},
                    "size":{
                      "width":739,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/版本说明/u5.png"}},
{
              "id":"b9243e254e9a492689585f0e8c4b20de",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":321,
                  "y":30},
                "size":{
                  "width":739,
                  "height":77}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b089c2fb04ed4e8e899d5f7463b68eaa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":321,
                      "y":30},
                    "size":{
                      "width":739,
                      "height":77}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/版本说明/u11.png"}},
{
              "id":"eaa6a5cc193b4b61a8a8ed1b2e299dc6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":321,
                  "y":107},
                "size":{
                  "width":739,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5f070be8f0354f7ba533db1cf7010fe2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":321,
                      "y":107},
                    "size":{
                      "width":739,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/版本说明/u17.png"}},
{
              "id":"75b646b3513c4e78bc534350b3cfc783",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":175},
                "size":{
                  "width":147,
                  "height":65}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"84382b79d4b74a11b2fd3c22cb17dc40",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":175},
                    "size":{
                      "width":147,
                      "height":65}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/版本说明/u19.png"}},
{
              "id":"5c21e00854e543f08fac8fd6155cbbf5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":147,
                  "y":175},
                "size":{
                  "width":174,
                  "height":65}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e1a42b8468b54fafad8fbd9aa1528192",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":147,
                      "y":175},
                    "size":{
                      "width":174,
                      "height":65}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/版本说明/u21.png"}},
{
              "id":"2eb2d6cf58614fa7b4e0aaf25fb1c23f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":321,
                  "y":175},
                "size":{
                  "width":739,
                  "height":65}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"99a93efb932d40d3920027039e34312c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":321,
                      "y":175},
                    "size":{
                      "width":739,
                      "height":65}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/版本说明/u23.png"}},
{
              "id":"904938f119544dec9cddc65b02f4a227",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":240},
                "size":{
                  "width":147,
                  "height":105}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4e349570b865403aade6dc15d5efabca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":240},
                    "size":{
                      "width":147,
                      "height":105}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/版本说明/u25.png"}},
{
              "id":"e78e8f1f450a460da7a1e2aefd31fef7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":147,
                  "y":240},
                "size":{
                  "width":174,
                  "height":105}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f1f3641b837141cd88769a429cb9eab4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":147,
                      "y":240},
                    "size":{
                      "width":174,
                      "height":105}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/版本说明/u27.png"}},
{
              "id":"b27e0693cf2c4dc1bff217d231af993b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":321,
                  "y":240},
                "size":{
                  "width":739,
                  "height":105}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"669800db99894a6e82b5c69979a4c15d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":321,
                      "y":240},
                    "size":{
                      "width":739,
                      "height":105}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/版本说明/u29.png"}},
{
              "id":"c45b52e442be47b3b09ea482d7c2df50",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":345},
                "size":{
                  "width":147,
                  "height":132}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"51b8dfe9f3574c15a70bdc436cf8d965",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":345},
                    "size":{
                      "width":147,
                      "height":132}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/版本说明/u31.png"}},
{
              "id":"ab59967fc4a84a86809f8874e6f15745",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":147,
                  "y":345},
                "size":{
                  "width":174,
                  "height":132}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1a6d2e738f084e02933f435d83e1b964",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":147,
                      "y":345},
                    "size":{
                      "width":174,
                      "height":132}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/版本说明/u33.png"}},
{
              "id":"0a2482ec826b4691be1878797c92836f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":321,
                  "y":345},
                "size":{
                  "width":739,
                  "height":132}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d621bed55f7643cda55338e3c7151495",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":321,
                      "y":345},
                    "size":{
                      "width":739,
                      "height":132}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/版本说明/u35.png"}}]},
{
          "id":"41db54e34cba41e7b16d9a2b4b690789",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":42},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d382023d1e2c42db834a1dee51737ddc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":42},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4008e07c11c64b0bb1cbde18b5a42d83":{
      "scriptId":"u0"},
    "7e8e0e02bfd34a8c85aac5de1e0f593b":{
      "scriptId":"u1"},
    "2cfdcb299f1340ce9df260b6af10b582":{
      "scriptId":"u2"},
    "844c800f88df4b7d9214c63c5bd32545":{
      "scriptId":"u3"},
    "f8863f0e02f04c99bc1c8551a2dd3f79":{
      "scriptId":"u4"},
    "096584e0e768450fbf1a4f2deffac8c4":{
      "scriptId":"u5"},
    "ccd26122aedd45808fa6ab8496a07b53":{
      "scriptId":"u6"},
    "98c3c2eb621246d8bfa3ec3c5e5f54bd":{
      "scriptId":"u7"},
    "8957d95d4ffc491bbe3115ac4cb82ce5":{
      "scriptId":"u8"},
    "70f6d9aa157e42cb8a73e6658dd92d0f":{
      "scriptId":"u9"},
    "2b659e1da2c04ba9bb5be19aee10e63e":{
      "scriptId":"u10"},
    "b9243e254e9a492689585f0e8c4b20de":{
      "scriptId":"u11"},
    "b089c2fb04ed4e8e899d5f7463b68eaa":{
      "scriptId":"u12"},
    "c7ccaa63901943a0bce31dd66fb17f7e":{
      "scriptId":"u13"},
    "0933afac0754471da561b170e4a25d44":{
      "scriptId":"u14"},
    "be55935aea1a405cad74cfa33b2a993d":{
      "scriptId":"u15"},
    "e4e4338d37574ae78ddea788808fc7ec":{
      "scriptId":"u16"},
    "eaa6a5cc193b4b61a8a8ed1b2e299dc6":{
      "scriptId":"u17"},
    "5f070be8f0354f7ba533db1cf7010fe2":{
      "scriptId":"u18"},
    "75b646b3513c4e78bc534350b3cfc783":{
      "scriptId":"u19"},
    "84382b79d4b74a11b2fd3c22cb17dc40":{
      "scriptId":"u20"},
    "5c21e00854e543f08fac8fd6155cbbf5":{
      "scriptId":"u21"},
    "e1a42b8468b54fafad8fbd9aa1528192":{
      "scriptId":"u22"},
    "2eb2d6cf58614fa7b4e0aaf25fb1c23f":{
      "scriptId":"u23"},
    "99a93efb932d40d3920027039e34312c":{
      "scriptId":"u24"},
    "904938f119544dec9cddc65b02f4a227":{
      "scriptId":"u25"},
    "4e349570b865403aade6dc15d5efabca":{
      "scriptId":"u26"},
    "e78e8f1f450a460da7a1e2aefd31fef7":{
      "scriptId":"u27"},
    "f1f3641b837141cd88769a429cb9eab4":{
      "scriptId":"u28"},
    "b27e0693cf2c4dc1bff217d231af993b":{
      "scriptId":"u29"},
    "669800db99894a6e82b5c69979a4c15d":{
      "scriptId":"u30"},
    "c45b52e442be47b3b09ea482d7c2df50":{
      "scriptId":"u31"},
    "51b8dfe9f3574c15a70bdc436cf8d965":{
      "scriptId":"u32"},
    "ab59967fc4a84a86809f8874e6f15745":{
      "scriptId":"u33"},
    "1a6d2e738f084e02933f435d83e1b964":{
      "scriptId":"u34"},
    "0a2482ec826b4691be1878797c92836f":{
      "scriptId":"u35"},
    "d621bed55f7643cda55338e3c7151495":{
      "scriptId":"u36"},
    "41db54e34cba41e7b16d9a2b4b690789":{
      "scriptId":"u37"},
    "d382023d1e2c42db834a1dee51737ddc":{
      "scriptId":"u38"}}});