$axure.loadCurrentPage({
  "url":"修改密码成功提示（不需要）.html",
  "generationDate":new Date(1458553414733.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b18cd28784db472e85642b2be1ed7ba1",
    "type":"Axure:Page",
    "name":"修改密码成功提示（不需要）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"73c6f94c75c74d489f456974e3f59461",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":200,
              "y":200},
            "size":{
              "width":1219,
              "height":840},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93d9a3d3da3140a39cfa8db47653e47b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.3",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":200,
                  "y":200},
                "size":{
                  "width":1219,
                  "height":840},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/密码管理/u0.png"}},
{
          "id":"d93c5b4321e54dc0bf295a869905f179",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":300},
            "size":{
              "width":1219,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/帮助/u43_line.png"}},
{
          "id":"0e5413fe63b94fdbaf0af013a997e81f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":220},
            "size":{
              "width":125,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"628c90478bcf44318e8e904e6949b1f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":235,
                  "y":220},
                "size":{
                  "width":125,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u47.png"}},
{
          "id":"78675f319bc54510a2aebd710ed91b3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":387,
              "y":237},
            "size":{
              "width":113,
              "height":43},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0aeb0e7cc87453e8e93bf05bc08722d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":387,
                  "y":237},
                "size":{
                  "width":113,
                  "height":43},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页（控制台）",
                      "target":{
                        "targetType":"page",
                        "url":"首页（控制台）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u49.png"}},
{
          "id":"7117add7a1e04b75bc7c32feab25dca0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":521,
              "y":237},
            "size":{
              "width":113,
              "height":43},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e348f5f019d48eb96d7835eab95563e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":521,
                  "y":237},
                "size":{
                  "width":113,
                  "height":43},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 渠道管理",
                      "target":{
                        "targetType":"page",
                        "url":"渠道管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u49.png"}},
{
          "id":"363febe1550b40509a511f768ec3cedd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":655,
              "y":237},
            "size":{
              "width":113,
              "height":43},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9030b1894bf45e48e1c3e52ac4e6a7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":655,
                  "y":237},
                "size":{
                  "width":113,
                  "height":43},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 提现",
                      "target":{
                        "targetType":"page",
                        "url":"提现.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u49.png"}},
{
          "id":"65ac131267eb4a1aba6df11d83135a67",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1350,
              "y":230},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72de8bcc5ea749128a4d0b4e3470c7fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1350,
                  "y":230},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u57.png"}},
{
          "id":"01855e5bc2ac4692abcf0e5acf5b7492",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":306},
            "size":{
              "width":210,
              "height":644}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8098a3ae54cf495ba2f2176dc0e031ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":306},
                "size":{
                  "width":210,
                  "height":644}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/结算信息/u13.png"}},
{
          "id":"1ab84e74e91843cbaa08f63df87b271c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":218,
              "y":352},
            "size":{
              "width":174,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54675615c98a430ca91f16db19b32c03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":218,
                  "y":352},
                "size":{
                  "width":174,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e1e4af5e02b47a4bbc39dc021b6ee34",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":247,
              "y":398},
            "size":{
              "width":120,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54c4909bd74e4b6193296ce54dc9e178",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":247,
                  "y":398},
                "size":{
                  "width":120,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u64.png"}},
{
          "id":"c06cadd47c2d4000b7f7a32034f36e18",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":460},
            "size":{
              "width":210,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息（个人呈现）/u19_line.png"}},
{
          "id":"312926a47a4a4dcba56a6e802d5df984",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":205,
              "y":524},
            "size":{
              "width":200,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息（个人呈现）/u20_line.png"}},
{
          "id":"dba4558858eb49abaffa6a054f8a0369",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":480},
            "size":{
              "width":42,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbf5afce2c12487397bd7659e9737e91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":218,
                  "y":480},
                "size":{
                  "width":42,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u21.png"}},
{
          "id":"a9e6f094be044182ab2884bb1a787b76",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":272,
              "y":492},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ac90e943c0c4e879b15208f35bd37e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":272,
                  "y":492},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02f9d682716d449789fed675a0fe9583",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":366,
              "y":492},
            "size":{
              "width":32,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0c848d12dfb44b6bb404089d6d156a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":366,
                  "y":492},
                "size":{
                  "width":32,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u25.png"}},
{
          "id":"b684c1a092a541cfa36a9ad6a78c24c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":434,
              "y":328},
            "size":{
              "width":946,
              "height":682}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"633c8e6f85b94c2683557beb3b8ee6e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":434,
                  "y":328},
                "size":{
                  "width":946,
                  "height":682}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/密码管理/u27.png"}},
{
          "id":"a96647cf95bf414ba88c7c78069b3f2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":434,
              "y":328},
            "size":{
              "width":946,
              "height":92}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f946ded63e846469ceff17d86326085",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":434,
                  "y":328},
                "size":{
                  "width":946,
                  "height":92}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u29.png"}},
{
          "id":"69a0e62f701d4b5882da1ad3718a903e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":475,
              "y":364},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3c192efb22a4c3487196510bea966e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":475,
                  "y":364},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b281db4e684471f9831e33483ccd68a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":205,
              "y":605},
            "size":{
              "width":200,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息（个人呈现）/u20_line.png"}},
{
          "id":"7c8cf1f09bf8455c917854ce0fa93bed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":561},
            "size":{
              "width":42,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae78e0a478274ce8964b3b8069cc8723",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":218,
                  "y":561},
                "size":{
                  "width":42,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u21.png"}},
{
          "id":"348364c3b4264a4e89776293c796f62c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":272,
              "y":573},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1aa56efd615647068c7220405505fb85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":272,
                  "y":573},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5449c200b05b413d9ab2a1007c7ff559",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":366,
              "y":573},
            "size":{
              "width":32,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ae74dc5ef9547d7b9d00aabe646a43a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":366,
                  "y":573},
                "size":{
                  "width":32,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u25.png"}},
{
          "id":"ae327e6760be4707a97df1cb592139b9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":689},
            "size":{
              "width":200,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息（个人呈现）/u20_line.png"}},
{
          "id":"b773ede218ac422c82cbc2250f0f86fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":217,
              "y":645},
            "size":{
              "width":42,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5aa94d479584cbab83ac14cac45ea9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":217,
                  "y":645},
                "size":{
                  "width":42,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u21.png"}},
{
          "id":"6e736df9e8d6461f818186fe37ce6967",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":271,
              "y":657},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e941efd0f7b64b3cabe7dbb393dd8a72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":271,
                  "y":657},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ccca22e2c9443ff8609b9270c6d6e17",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":657},
            "size":{
              "width":32,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf1279da20664e578f200a1e091408c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":365,
                  "y":657},
                "size":{
                  "width":32,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u25.png"}},
{
          "id":"a5dfbe55f6ae428b8d09660b15f1704d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":207,
              "y":768},
            "size":{
              "width":200,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息（个人呈现）/u20_line.png"}},
{
          "id":"5ada0ed49b024a22b6d08bbcc784b79e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":724},
            "size":{
              "width":42,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7881e7ea043741fc9f19e070091c462d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":724},
                "size":{
                  "width":42,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u21.png"}},
{
          "id":"2e4b2c5e7e22478eab8ff0d66f93f7ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":274,
              "y":736},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1dfdf1560284067b6a15e84ac7ffbcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":274,
                  "y":736},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45a3411ff70f4196b62f98c3d92d292f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":368,
              "y":736},
            "size":{
              "width":32,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f83b236e94f94c46bd2a25cc7e90008e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":368,
                  "y":736},
                "size":{
                  "width":32,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u25.png"}},
{
          "id":"2a230ce2ed034769a6d774d2f3a75874",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":481,
              "y":709},
            "size":{
              "width":838,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户签约-基本信息（个人）/u35_line.png"}},
{
          "id":"0d460dea52de4d9e8bcfa79ff6f1f766",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":517,
              "y":460},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77cfc69f853840af9031e99e2bca3c90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":517,
                  "y":460},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1592c32bedf4b4eae672a00d197ad1f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":461},
            "size":{
              "width":220,
              "height":23}},
          "adaptiveStyles":{
}},
{
          "id":"e472a46f8e0c4dccbf3d803dd58c60a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":517,
              "y":536},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65063a3f47f34c58bcd13a1d0f3f1d09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":517,
                  "y":536},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c85e90918037451bb414438c62c6d735",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":537},
            "size":{
              "width":220,
              "height":23}},
          "adaptiveStyles":{
}},
{
          "id":"4d6217260ad4489c9371c4f7d3da7fdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":483,
              "y":616},
            "size":{
              "width":127,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d3ec4d0de6e441d88fdcc7a87aa6181",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":483,
                  "y":616},
                "size":{
                  "width":127,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ad7ead189bd478a8fa6bf7ef233f941",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":617},
            "size":{
              "width":220,
              "height":23}},
          "adaptiveStyles":{
}},
{
          "id":"a1a71371f88240dfa04df76d40c1bdd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1160,
              "y":664},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b37e4fcc9e34e79ae65bfb7149c0ad7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1160,
                  "y":664},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u85.png"}},
{
          "id":"2efc0bcf95d04545853450b187467a8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":517,
              "y":756},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a82dd43143b54b56b76d800ef557a7ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":517,
                  "y":756},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6451e20f4dde41b090e716aa67c02376",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":757},
            "size":{
              "width":220,
              "height":23}},
          "adaptiveStyles":{
}},
{
          "id":"580c85a1acf64b5fb113bda7f4a544d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":517,
              "y":832},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfbeb6ba8763437bb857e1f9774c1b17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":517,
                  "y":832},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebff6177c6724c06a102dd20e3d51506",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":833},
            "size":{
              "width":220,
              "height":23}},
          "adaptiveStyles":{
}},
{
          "id":"8c8593645fdc49eb9a860ae7d364b96a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":483,
              "y":912},
            "size":{
              "width":127,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cea634c92b9482ebead3706c502bf42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":483,
                  "y":912},
                "size":{
                  "width":127,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"334d2b6fb4984ca88eb8a53e759e6290",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":913},
            "size":{
              "width":220,
              "height":23}},
          "adaptiveStyles":{
}},
{
          "id":"e3a89dd57ff441d9bd31153becf817ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1160,
              "y":960},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55f1507388a740f7abd949e5611b1a27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1160,
                  "y":960},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u85.png"}},
{
          "id":"d46aac15af6f4e86b8784edac8827b70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":878,
              "y":762},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ecf552d669c499eb7ac1daada3e8616",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":878,
                  "y":762},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 找回原安全密码",
                      "target":{
                        "targetType":"page",
                        "url":"找回原安全密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"175cf7cac4594089a5f6783ab5aed95e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":648,
              "y":494},
            "size":{
              "width":104,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b28302e75ee4763990c33b542413041",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":648,
                  "y":494},
                "size":{
                  "width":104,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92570d14f8174a67a59c4f56ea466814",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":494},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"517232d69e1642ababfd9822734a9699",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":494},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u81.png"}},
{
          "id":"62994f0d940846e787ec737d29a35c9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":648,
              "y":570},
            "size":{
              "width":104,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ff9bbfcd3564b699b28ea3a5aa5aecd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":648,
                  "y":570},
                "size":{
                  "width":104,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29f9232cff5341309738b24a9053fcbd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":570},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea1560688e6f4cb2889144c820f745d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":570},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u81.png"}},
{
          "id":"77da3f531b3a4b5499a4d6239b91f2a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":648,
              "y":659},
            "size":{
              "width":104,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9a98664bf9a4b91a4343580ace47790",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":648,
                  "y":659},
                "size":{
                  "width":104,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c75ec4af6434ab6b1c84d5669194a33",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":659},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d718077897d46f78a86312b97fefdb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":659},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u81.png"}},
{
          "id":"f402102551de4938a1fad4b49ee32682",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":648,
              "y":790},
            "size":{
              "width":104,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9363adb1a3b04ac38c326e4c35358e06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":648,
                  "y":790},
                "size":{
                  "width":104,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fe76ba8515c40c49b999b91257db311",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":790},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdb5d9a7dc27445293f47d208de85d31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":790},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u81.png"}},
{
          "id":"9ab759eb74524b3980ff22bf726778f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":648,
              "y":866},
            "size":{
              "width":104,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53cad260b440402da7fd259be85b101e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":648,
                  "y":866},
                "size":{
                  "width":104,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"694c51aaed4449b09c61c160f3c5ed5d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":866},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59d8c54db095451e8f59f5a2279243c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":866},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u81.png"}},
{
          "id":"c027681783f64ffbbbb96f87c314d5ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":648,
              "y":946},
            "size":{
              "width":104,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81f0c8e0def9408b9174e6dea75cafe8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":648,
                  "y":946},
                "size":{
                  "width":104,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42f56b42f23641a4b3459f20d91a40d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":946},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c769da8f2ef4ed88745511c2627d580",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":946},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u81.png"}},
{
          "id":"0cb0838ac28545bca19f78238e30306d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":1470,
              "y":230},
            "size":{
              "width":430,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"367da54628dd486494bbdd361254c2d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":1470,
                  "y":230},
                "size":{
                  "width":430,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u88.png"}},
{
          "id":"80fa49dbc07f46ada95ff74ce2ed64b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":868,
              "y":542},
            "size":{
              "width":121,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a700ee39007c4df29c898d0bdd7283ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":868,
                  "y":542},
                "size":{
                  "width":121,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cb9a7284a6d40ada92b0dd16a96cc36",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.4",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":210,
              "y":210},
            "size":{
              "width":1220,
              "height":930}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b42e6b69c79046a4ba794fdc1e8ca83c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.4",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":210,
                  "y":210},
                "size":{
                  "width":1220,
                  "height":930}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改基本信息成功提示/u115.png"}},
{
          "id":"89f4b1bde3344666b3a37973e43e25b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":531,
              "y":560},
            "size":{
              "width":519,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f08a6826128d4c6a9231f139dba07138",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":531,
                  "y":560},
                "size":{
                  "width":519,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-提交成功提醒/u90.png"}},
{
          "id":"c6ecae35a0994e13a9e1b265e04007b8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":531,
              "y":719},
            "size":{
              "width":519,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户签约-提交成功提醒/u92_line.png"}},
{
          "id":"cb5dde67acd64648964388c3b80cad56",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":720,
              "y":747},
            "size":{
              "width":120,
              "height":37},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2795d93f97d7487d9aeddc8ce166e4a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":720,
                  "y":747},
                "size":{
                  "width":120,
                  "height":37},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页（控制台）",
                      "target":{
                        "targetType":"page",
                        "url":"首页（控制台）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户签约-提交成功提醒/u93.png"}},
{
          "id":"f2141c9ed28e41ebb7d2353f59e93266",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":562,
              "y":614},
            "size":{
              "width":477,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3e9ea54c6d7476ab83d49e2278de38f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":562,
                  "y":614},
                "size":{
                  "width":477,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "73c6f94c75c74d489f456974e3f59461":{
      "scriptId":"u0"},
    "93d9a3d3da3140a39cfa8db47653e47b":{
      "scriptId":"u1"},
    "d93c5b4321e54dc0bf295a869905f179":{
      "scriptId":"u2"},
    "0e5413fe63b94fdbaf0af013a997e81f":{
      "scriptId":"u3"},
    "628c90478bcf44318e8e904e6949b1f2":{
      "scriptId":"u4"},
    "78675f319bc54510a2aebd710ed91b3b":{
      "scriptId":"u5"},
    "b0aeb0e7cc87453e8e93bf05bc08722d":{
      "scriptId":"u6"},
    "7117add7a1e04b75bc7c32feab25dca0":{
      "scriptId":"u7"},
    "3e348f5f019d48eb96d7835eab95563e":{
      "scriptId":"u8"},
    "363febe1550b40509a511f768ec3cedd":{
      "scriptId":"u9"},
    "e9030b1894bf45e48e1c3e52ac4e6a7a":{
      "scriptId":"u10"},
    "65ac131267eb4a1aba6df11d83135a67":{
      "scriptId":"u11"},
    "72de8bcc5ea749128a4d0b4e3470c7fb":{
      "scriptId":"u12"},
    "01855e5bc2ac4692abcf0e5acf5b7492":{
      "scriptId":"u13"},
    "8098a3ae54cf495ba2f2176dc0e031ed":{
      "scriptId":"u14"},
    "1ab84e74e91843cbaa08f63df87b271c":{
      "scriptId":"u15"},
    "54675615c98a430ca91f16db19b32c03":{
      "scriptId":"u16"},
    "3e1e4af5e02b47a4bbc39dc021b6ee34":{
      "scriptId":"u17"},
    "54c4909bd74e4b6193296ce54dc9e178":{
      "scriptId":"u18"},
    "c06cadd47c2d4000b7f7a32034f36e18":{
      "scriptId":"u19"},
    "312926a47a4a4dcba56a6e802d5df984":{
      "scriptId":"u20"},
    "dba4558858eb49abaffa6a054f8a0369":{
      "scriptId":"u21"},
    "dbf5afce2c12487397bd7659e9737e91":{
      "scriptId":"u22"},
    "a9e6f094be044182ab2884bb1a787b76":{
      "scriptId":"u23"},
    "3ac90e943c0c4e879b15208f35bd37e7":{
      "scriptId":"u24"},
    "02f9d682716d449789fed675a0fe9583":{
      "scriptId":"u25"},
    "b0c848d12dfb44b6bb404089d6d156a8":{
      "scriptId":"u26"},
    "b684c1a092a541cfa36a9ad6a78c24c2":{
      "scriptId":"u27"},
    "633c8e6f85b94c2683557beb3b8ee6e6":{
      "scriptId":"u28"},
    "a96647cf95bf414ba88c7c78069b3f2b":{
      "scriptId":"u29"},
    "1f946ded63e846469ceff17d86326085":{
      "scriptId":"u30"},
    "69a0e62f701d4b5882da1ad3718a903e":{
      "scriptId":"u31"},
    "f3c192efb22a4c3487196510bea966e6":{
      "scriptId":"u32"},
    "2b281db4e684471f9831e33483ccd68a":{
      "scriptId":"u33"},
    "7c8cf1f09bf8455c917854ce0fa93bed":{
      "scriptId":"u34"},
    "ae78e0a478274ce8964b3b8069cc8723":{
      "scriptId":"u35"},
    "348364c3b4264a4e89776293c796f62c":{
      "scriptId":"u36"},
    "1aa56efd615647068c7220405505fb85":{
      "scriptId":"u37"},
    "5449c200b05b413d9ab2a1007c7ff559":{
      "scriptId":"u38"},
    "2ae74dc5ef9547d7b9d00aabe646a43a":{
      "scriptId":"u39"},
    "ae327e6760be4707a97df1cb592139b9":{
      "scriptId":"u40"},
    "b773ede218ac422c82cbc2250f0f86fc":{
      "scriptId":"u41"},
    "b5aa94d479584cbab83ac14cac45ea9f":{
      "scriptId":"u42"},
    "6e736df9e8d6461f818186fe37ce6967":{
      "scriptId":"u43"},
    "e941efd0f7b64b3cabe7dbb393dd8a72":{
      "scriptId":"u44"},
    "0ccca22e2c9443ff8609b9270c6d6e17":{
      "scriptId":"u45"},
    "bf1279da20664e578f200a1e091408c6":{
      "scriptId":"u46"},
    "a5dfbe55f6ae428b8d09660b15f1704d":{
      "scriptId":"u47"},
    "5ada0ed49b024a22b6d08bbcc784b79e":{
      "scriptId":"u48"},
    "7881e7ea043741fc9f19e070091c462d":{
      "scriptId":"u49"},
    "2e4b2c5e7e22478eab8ff0d66f93f7ce":{
      "scriptId":"u50"},
    "d1dfdf1560284067b6a15e84ac7ffbcb":{
      "scriptId":"u51"},
    "45a3411ff70f4196b62f98c3d92d292f":{
      "scriptId":"u52"},
    "f83b236e94f94c46bd2a25cc7e90008e":{
      "scriptId":"u53"},
    "2a230ce2ed034769a6d774d2f3a75874":{
      "scriptId":"u54"},
    "0d460dea52de4d9e8bcfa79ff6f1f766":{
      "scriptId":"u55"},
    "77cfc69f853840af9031e99e2bca3c90":{
      "scriptId":"u56"},
    "d1592c32bedf4b4eae672a00d197ad1f":{
      "scriptId":"u57"},
    "e472a46f8e0c4dccbf3d803dd58c60a2":{
      "scriptId":"u58"},
    "65063a3f47f34c58bcd13a1d0f3f1d09":{
      "scriptId":"u59"},
    "c85e90918037451bb414438c62c6d735":{
      "scriptId":"u60"},
    "4d6217260ad4489c9371c4f7d3da7fdf":{
      "scriptId":"u61"},
    "9d3ec4d0de6e441d88fdcc7a87aa6181":{
      "scriptId":"u62"},
    "7ad7ead189bd478a8fa6bf7ef233f941":{
      "scriptId":"u63"},
    "a1a71371f88240dfa04df76d40c1bdd0":{
      "scriptId":"u64"},
    "1b37e4fcc9e34e79ae65bfb7149c0ad7":{
      "scriptId":"u65"},
    "2efc0bcf95d04545853450b187467a8a":{
      "scriptId":"u66"},
    "a82dd43143b54b56b76d800ef557a7ec":{
      "scriptId":"u67"},
    "6451e20f4dde41b090e716aa67c02376":{
      "scriptId":"u68"},
    "580c85a1acf64b5fb113bda7f4a544d4":{
      "scriptId":"u69"},
    "cfbeb6ba8763437bb857e1f9774c1b17":{
      "scriptId":"u70"},
    "ebff6177c6724c06a102dd20e3d51506":{
      "scriptId":"u71"},
    "8c8593645fdc49eb9a860ae7d364b96a":{
      "scriptId":"u72"},
    "0cea634c92b9482ebead3706c502bf42":{
      "scriptId":"u73"},
    "334d2b6fb4984ca88eb8a53e759e6290":{
      "scriptId":"u74"},
    "e3a89dd57ff441d9bd31153becf817ac":{
      "scriptId":"u75"},
    "55f1507388a740f7abd949e5611b1a27":{
      "scriptId":"u76"},
    "d46aac15af6f4e86b8784edac8827b70":{
      "scriptId":"u77"},
    "4ecf552d669c499eb7ac1daada3e8616":{
      "scriptId":"u78"},
    "175cf7cac4594089a5f6783ab5aed95e":{
      "scriptId":"u79"},
    "5b28302e75ee4763990c33b542413041":{
      "scriptId":"u80"},
    "92570d14f8174a67a59c4f56ea466814":{
      "scriptId":"u81"},
    "517232d69e1642ababfd9822734a9699":{
      "scriptId":"u82"},
    "62994f0d940846e787ec737d29a35c9b":{
      "scriptId":"u83"},
    "3ff9bbfcd3564b699b28ea3a5aa5aecd":{
      "scriptId":"u84"},
    "29f9232cff5341309738b24a9053fcbd":{
      "scriptId":"u85"},
    "ea1560688e6f4cb2889144c820f745d7":{
      "scriptId":"u86"},
    "77da3f531b3a4b5499a4d6239b91f2a2":{
      "scriptId":"u87"},
    "a9a98664bf9a4b91a4343580ace47790":{
      "scriptId":"u88"},
    "1c75ec4af6434ab6b1c84d5669194a33":{
      "scriptId":"u89"},
    "4d718077897d46f78a86312b97fefdb5":{
      "scriptId":"u90"},
    "f402102551de4938a1fad4b49ee32682":{
      "scriptId":"u91"},
    "9363adb1a3b04ac38c326e4c35358e06":{
      "scriptId":"u92"},
    "6fe76ba8515c40c49b999b91257db311":{
      "scriptId":"u93"},
    "fdb5d9a7dc27445293f47d208de85d31":{
      "scriptId":"u94"},
    "9ab759eb74524b3980ff22bf726778f4":{
      "scriptId":"u95"},
    "53cad260b440402da7fd259be85b101e":{
      "scriptId":"u96"},
    "694c51aaed4449b09c61c160f3c5ed5d":{
      "scriptId":"u97"},
    "59d8c54db095451e8f59f5a2279243c0":{
      "scriptId":"u98"},
    "c027681783f64ffbbbb96f87c314d5ee":{
      "scriptId":"u99"},
    "81f0c8e0def9408b9174e6dea75cafe8":{
      "scriptId":"u100"},
    "42f56b42f23641a4b3459f20d91a40d7":{
      "scriptId":"u101"},
    "1c769da8f2ef4ed88745511c2627d580":{
      "scriptId":"u102"},
    "0cb0838ac28545bca19f78238e30306d":{
      "scriptId":"u103"},
    "367da54628dd486494bbdd361254c2d6":{
      "scriptId":"u104"},
    "80fa49dbc07f46ada95ff74ce2ed64b6":{
      "scriptId":"u105"},
    "a700ee39007c4df29c898d0bdd7283ed":{
      "scriptId":"u106"},
    "6cb9a7284a6d40ada92b0dd16a96cc36":{
      "scriptId":"u107"},
    "b42e6b69c79046a4ba794fdc1e8ca83c":{
      "scriptId":"u108"},
    "89f4b1bde3344666b3a37973e43e25b4":{
      "scriptId":"u109"},
    "f08a6826128d4c6a9231f139dba07138":{
      "scriptId":"u110"},
    "c6ecae35a0994e13a9e1b265e04007b8":{
      "scriptId":"u111"},
    "cb5dde67acd64648964388c3b80cad56":{
      "scriptId":"u112"},
    "2795d93f97d7487d9aeddc8ce166e4a3":{
      "scriptId":"u113"},
    "f2141c9ed28e41ebb7d2353f59e93266":{
      "scriptId":"u114"},
    "b3e9ea54c6d7476ab83d49e2278de38f":{
      "scriptId":"u115"}}});