$axure.loadCurrentPage({
  "url":"隐私数据删除提醒_p2.html",
  "generationDate":new Date(1461745755984.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a355a039760f4f45aca04f95caff597f",
    "type":"Axure:Page",
    "name":"隐私数据删除提醒 p2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ddbc506c4336476baf6b627cdb5b52ef",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":183,
              "y":198}},
          "adaptiveStyles":{
},
          "masterId":"ce194b8bf61742aea7475dad35671852"},
{
          "id":"9e2dde39601e4ed28a04f4652d1ef6fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":434,
              "y":328},
            "size":{
              "width":946,
              "height":752}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6f3f53095b242d7a5594ac81536a8a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":434,
                  "y":328},
                "size":{
                  "width":946,
                  "height":752}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u66.png"}},
{
          "id":"db67d30e7ddc487cbf816d0d1218f00d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":434,
              "y":328},
            "size":{
              "width":946,
              "height":92}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bde1dd9f6d05432e82230ea9ced644f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":434,
                  "y":328},
                "size":{
                  "width":946,
                  "height":92}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u68.png"}},
{
          "id":"d0fa277a5e144467af313a11ea348be9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":475,
              "y":364},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ee464e6f5f748b2903f3a29b0d381d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":475,
                  "y":364},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c24281051d34beeb31ccf72be561a9d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":475,
              "y":438},
            "size":{
              "width":435,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c073910dab74db3a3e65bdaf8d0f1d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":475,
                  "y":438},
                "size":{
                  "width":435,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/隐私数据管理（订单数据）_p2/u36.png"}},
{
          "id":"ecd70a2bd5b24354b073a6006e26d129",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":500,
              "y":524},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd3480c95ac0432d93689b63a850e63e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":500,
                  "y":524},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f76a0690d0e64600a578c8cc46261507",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":524},
            "size":{
              "width":200,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"2af50576d94b4141a5f4a943dc529727",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":499,
              "y":560},
            "size":{
              "width":330,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2047dfe2c36e4acf9d91a065f9f21513",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":499,
                  "y":560},
                "size":{
                  "width":330,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/隐私数据管理（订单数据）_p2/u41.png"}},
{
          "id":"98a1a6f70e744ab487bfbc058cc29a7b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":499,
              "y":605},
            "size":{
              "width":174,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b81ec39b83794c09bd164bbbf960c1ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":499,
                  "y":605},
                "size":{
                  "width":174,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/隐私数据删除确认_p2/u43.png"}},
{
          "id":"97ca3cd63c77438eba4bc68cffff9862",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":499,
              "y":645},
            "size":{
              "width":290,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f01ee1aceba4754a682bb2d96b5acee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":499,
                  "y":645},
                "size":{
                  "width":290,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/隐私数据管理（订单数据）_p2/u43.png"}},
{
          "id":"f092b75bd2ec477aae624ccf09e31e95",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":499,
              "y":689},
            "size":{
              "width":624,
              "height":136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6cd149408c34a8192e96ae1707b7a83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":499,
                  "y":689},
                "size":{
                  "width":624,
                  "height":136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/隐私数据管理（订单数据）_p2/u45.png"}},
{
          "id":"a5f2959ca51140c9986ea742af0fb39c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.4",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":183,
              "y":198},
            "size":{
              "width":1220,
              "height":930}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a7a2c0fcc0f4c1886aa3aa9a8bc8c19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.4",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":183,
                  "y":198},
                "size":{
                  "width":1220,
                  "height":930}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/不可修改提醒/u91.png"}},
{
          "id":"d611449131cf4de4920768e50b3d26b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":531,
              "y":560},
            "size":{
              "width":519,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"164d58598cec4a52a1d5257538e04707",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":531,
                  "y":560},
                "size":{
                  "width":519,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-提交成功提醒/u81.png"}},
{
          "id":"35789591b1324990a1c88b9237e5ef76",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":531,
              "y":719},
            "size":{
              "width":519,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户签约-提交成功提醒/u83_line.png"}},
{
          "id":"c7c2bf0d3f534caebd284c0067366e03",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":720,
              "y":747},
            "size":{
              "width":120,
              "height":37},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a03fa7fe2ec049bd8abdea3d519c92b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":720,
                  "y":747},
                "size":{
                  "width":120,
                  "height":37},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户签约-提交成功提醒/u84.png"}},
{
          "id":"cd7675cd242e408583401cea69c3f7ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":562,
              "y":614},
            "size":{
              "width":437,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"804fc5a0ca4649a0b6dcec283810a540",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":562,
                  "y":614},
                "size":{
                  "width":437,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "ce194b8bf61742aea7475dad35671852":{
      "packageId":"ce194b8bf61742aea7475dad35671852",
      "type":"Axure:Master",
      "name":"头部框架",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1a8ee24928a94860889c9b047390fbf5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "opacity":"0.3",
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "size":{
                "width":1219,
                "height":1020},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f6d5da329001418bad0c45f297bae802",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "opacity":"0.3",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "size":{
                    "width":1219,
                    "height":1020},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/帮助/u41.png"}},
{
            "id":"2b596599a1a2483d84e1634a29aaddec",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":100},
              "size":{
                "width":1219,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/帮助/u43_line.png"}},
{
            "id":"06a4f09ba941472c84ee4ff1c0e16d57",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":855,
                "y":41},
              "size":{
                "width":203,
                "height":33}},
            "adaptiveStyles":{
}},
{
            "id":"2d1981c2bb3a4bbf98d29d5eb4a95f05",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":1058,
                "y":41},
              "size":{
                "width":38,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5c489b146ee44a60b5c40b1930b87fea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":1058,
                    "y":41},
                  "size":{
                    "width":38,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 支付查询",
                        "target":{
                          "targetType":"page",
                          "url":"支付查询.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u45.png"}},
{
            "id":"014e382808854576ac2a5acf6f38b3a2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":35,
                "y":20},
              "size":{
                "width":125,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f984bdbcccaa4abf9aac379604b9f79d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":35,
                    "y":20},
                  "size":{
                    "width":125,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/帮助/u47.png"}},
{
            "id":"bececc72e4864233aa56bbeb0067e5a5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":187,
                "y":37},
              "size":{
                "width":73,
                "height":43},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"665d02781c8d4d96a2ccf54f489faf8d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":187,
                    "y":37},
                  "size":{
                    "width":73,
                    "height":43},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页（控制台）",
                        "target":{
                          "targetType":"page",
                          "url":"首页（控制台）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u49.png"}},
{
            "id":"f7852bcc4c5a4921802ef94e6d848264",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":747,
                "y":40},
              "size":{
                "width":50,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da463ba93a7b4aec8326c16acf8da252",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":747,
                    "y":40},
                  "size":{
                    "width":50,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 帮助",
                        "target":{
                          "targetType":"page",
                          "url":"帮助.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u51.png"}},
{
            "id":"75f88fef079b47a09a5869837b83bf72",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1150,
                "y":30},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e78ad31a00344180aede2de040f4a718",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1150,
                    "y":30},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle 右侧边栏",
                        "objectsToFades":[{
                            "objectPath":["4c67581e5b9c41d2bed24e008a7eaf41"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u53.png"}},
{
            "id":"4c67581e5b9c41d2bed24e008a7eaf41",
            "label":"右侧边栏",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":1019,
                "y":105},
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"735f9a5466874ed29256b29c16e25def",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"718082d5a20f450d9c84bd2103096cf6",
                    "label":"",
                    "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":200,
                        "height":205}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b1ccd05daa8b42a3bfb0dbd5953ba989",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":200,
                            "height":205}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/帮助/u56.png"}},
{
                    "id":"9654f5fb424e410187206b64ad418cc3",
                    "label":"",
                    "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Negreta', 'Arial'",
                      "fontSize":"18px",
                      "fontWeight":"700",
                      "location":{
                        "x":12,
                        "y":26},
                      "size":{
                        "width":174,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"90a4735f986b4a6182c99e43389f1406",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Negreta', 'Arial'",
                          "fontSize":"18px",
                          "fontWeight":"700",
                          "location":{
                            "x":12,
                            "y":26},
                          "size":{
                            "width":174,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"b8ee2d90d06e4e538a40ae52e9ffc07e",
                    "label":"",
                    "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontSize":"16px",
                      "location":{
                        "x":41,
                        "y":73},
                      "size":{
                        "width":120,
                        "height":30},
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2d867bb2072e457e8c918d09ae3ddac6",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"16px",
                          "location":{
                            "x":41,
                            "y":73},
                          "size":{
                            "width":120,
                            "height":30},
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 基本信息（个人呈现）",
                                "target":{
                                  "targetType":"page",
                                  "url":"基本信息（个人呈现）.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/帮助/u60.png"}},
{
                    "id":"09c4937ed6844893bf4a19ae7fcb6637",
                    "label":"",
                    "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":75,
                        "y":128},
                      "size":{
                        "width":50,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"aa7310f048d8440d82e9fb58dffe258a",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":75,
                            "y":128},
                          "size":{
                            "width":50,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/帮助/u62.png"}}]}]},
{
            "id":"aaa8451fb0384ee78285cd70dbd3ac43",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":301,
                "y":41},
              "size":{
                "width":93,
                "height":40},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b70af69fec064387a9c5b3322fb2146a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":301,
                    "y":41},
                  "size":{
                    "width":93,
                    "height":40},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u64.png"}},
{
            "id":"861b3c8487af4ee0950251a48b2c6762",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":654,
                "y":46},
              "size":{
                "width":74,
                "height":30},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b711ccb25389454aa756897a2ff7e007",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":654,
                    "y":46},
                  "size":{
                    "width":74,
                    "height":30},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/帮助/u66.png"}}]}}},
  "objectPaths":{
    "ddbc506c4336476baf6b627cdb5b52ef":{
      "scriptId":"u0",
      "1a8ee24928a94860889c9b047390fbf5":{
        "scriptId":"u1"},
      "f6d5da329001418bad0c45f297bae802":{
        "scriptId":"u2"},
      "2b596599a1a2483d84e1634a29aaddec":{
        "scriptId":"u3"},
      "06a4f09ba941472c84ee4ff1c0e16d57":{
        "scriptId":"u4"},
      "2d1981c2bb3a4bbf98d29d5eb4a95f05":{
        "scriptId":"u5"},
      "5c489b146ee44a60b5c40b1930b87fea":{
        "scriptId":"u6"},
      "014e382808854576ac2a5acf6f38b3a2":{
        "scriptId":"u7"},
      "f984bdbcccaa4abf9aac379604b9f79d":{
        "scriptId":"u8"},
      "bececc72e4864233aa56bbeb0067e5a5":{
        "scriptId":"u9"},
      "665d02781c8d4d96a2ccf54f489faf8d":{
        "scriptId":"u10"},
      "f7852bcc4c5a4921802ef94e6d848264":{
        "scriptId":"u11"},
      "da463ba93a7b4aec8326c16acf8da252":{
        "scriptId":"u12"},
      "75f88fef079b47a09a5869837b83bf72":{
        "scriptId":"u13"},
      "e78ad31a00344180aede2de040f4a718":{
        "scriptId":"u14"},
      "4c67581e5b9c41d2bed24e008a7eaf41":{
        "scriptId":"u15"},
      "718082d5a20f450d9c84bd2103096cf6":{
        "scriptId":"u16"},
      "b1ccd05daa8b42a3bfb0dbd5953ba989":{
        "scriptId":"u17"},
      "9654f5fb424e410187206b64ad418cc3":{
        "scriptId":"u18"},
      "90a4735f986b4a6182c99e43389f1406":{
        "scriptId":"u19"},
      "b8ee2d90d06e4e538a40ae52e9ffc07e":{
        "scriptId":"u20"},
      "2d867bb2072e457e8c918d09ae3ddac6":{
        "scriptId":"u21"},
      "09c4937ed6844893bf4a19ae7fcb6637":{
        "scriptId":"u22"},
      "aa7310f048d8440d82e9fb58dffe258a":{
        "scriptId":"u23"},
      "aaa8451fb0384ee78285cd70dbd3ac43":{
        "scriptId":"u24"},
      "b70af69fec064387a9c5b3322fb2146a":{
        "scriptId":"u25"},
      "861b3c8487af4ee0950251a48b2c6762":{
        "scriptId":"u26"},
      "b711ccb25389454aa756897a2ff7e007":{
        "scriptId":"u27"}},
    "9e2dde39601e4ed28a04f4652d1ef6fb":{
      "scriptId":"u28"},
    "c6f3f53095b242d7a5594ac81536a8a3":{
      "scriptId":"u29"},
    "db67d30e7ddc487cbf816d0d1218f00d":{
      "scriptId":"u30"},
    "bde1dd9f6d05432e82230ea9ced644f5":{
      "scriptId":"u31"},
    "d0fa277a5e144467af313a11ea348be9":{
      "scriptId":"u32"},
    "0ee464e6f5f748b2903f3a29b0d381d5":{
      "scriptId":"u33"},
    "3c24281051d34beeb31ccf72be561a9d":{
      "scriptId":"u34"},
    "0c073910dab74db3a3e65bdaf8d0f1d2":{
      "scriptId":"u35"},
    "ecd70a2bd5b24354b073a6006e26d129":{
      "scriptId":"u36"},
    "fd3480c95ac0432d93689b63a850e63e":{
      "scriptId":"u37"},
    "f76a0690d0e64600a578c8cc46261507":{
      "scriptId":"u38"},
    "2af50576d94b4141a5f4a943dc529727":{
      "scriptId":"u39"},
    "2047dfe2c36e4acf9d91a065f9f21513":{
      "scriptId":"u40"},
    "98a1a6f70e744ab487bfbc058cc29a7b":{
      "scriptId":"u41"},
    "b81ec39b83794c09bd164bbbf960c1ad":{
      "scriptId":"u42"},
    "97ca3cd63c77438eba4bc68cffff9862":{
      "scriptId":"u43"},
    "7f01ee1aceba4754a682bb2d96b5acee":{
      "scriptId":"u44"},
    "f092b75bd2ec477aae624ccf09e31e95":{
      "scriptId":"u45"},
    "e6cd149408c34a8192e96ae1707b7a83":{
      "scriptId":"u46"},
    "a5f2959ca51140c9986ea742af0fb39c":{
      "scriptId":"u47"},
    "0a7a2c0fcc0f4c1886aa3aa9a8bc8c19":{
      "scriptId":"u48"},
    "d611449131cf4de4920768e50b3d26b1":{
      "scriptId":"u49"},
    "164d58598cec4a52a1d5257538e04707":{
      "scriptId":"u50"},
    "35789591b1324990a1c88b9237e5ef76":{
      "scriptId":"u51"},
    "c7c2bf0d3f534caebd284c0067366e03":{
      "scriptId":"u52"},
    "a03fa7fe2ec049bd8abdea3d519c92b1":{
      "scriptId":"u53"},
    "cd7675cd242e408583401cea69c3f7ec":{
      "scriptId":"u54"},
    "804fc5a0ca4649a0b6dcec283810a540":{
      "scriptId":"u55"}}});