$axure.loadCurrentPage({
  "url":"账户明细.html",
  "generationDate":new Date(1461745770654.46),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fead535167734a058ee516dda7b61276",
    "type":"Axure:Page",
    "name":"账户明细",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f5bdd0bbeba2423695ea0d5b6777b771",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":210,
              "y":210},
            "size":{
              "width":1219,
              "height":690},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82d7c5fb616049048f506e7d3b9fec98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.3",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":210,
                  "y":210},
                "size":{
                  "width":1219,
                  "height":690},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账户明细/u0.png"}},
{
          "id":"17b5fff2f9a04f9490ff98be9684fec8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":740,
              "y":253},
            "size":{
              "width":145,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca57e27de456421bab6dff499380d135",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":740,
                  "y":253},
                "size":{
                  "width":145,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f67a9ed8a94842acb56551fa351cf769",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":310},
            "size":{
              "width":1150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/批量复核_p2/u4_line.png"}},
{
          "id":"4f56df4a891f40c1b4b3f0b83f16d0fd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":245},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc577017955047958f91aa5a97215559",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":245},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/批量复核_p2/u5.png"}},
{
          "id":"680ecb87acc249d8b3b94605bbca93a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":246,
              "y":330},
            "size":{
              "width":1140,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da6fa562949549d99465a4f136af7926",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":246,
                  "y":330},
                "size":{
                  "width":1140,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付查询/u40.png"}},
{
          "id":"4b3afe274ffc495a83b8363f94075ea0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":292,
              "y":346},
            "size":{
              "width":151,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64326bcb44f542118195776962c06aa0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":292,
                  "y":346},
                "size":{
                  "width":151,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付查询/u42.png"}},
{
          "id":"17e854ebf79a41a98d411ac590bd795a",
          "label":"日期筛选",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":292,
              "y":379},
            "size":{
              "width":150,
              "height":50},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b14734ed6eb84377af3084d11fd937fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":292,
                  "y":379},
                "size":{
                  "width":150,
                  "height":50},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付查询/日期筛选_u94.png"}},
{
          "id":"f18d7f4e683e4fdca7d5d0ee41b15a71",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":346},
            "size":{
              "width":26,
              "height":31}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"fadeWidget",
                      "description":"Toggle 日期筛选",
                      "objectsToFades":[{
                          "objectPath":["17e854ebf79a41a98d411ac590bd795a"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"fd52d02890fe405aa470a3bb2779b197",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1296,
              "y":350},
            "size":{
              "width":63,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05dbed95967640baaa9fdd98b1dd9f01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1296,
                  "y":350},
                "size":{
                  "width":63,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付查询/u46.png"}},
{
          "id":"266df216996c48d885691d0ba8dc4a27",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1213,
              "y":350},
            "size":{
              "width":63,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cdb7c8d1548426c90db4d5ef697581b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1213,
                  "y":350},
                "size":{
                  "width":63,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付查询/u46.png"}},
{
          "id":"920fd085434040a8953df92f4eb02db6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":563,
              "y":344},
            "size":{
              "width":130,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"2fd9dc31c5b240e19f39190cd68bd224",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":786},
            "size":{
              "width":437,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6407f64c5e054d2d86b9043fb358682f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":786},
                "size":{
                  "width":437,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/删除提现记录/u16.png"}},
{
          "id":"4ff213dead724ad08349fab1bdb3ae44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":480,
              "y":352},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d71ee6ad39f4332b0bf4e17ad81190f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":480,
                  "y":352},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e144c7bcd2274c51847c02136e5efab6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":740,
              "y":348},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c616fb419a9a4943a245f43c16721fad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":740,
                  "y":348},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e44d85b108284ec6b54c7caeb9cdb7ac",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":348},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"772267d16c6d47af9d9e781a4decf942",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":980,
              "y":350},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b23edf0e734c40aaa75f81a3aa493a4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":980,
                  "y":350},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd84d45c1b4e42b0b371132d6646905b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":1080,
              "y":350},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"4666b05d493b4739a36fd48814e7ed46",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":246,
              "y":410},
            "size":{
              "width":1140,
              "height":330}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a0fef5efa224162ae6f81feecee9f24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":246,
                  "y":410},
                "size":{
                  "width":1140,
                  "height":330}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账户明细/u29.png"}},
{
          "id":"2cd888ac63ec4423a254f5619ea31b4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":1457,
              "y":210},
            "size":{
              "width":430,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7bb16a4c604432f9bc8059af78de45b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":1457,
                  "y":210},
                "size":{
                  "width":430,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u88.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f5bdd0bbeba2423695ea0d5b6777b771":{
      "scriptId":"u0"},
    "82d7c5fb616049048f506e7d3b9fec98":{
      "scriptId":"u1"},
    "17b5fff2f9a04f9490ff98be9684fec8":{
      "scriptId":"u2"},
    "ca57e27de456421bab6dff499380d135":{
      "scriptId":"u3"},
    "f67a9ed8a94842acb56551fa351cf769":{
      "scriptId":"u4"},
    "4f56df4a891f40c1b4b3f0b83f16d0fd":{
      "scriptId":"u5"},
    "dc577017955047958f91aa5a97215559":{
      "scriptId":"u6"},
    "680ecb87acc249d8b3b94605bbca93a5":{
      "scriptId":"u7"},
    "da6fa562949549d99465a4f136af7926":{
      "scriptId":"u8"},
    "4b3afe274ffc495a83b8363f94075ea0":{
      "scriptId":"u9"},
    "64326bcb44f542118195776962c06aa0":{
      "scriptId":"u10"},
    "17e854ebf79a41a98d411ac590bd795a":{
      "scriptId":"u11"},
    "b14734ed6eb84377af3084d11fd937fe":{
      "scriptId":"u12"},
    "f18d7f4e683e4fdca7d5d0ee41b15a71":{
      "scriptId":"u13"},
    "fd52d02890fe405aa470a3bb2779b197":{
      "scriptId":"u14"},
    "05dbed95967640baaa9fdd98b1dd9f01":{
      "scriptId":"u15"},
    "266df216996c48d885691d0ba8dc4a27":{
      "scriptId":"u16"},
    "8cdb7c8d1548426c90db4d5ef697581b":{
      "scriptId":"u17"},
    "920fd085434040a8953df92f4eb02db6":{
      "scriptId":"u18"},
    "2fd9dc31c5b240e19f39190cd68bd224":{
      "scriptId":"u19"},
    "6407f64c5e054d2d86b9043fb358682f":{
      "scriptId":"u20"},
    "4ff213dead724ad08349fab1bdb3ae44":{
      "scriptId":"u21"},
    "4d71ee6ad39f4332b0bf4e17ad81190f":{
      "scriptId":"u22"},
    "e144c7bcd2274c51847c02136e5efab6":{
      "scriptId":"u23"},
    "c616fb419a9a4943a245f43c16721fad":{
      "scriptId":"u24"},
    "e44d85b108284ec6b54c7caeb9cdb7ac":{
      "scriptId":"u25"},
    "772267d16c6d47af9d9e781a4decf942":{
      "scriptId":"u26"},
    "b23edf0e734c40aaa75f81a3aa493a4d":{
      "scriptId":"u27"},
    "cd84d45c1b4e42b0b371132d6646905b":{
      "scriptId":"u28"},
    "4666b05d493b4739a36fd48814e7ed46":{
      "scriptId":"u29"},
    "7a0fef5efa224162ae6f81feecee9f24":{
      "scriptId":"u30"},
    "2cd888ac63ec4423a254f5619ea31b4c":{
      "scriptId":"u31"},
    "d7bb16a4c604432f9bc8059af78de45b":{
      "scriptId":"u32"}}});