$axure.loadCurrentPage({
  "url":"提现.html",
  "generationDate":new Date(1461745769378.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"85b91fdb2c4e4f889480a3bd26452a12",
    "type":"Axure:Page",
    "name":"提现",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"356558fc9d0d41918cf05061daf5951f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":75},
            "size":{
              "width":1223,
              "height":1005}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7ad1e56d60e40f4af1b546aeed97f3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":75},
                "size":{
                  "width":1223,
                  "height":1005}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/未实名认证提醒/u0.jpg"}},
{
          "id":"8e002fdc3abb45ae9a49dcae4a415f03",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.4",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":110,
              "y":75},
            "size":{
              "width":1220,
              "height":1005}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"386fb7cc23394ba0aa68223709ae8798",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.4",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":110,
                  "y":75},
                "size":{
                  "width":1220,
                  "height":1005}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/未实名认证提醒/u9.png"}},
{
          "id":"48d6fdacbdcc49c9afaa26fa19ba8ccb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":360},
            "size":{
              "width":980,
              "height":340}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c370ccfed7844f60921deb9f492da703",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":360},
                "size":{
                  "width":980,
                  "height":340}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现/u4.png"}},
{
          "id":"8085f90ed58d42b184d0570457cbcbc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":280,
              "y":360},
            "size":{
              "width":980,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"816d45ad34544b2682547c64fe88bf06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":280,
                  "y":360},
                "size":{
                  "width":980,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现/u6.png"}},
{
          "id":"8503d38ee8c84d00bb6d97ba04424fe1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":336,
              "y":392},
            "size":{
              "width":169,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12a2b0d592f74ad39e9b0e0872662c42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":336,
                  "y":392},
                "size":{
                  "width":169,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8538ebf1f8c04440a05e0b72b4fe6f17",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":524,
              "y":398},
            "size":{
              "width":99,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30ec1e86bb7b41e1883943db2d06d388",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":524,
                  "y":398},
                "size":{
                  "width":99,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f3b3947505d46d484937dc382517e1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":1360,
              "y":90},
            "size":{
              "width":430,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f1a67393e3e4bc382b5574ff0c86583",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":1360,
                  "y":90},
                "size":{
                  "width":430,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u88.png"}},
{
          "id":"8862309f9b0d4550b47b7bc0bd88ccf3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":633,
              "y":400},
            "size":{
              "width":181,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d3bd68a473d4306a715cd1603d77a2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":633,
                  "y":400},
                "size":{
                  "width":181,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1674b1d3e4f44091a4dbcfae4d727b8b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1191,
              "y":380},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a16be1fec6148ecbddc35e3e6e3fad1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1191,
                  "y":380},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页（控制台）",
                      "target":{
                        "targetType":"page",
                        "url":"首页（控制台）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u74.png"}},
{
          "id":"5b5b7c9857c74ee9be9defe734d17455",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":443,
              "y":525},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5ddf0a9d2314bb780c51f55da5c9dfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":443,
                  "y":525},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b076b3df138c48c0a6c9ccf64a843c7d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":575,
              "y":525},
            "size":{
              "width":110,
              "height":34}},
          "adaptiveStyles":{
}},
{
          "id":"a8d93a44343645deac9dd41629676269",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":705,
              "y":530},
            "size":{
              "width":21,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3aa10680b37e4142a746d974b6268cef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":705,
                  "y":530},
                "size":{
                  "width":21,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a67951f496c94513b3bd5730d3e0d7b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":681,
              "y":599},
            "size":{
              "width":186,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f2f7edbc5b749d48f5715549f313d25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":681,
                  "y":599},
                "size":{
                  "width":186,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 单笔复核",
                      "target":{
                        "targetType":"page",
                        "url":"单笔复核.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/提现/u23.png"}},
{
          "id":"f59b9c533e4041a49ee2336385671484",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":765,
              "y":533},
            "size":{
              "width":361,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69ac7f523777471285ddf362519eeb88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":765,
                  "y":533},
                "size":{
                  "width":361,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37b7fb5545ef421dae42d59684c35e7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":569},
            "size":{
              "width":133,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22f8d4deb7d54ff1a525f9c4b6b8d961",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":593,
                  "y":569},
                "size":{
                  "width":133,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81bc7901d7d041c1a6d04dd43eb01739",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":575,
              "y":569},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96dbcf7fdff640e38bbd5788530d6d56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":575,
                  "y":569},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u69.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "356558fc9d0d41918cf05061daf5951f":{
      "scriptId":"u0"},
    "c7ad1e56d60e40f4af1b546aeed97f3a":{
      "scriptId":"u1"},
    "8e002fdc3abb45ae9a49dcae4a415f03":{
      "scriptId":"u2"},
    "386fb7cc23394ba0aa68223709ae8798":{
      "scriptId":"u3"},
    "48d6fdacbdcc49c9afaa26fa19ba8ccb":{
      "scriptId":"u4"},
    "c370ccfed7844f60921deb9f492da703":{
      "scriptId":"u5"},
    "8085f90ed58d42b184d0570457cbcbc3":{
      "scriptId":"u6"},
    "816d45ad34544b2682547c64fe88bf06":{
      "scriptId":"u7"},
    "8503d38ee8c84d00bb6d97ba04424fe1":{
      "scriptId":"u8"},
    "12a2b0d592f74ad39e9b0e0872662c42":{
      "scriptId":"u9"},
    "8538ebf1f8c04440a05e0b72b4fe6f17":{
      "scriptId":"u10"},
    "30ec1e86bb7b41e1883943db2d06d388":{
      "scriptId":"u11"},
    "5f3b3947505d46d484937dc382517e1e":{
      "scriptId":"u12"},
    "5f1a67393e3e4bc382b5574ff0c86583":{
      "scriptId":"u13"},
    "8862309f9b0d4550b47b7bc0bd88ccf3":{
      "scriptId":"u14"},
    "0d3bd68a473d4306a715cd1603d77a2e":{
      "scriptId":"u15"},
    "1674b1d3e4f44091a4dbcfae4d727b8b":{
      "scriptId":"u16"},
    "2a16be1fec6148ecbddc35e3e6e3fad1":{
      "scriptId":"u17"},
    "5b5b7c9857c74ee9be9defe734d17455":{
      "scriptId":"u18"},
    "f5ddf0a9d2314bb780c51f55da5c9dfe":{
      "scriptId":"u19"},
    "b076b3df138c48c0a6c9ccf64a843c7d":{
      "scriptId":"u20"},
    "a8d93a44343645deac9dd41629676269":{
      "scriptId":"u21"},
    "3aa10680b37e4142a746d974b6268cef":{
      "scriptId":"u22"},
    "a67951f496c94513b3bd5730d3e0d7b2":{
      "scriptId":"u23"},
    "1f2f7edbc5b749d48f5715549f313d25":{
      "scriptId":"u24"},
    "f59b9c533e4041a49ee2336385671484":{
      "scriptId":"u25"},
    "69ac7f523777471285ddf362519eeb88":{
      "scriptId":"u26"},
    "37b7fb5545ef421dae42d59684c35e7e":{
      "scriptId":"u27"},
    "22f8d4deb7d54ff1a525f9c4b6b8d961":{
      "scriptId":"u28"},
    "81bc7901d7d041c1a6d04dd43eb01739":{
      "scriptId":"u29"},
    "96dbcf7fdff640e38bbd5788530d6d56":{
      "scriptId":"u30"}}});