$axure.loadCurrentPage({
  "url":"商户管理-技术协议.html",
  "generationDate":new Date(1462860680864.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"21a59f8f1a1c4566a32e254e7f17d0be",
    "type":"Axure:Page",
    "name":"商户管理-技术协议",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c9387c04e6b047a1a3f70310329e8c89",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":200},
            "size":{
              "width":1226,
              "height":1010}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a83d6a0255fa448aa047a555eb61e231",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":200},
                "size":{
                  "width":1226,
                  "height":1010}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户管理-技术协议/u0.png"}},
{
          "id":"8890488781884c6ba5fd4c5d76acd2f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":772,
              "y":227},
            "size":{
              "width":145,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"284bd62d56e148168c6703cc65afbae1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":772,
                  "y":227},
                "size":{
                  "width":145,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83f4dec502a348e8baf41c9ffbdafe12",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":624,
              "y":1125},
            "size":{
              "width":298,
              "height":51},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2f9947b264a46f6b3a66eee39630bbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":624,
                  "y":1125},
                "size":{
                  "width":298,
                  "height":51},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商户签约-基本信息（个人）",
                      "target":{
                        "targetType":"page",
                        "url":"商户签约-基本信息（个人）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户管理-技术协议/u4.png"}},
{
          "id":"b633b28b10ee438f99a5c9429fab541a",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":422,
              "y":378},
            "size":{
              "width":915,
              "height":711}},
          "adaptiveStyles":{
}},
{
          "id":"46debbe0ae72492c86c5188883072bdb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":1530,
              "y":200},
            "size":{
              "width":430,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c2650dc65b047e584dedc70dd3e06a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":1530,
                  "y":200},
                "size":{
                  "width":430,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u89.png"}},
{
          "id":"20a6ce362a0e4e9295d40c18f5e62a7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":223,
              "y":668},
            "size":{
              "width":41,
              "height":42},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9aa8353a7bcf4a9dbcc7c58104f73a71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":223,
                  "y":668},
                "size":{
                  "width":41,
                  "height":42},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户管理-技术协议/u9.png"}},
{
          "id":"7540465983da4d78b00737c5dda776d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":272,
              "y":684},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f5577252b0d49f288f22b6d99cc7fd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":272,
                  "y":684},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be8aca718a3c433c9216d99d52e488a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":223,
              "y":980},
            "size":{
              "width":41,
              "height":36},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99664bc4a83644b3ba83c3b0ade1cea2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":223,
                  "y":980},
                "size":{
                  "width":41,
                  "height":36},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户管理-技术协议/u13.png"}},
{
          "id":"95d72d0906654ce983b775794f45e632",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":272,
              "y":992},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6fd1d010ce4408f88441f9b0d9d0caa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":272,
                  "y":992},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50702d5187fb499fa6146c470976b410",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":710},
            "size":{
              "width":10,
              "height":270}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户管理-技术协议/u17_line.png"}},
{
          "id":"bc010dfa4ab64ce1b94ffad43102848c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":272,
              "y":364},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d486bb6a3f94f179492f63493c23a5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":272,
                  "y":364},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e67a1c17af5849249644408f85254678",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":400},
            "size":{
              "width":10,
              "height":268}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户管理-技术协议/u20_line.png"}},
{
          "id":"f3480e9a92fb4b9c9041b5ef036366c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":223,
              "y":358},
            "size":{
              "width":41,
              "height":42},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e351a1bc3ee4778bef89f7c83583ec9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":223,
                  "y":358},
                "size":{
                  "width":41,
                  "height":42},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户管理-技术协议/u21.png"}},
{
          "id":"ae78fb243ac1454cb2aaa8a4af36d78e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":220},
            "size":{
              "width":126,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e95f4da790447dfaa02a01c5333286d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":235,
                  "y":220},
                "size":{
                  "width":126,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户管理-技术协议/u23.png"}},
{
          "id":"aab801fc85934098bf615c77edb3571f",
          "label":"右侧边栏",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":1225,
              "y":300},
            "size":{
              "width":200,
              "height":205}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"86c65c7a728a4551bed5cb67c49c9307",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0f30b49ede0d43dd9b124baf398adc3e",
                  "label":"",
                  "parentDynamicPanel":"aab801fc85934098bf615c77edb3571f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":205}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d9dc442c2ed94c1ab5419dd4ed615a8e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aab801fc85934098bf615c77edb3571f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":205}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/帮助/u56.png"}},
{
                  "id":"fc3c228b71d44202af65c6b1314588a0",
                  "label":"",
                  "parentDynamicPanel":"aab801fc85934098bf615c77edb3571f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"700",
                    "location":{
                      "x":12,
                      "y":44},
                    "size":{
                      "width":174,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"227e74f77d4a4dedb0c62aa0f8c15333",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aab801fc85934098bf615c77edb3571f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"700",
                        "location":{
                          "x":12,
                          "y":44},
                        "size":{
                          "width":174,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"78245df2683e4acdbcb882e459cbb42f",
                  "label":"",
                  "parentDynamicPanel":"aab801fc85934098bf615c77edb3571f",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":75,
                      "y":120},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"be638b426843407db14c118a394a9eeb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aab801fc85934098bf615c77edb3571f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":75,
                          "y":120},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/帮助/u62.png"}}]}]},
{
          "id":"2291735104fb4d9abbb6dce887148085",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1356,
              "y":230},
            "size":{
              "width":51,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5242dae527f47a88bcca444a6b73d50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1356,
                  "y":230},
                "size":{
                  "width":51,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle 右侧边栏",
                      "objectsToFades":[{
                          "objectPath":["aab801fc85934098bf615c77edb3571f"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u53.png"}},
{
          "id":"bb63c14343cb4710a8b54d30438bb554",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":300},
            "size":{
              "width":1219,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/帮助/u43_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c9387c04e6b047a1a3f70310329e8c89":{
      "scriptId":"u0"},
    "a83d6a0255fa448aa047a555eb61e231":{
      "scriptId":"u1"},
    "8890488781884c6ba5fd4c5d76acd2f7":{
      "scriptId":"u2"},
    "284bd62d56e148168c6703cc65afbae1":{
      "scriptId":"u3"},
    "83f4dec502a348e8baf41c9ffbdafe12":{
      "scriptId":"u4"},
    "b2f9947b264a46f6b3a66eee39630bbc":{
      "scriptId":"u5"},
    "b633b28b10ee438f99a5c9429fab541a":{
      "scriptId":"u6"},
    "46debbe0ae72492c86c5188883072bdb":{
      "scriptId":"u7"},
    "2c2650dc65b047e584dedc70dd3e06a3":{
      "scriptId":"u8"},
    "20a6ce362a0e4e9295d40c18f5e62a7d":{
      "scriptId":"u9"},
    "9aa8353a7bcf4a9dbcc7c58104f73a71":{
      "scriptId":"u10"},
    "7540465983da4d78b00737c5dda776d1":{
      "scriptId":"u11"},
    "2f5577252b0d49f288f22b6d99cc7fd7":{
      "scriptId":"u12"},
    "be8aca718a3c433c9216d99d52e488a6":{
      "scriptId":"u13"},
    "99664bc4a83644b3ba83c3b0ade1cea2":{
      "scriptId":"u14"},
    "95d72d0906654ce983b775794f45e632":{
      "scriptId":"u15"},
    "b6fd1d010ce4408f88441f9b0d9d0caa":{
      "scriptId":"u16"},
    "50702d5187fb499fa6146c470976b410":{
      "scriptId":"u17"},
    "bc010dfa4ab64ce1b94ffad43102848c":{
      "scriptId":"u18"},
    "2d486bb6a3f94f179492f63493c23a5d":{
      "scriptId":"u19"},
    "e67a1c17af5849249644408f85254678":{
      "scriptId":"u20"},
    "f3480e9a92fb4b9c9041b5ef036366c8":{
      "scriptId":"u21"},
    "1e351a1bc3ee4778bef89f7c83583ec9":{
      "scriptId":"u22"},
    "ae78fb243ac1454cb2aaa8a4af36d78e":{
      "scriptId":"u23"},
    "6e95f4da790447dfaa02a01c5333286d":{
      "scriptId":"u24"},
    "aab801fc85934098bf615c77edb3571f":{
      "scriptId":"u25"},
    "0f30b49ede0d43dd9b124baf398adc3e":{
      "scriptId":"u26"},
    "d9dc442c2ed94c1ab5419dd4ed615a8e":{
      "scriptId":"u27"},
    "fc3c228b71d44202af65c6b1314588a0":{
      "scriptId":"u28"},
    "227e74f77d4a4dedb0c62aa0f8c15333":{
      "scriptId":"u29"},
    "78245df2683e4acdbcb882e459cbb42f":{
      "scriptId":"u30"},
    "be638b426843407db14c118a394a9eeb":{
      "scriptId":"u31"},
    "2291735104fb4d9abbb6dce887148085":{
      "scriptId":"u32"},
    "f5242dae527f47a88bcca444a6b73d50":{
      "scriptId":"u33"},
    "bb63c14343cb4710a8b54d30438bb554":{
      "scriptId":"u34"}}});