$axure.loadCurrentPage({
  "url":"提交订单（商户页）.html",
  "generationDate":new Date(1469168368779.61),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c960990f4e3347388ee068c40476f9c3",
    "type":"Axure:Page",
    "name":"提交订单（商户页）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5369962d381b4a71a73c968f6d6f4c12",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":124},
            "size":{
              "width":66,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46579ebe68b6485e85576248d2731258",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":124},
                "size":{
                  "width":66,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb7ad29082654511a37bfbaa88d3728b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":199,
              "y":118},
            "size":{
              "width":406,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e35da76561b745c8b2d0d5dc2ad3f5b3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":246},
            "size":{
              "width":406,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d3fe0ff03d63441fb12dab0b453128b1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":315},
            "size":{
              "width":406,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0f09d3170dc9481b92e6e4357f16b552",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":375},
            "size":{
              "width":406,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bf692446d1614c38a63f0bba0f803b94",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":30},
            "size":{
              "width":121,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54e5b2bdbf484a9bb26eaa6ddda9611e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":30},
                "size":{
                  "width":121,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e04a897901dc43c6bb33cfc972fae9ed",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":197,
              "y":440},
            "size":{
              "width":103,
              "height":55}},
          "adaptiveStyles":{
}},
{
          "id":"c91bb85fc8d744b58d878fff9541ac26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":756,
              "y":177},
            "size":{
              "width":307,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c0dbae392fd4bffa5c7f71ebb3c635b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":756,
                  "y":177},
                "size":{
                  "width":307,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8b6dbeaf0a14af89bd7407a6d145535",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":184},
            "size":{
              "width":170,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"604f6b8aa7fb49a899148fd1714a7dfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":389,
              "y":188},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"198c690d547d488eacf97fc0d777b720",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":389,
                  "y":188},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "5369962d381b4a71a73c968f6d6f4c12":{
      "scriptId":"u0"},
    "46579ebe68b6485e85576248d2731258":{
      "scriptId":"u1"},
    "eb7ad29082654511a37bfbaa88d3728b":{
      "scriptId":"u2"},
    "e35da76561b745c8b2d0d5dc2ad3f5b3":{
      "scriptId":"u3"},
    "d3fe0ff03d63441fb12dab0b453128b1":{
      "scriptId":"u4"},
    "0f09d3170dc9481b92e6e4357f16b552":{
      "scriptId":"u5"},
    "bf692446d1614c38a63f0bba0f803b94":{
      "scriptId":"u6"},
    "54e5b2bdbf484a9bb26eaa6ddda9611e":{
      "scriptId":"u7"},
    "e04a897901dc43c6bb33cfc972fae9ed":{
      "scriptId":"u8"},
    "c91bb85fc8d744b58d878fff9541ac26":{
      "scriptId":"u9"},
    "5c0dbae392fd4bffa5c7f71ebb3c635b":{
      "scriptId":"u10"},
    "d8b6dbeaf0a14af89bd7407a6d145535":{
      "scriptId":"u11"},
    "604f6b8aa7fb49a899148fd1714a7dfe":{
      "scriptId":"u12"},
    "198c690d547d488eacf97fc0d777b720":{
      "scriptId":"u13"}}});