$axure.loadCurrentPage({
  "url":"基本信息（个人呈现）.html",
  "generationDate":new Date(1458553411036.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3e4613d5a8424704adfb9c2779097d1d",
    "type":"Axure:Page",
    "name":"基本信息（个人呈现）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"73c6f94c75c74d489f456974e3f59461",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":200,
              "y":200},
            "size":{
              "width":1219,
              "height":890},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93d9a3d3da3140a39cfa8db47653e47b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.3",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":200,
                  "y":200},
                "size":{
                  "width":1219,
                  "height":890},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/大入口/u0.png"}},
{
          "id":"d93c5b4321e54dc0bf295a869905f179",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":300},
            "size":{
              "width":1219,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/帮助/u43_line.png"}},
{
          "id":"0e5413fe63b94fdbaf0af013a997e81f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":220},
            "size":{
              "width":125,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"628c90478bcf44318e8e904e6949b1f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":235,
                  "y":220},
                "size":{
                  "width":125,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u47.png"}},
{
          "id":"78675f319bc54510a2aebd710ed91b3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":387,
              "y":237},
            "size":{
              "width":113,
              "height":43},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0aeb0e7cc87453e8e93bf05bc08722d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":387,
                  "y":237},
                "size":{
                  "width":113,
                  "height":43},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页（控制台）",
                      "target":{
                        "targetType":"page",
                        "url":"首页（控制台）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u49.png"}},
{
          "id":"7117add7a1e04b75bc7c32feab25dca0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":521,
              "y":237},
            "size":{
              "width":113,
              "height":43},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e348f5f019d48eb96d7835eab95563e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":521,
                  "y":237},
                "size":{
                  "width":113,
                  "height":43},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 渠道管理",
                      "target":{
                        "targetType":"page",
                        "url":"渠道管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u49.png"}},
{
          "id":"363febe1550b40509a511f768ec3cedd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":655,
              "y":237},
            "size":{
              "width":113,
              "height":43},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9030b1894bf45e48e1c3e52ac4e6a7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":655,
                  "y":237},
                "size":{
                  "width":113,
                  "height":43},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 提现",
                      "target":{
                        "targetType":"page",
                        "url":"提现.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u49.png"}},
{
          "id":"65ac131267eb4a1aba6df11d83135a67",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1350,
              "y":230},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72de8bcc5ea749128a4d0b4e3470c7fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1350,
                  "y":230},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u57.png"}},
{
          "id":"01855e5bc2ac4692abcf0e5acf5b7492",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":306},
            "size":{
              "width":210,
              "height":784}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8098a3ae54cf495ba2f2176dc0e031ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":306},
                "size":{
                  "width":210,
                  "height":784}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u13.png"}},
{
          "id":"1ab84e74e91843cbaa08f63df87b271c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":218,
              "y":352},
            "size":{
              "width":174,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54675615c98a430ca91f16db19b32c03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":218,
                  "y":352},
                "size":{
                  "width":174,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e1e4af5e02b47a4bbc39dc021b6ee34",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":247,
              "y":398},
            "size":{
              "width":120,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54c4909bd74e4b6193296ce54dc9e178",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":247,
                  "y":398},
                "size":{
                  "width":120,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u64.png"}},
{
          "id":"c06cadd47c2d4000b7f7a32034f36e18",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":460},
            "size":{
              "width":210,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息（个人呈现）/u19_line.png"}},
{
          "id":"312926a47a4a4dcba56a6e802d5df984",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":205,
              "y":524},
            "size":{
              "width":200,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息（个人呈现）/u20_line.png"}},
{
          "id":"dba4558858eb49abaffa6a054f8a0369",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":480},
            "size":{
              "width":42,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbf5afce2c12487397bd7659e9737e91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":218,
                  "y":480},
                "size":{
                  "width":42,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u21.png"}},
{
          "id":"a9e6f094be044182ab2884bb1a787b76",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":272,
              "y":492},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ac90e943c0c4e879b15208f35bd37e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":272,
                  "y":492},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02f9d682716d449789fed675a0fe9583",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":366,
              "y":492},
            "size":{
              "width":32,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0c848d12dfb44b6bb404089d6d156a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":366,
                  "y":492},
                "size":{
                  "width":32,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u25.png"}},
{
          "id":"b684c1a092a541cfa36a9ad6a78c24c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":434,
              "y":328},
            "size":{
              "width":946,
              "height":752}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"633c8e6f85b94c2683557beb3b8ee6e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":434,
                  "y":328},
                "size":{
                  "width":946,
                  "height":752}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u27.png"}},
{
          "id":"a96647cf95bf414ba88c7c78069b3f2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":434,
              "y":328},
            "size":{
              "width":946,
              "height":92}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f946ded63e846469ceff17d86326085",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":434,
                  "y":328},
                "size":{
                  "width":946,
                  "height":92}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u29.png"}},
{
          "id":"69a0e62f701d4b5882da1ad3718a903e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":475,
              "y":364},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3c192efb22a4c3487196510bea966e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":475,
                  "y":364},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"054c5db3f4f64786b42a2af62d932989",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":955,
              "y":440},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2ba1a1b5d11463d8c4327a077d6f71f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":955,
                  "y":440},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c79837f102364d998dac9752d49ffd46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":496,
              "y":440},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a83b678a72fa447983da63c8be09c054",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":496,
                  "y":440},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e328195f08e49d8bad018b6b30190e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":513,
              "y":497},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1884ef86bd4e40d29fe5de943cdbeb46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":513,
                  "y":497},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72cff80f16ab467686ebb6e5bef1e191",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":961,
              "y":497},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38149476b8ee4a4d89dbc54dd9c403cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":961,
                  "y":497},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf3af86c138045fab4579382eec34d38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":474,
              "y":586},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f4d5f1da7124538a5da9964595581e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":474,
                  "y":586},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c4a04e2c6ff4138928626406adcca72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":958,
              "y":591},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d15e93f51b04e86af63fc0e800ad62d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":958,
                  "y":591},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"783e115e5bba4a96a7ba02bf613dceb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":521,
              "y":644},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f93768670c14489a7d31516d4fb916f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":521,
                  "y":644},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e4e816191fd4c8ebbc2d7122e0ad344",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":995,
              "y":644},
            "size":{
              "width":29,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b3868493efe430ea29a81eccadc9f5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":995,
                  "y":644},
                "size":{
                  "width":29,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1763ee89c0b4d7db5c1bb1e5907eeb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":486,
              "y":704},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f8f63e6f47f40188254363ddca65b7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":486,
                  "y":704},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44515a3675f1414cb7e90ab5718b7650",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":486,
              "y":786},
            "size":{
              "width":838,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户签约-基本信息（个人）/u35_line.png"}},
{
          "id":"c41dd45f91944da69e99809fe96117f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":485,
              "y":837},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"decc05dac7094d82aed368656db645f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":485,
                  "y":837},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a729b2a921b942ea922f38ce847900cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":605,
              "y":1007},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dde0e4564b041ccb55a87652bd67a07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":605,
                  "y":1007},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebaaf72c2e694a028c6872805a038b2c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":586,
              "y":886},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a518d321b7e1442d972ddf2b775d3b8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":586,
                  "y":886},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u43.jpg"}},
{
          "id":"0efc385913bd4d23969fd2d4e66e57d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":873,
              "y":882},
            "size":{
              "width":110,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ceb34110389e4398ac59b91456ec7c2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":873,
                  "y":882},
                "size":{
                  "width":110,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u47.png"}},
{
          "id":"43330ed3472b41898197626ae04b8642",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":874,
              "y":1007},
            "size":{
              "width":113,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"517496a710454ade97d5f384af3a01e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":874,
                  "y":1007},
                "size":{
                  "width":113,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0d30dee27ca4c2c87dbbbb84a09b430",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1132,
              "y":884},
            "size":{
              "width":110,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a00d340ce1a64c9b961721ea8ada3045",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1132,
                  "y":884},
                "size":{
                  "width":110,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u47.png"}},
{
          "id":"396d0247c8004d6c8960b1f936256f82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1133,
              "y":1009},
            "size":{
              "width":113,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6a298d3497c4f5bbe2247137ec21845",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1133,
                  "y":1009},
                "size":{
                  "width":113,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9fc431fd676425b86f64442227c0236",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":474,
              "y":544},
            "size":{
              "width":838,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户签约-基本信息（个人）/u35_line.png"}},
{
          "id":"d108b01da6c64dccb7d6c1b00b139700",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":606,
              "y":443},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a45506d835d41f4bead8da850b9354d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":606,
                  "y":443},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00fe1b772c2649fd8ab3ef354a649e93",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1070,
              "y":443},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29313c7bfba147ac9a0ebaf6c919ab87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1070,
                  "y":443},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57fe353fde9944ea961ccdda69f6b279",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":606,
              "y":500},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12a65b1340134fd3814ccbb7110c2a62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":606,
                  "y":500},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb9fa0bff94945838ed1a31bcd240572",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1070,
              "y":500},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4ff56ded0be4a008f3a562d541d9aeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1070,
                  "y":500},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0d2631221f948d6b15058ceb31a617d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":606,
              "y":586},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fac8cd4ef9c43068a562e40aeeb95db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":606,
                  "y":586},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f6ea554a32d4097a00cfd65617d3aae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1070,
              "y":594},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3a1204361124906ab40f8698e743409",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1070,
                  "y":594},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f81ec6be9204c419a018b2e19e56d6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":606,
              "y":647},
            "size":{
              "width":132,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f26f97872169436ba04fa020a2e3beb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":606,
                  "y":647},
                "size":{
                  "width":132,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2d7fe3e38a64d7c90f91084877bca00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1070,
              "y":647},
            "size":{
              "width":82,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"830d4b5ced98463ba4b4347768412931",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1070,
                  "y":647},
                "size":{
                  "width":82,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e5157ba0ad14c4d98bec8224ba860d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":606,
              "y":840},
            "size":{
              "width":171,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b70e394f5b4f4aa685d0b1c50f4761d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":606,
                  "y":840},
                "size":{
                  "width":171,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac4a93d6361149d6a7f0a63a65c32ee2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1260,
              "y":364},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3182a47acaf0454cb173a6373d7153f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1260,
                  "y":364},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 基本信息（个人修改）",
                      "target":{
                        "targetType":"page",
                        "url":"基本信息（个人修改）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/基本信息（个人呈现）/u85.png"}},
{
          "id":"fd4153e218c54488bad6b0ab04e5414d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":601,
              "y":707},
            "size":{
              "width":257,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2af56a590a39499885120b4f4d40608c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":601,
                  "y":707},
                "size":{
                  "width":257,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2abdb0ebf99a4fb3826eb24a7b09c223",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":205,
              "y":605},
            "size":{
              "width":200,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息（个人呈现）/u20_line.png"}},
{
          "id":"0a1183953c43474c853fda4693705cc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":561},
            "size":{
              "width":42,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06f04a866cb949c1b1e0cd9110b1831a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":218,
                  "y":561},
                "size":{
                  "width":42,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u21.png"}},
{
          "id":"75a41293a8b6423ea987c0efef93be86",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":272,
              "y":573},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6417ab00cc2443489da51234270ab22c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":272,
                  "y":573},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d82813efbdf548dca81d62852d069b3a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":366,
              "y":573},
            "size":{
              "width":32,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a337546282b42cabfac9d25ea28bd8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":366,
                  "y":573},
                "size":{
                  "width":32,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u25.png"}},
{
          "id":"fa6ce49fe1f34fac9b4c26f7d629a177",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":689},
            "size":{
              "width":200,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息（个人呈现）/u20_line.png"}},
{
          "id":"34e18a4e43aa4163a53f42bfc337bc31",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":217,
              "y":645},
            "size":{
              "width":42,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d808f7a84044365b67960fedd2b95cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":217,
                  "y":645},
                "size":{
                  "width":42,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u21.png"}},
{
          "id":"095e562d7b82438d917f37f4d9dd0a93",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":271,
              "y":657},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5b15a0ac51f45aebcfd238b3c63926e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":271,
                  "y":657},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e656a7e3ea4842828dc0af814d20dbb9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":657},
            "size":{
              "width":32,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"036623de81e647b89e8ec6c58ad4bb16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":365,
                  "y":657},
                "size":{
                  "width":32,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u25.png"}},
{
          "id":"497177a2e614430da8e912cc46f23429",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":207,
              "y":768},
            "size":{
              "width":200,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息（个人呈现）/u20_line.png"}},
{
          "id":"836db493d27d4f61aba6f46830392325",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":724},
            "size":{
              "width":42,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9e473ae81004eaea122f4d237cff66f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":724},
                "size":{
                  "width":42,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u21.png"}},
{
          "id":"d364964749214754a3da7481e1fa023b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":274,
              "y":736},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e23a74b693da495bbfedbd0e5a157c6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":274,
                  "y":736},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e56a11872c6f49f1a23281f77c14bacf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":368,
              "y":736},
            "size":{
              "width":32,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00e2dbf498ad42de9a6bb96e9555cc93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":368,
                  "y":736},
                "size":{
                  "width":32,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u25.png"}},
{
          "id":"5a6db17541da41e68925fc98e332ea3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":1470,
              "y":230},
            "size":{
              "width":430,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c27fc16283e46b39c9f8fcfd90cf440",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":1470,
                  "y":230},
                "size":{
                  "width":430,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u88.png"}},
{
          "id":"73ef90d05b8640769bea450b410fbaea",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":475},
            "size":{
              "width":188,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 基本信息（个人呈现）",
                      "target":{
                        "targetType":"page",
                        "url":"基本信息（个人呈现）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"4f69a17a2b674ee0a3643999605e82b1",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":555},
            "size":{
              "width":188,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 结算信息",
                      "target":{
                        "targetType":"page",
                        "url":"结算信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"2f473b00cfcb4f9183e5f1793b1db3d3",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":639},
            "size":{
              "width":188,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 密码管理",
                      "target":{
                        "targetType":"page",
                        "url":"密码管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9354d9cd138e4615abaddab5be385653",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":212.5,
              "y":720.5},
            "size":{
              "width":188,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 签约协议",
                      "target":{
                        "targetType":"page",
                        "url":"签约协议.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "73c6f94c75c74d489f456974e3f59461":{
      "scriptId":"u0"},
    "93d9a3d3da3140a39cfa8db47653e47b":{
      "scriptId":"u1"},
    "d93c5b4321e54dc0bf295a869905f179":{
      "scriptId":"u2"},
    "0e5413fe63b94fdbaf0af013a997e81f":{
      "scriptId":"u3"},
    "628c90478bcf44318e8e904e6949b1f2":{
      "scriptId":"u4"},
    "78675f319bc54510a2aebd710ed91b3b":{
      "scriptId":"u5"},
    "b0aeb0e7cc87453e8e93bf05bc08722d":{
      "scriptId":"u6"},
    "7117add7a1e04b75bc7c32feab25dca0":{
      "scriptId":"u7"},
    "3e348f5f019d48eb96d7835eab95563e":{
      "scriptId":"u8"},
    "363febe1550b40509a511f768ec3cedd":{
      "scriptId":"u9"},
    "e9030b1894bf45e48e1c3e52ac4e6a7a":{
      "scriptId":"u10"},
    "65ac131267eb4a1aba6df11d83135a67":{
      "scriptId":"u11"},
    "72de8bcc5ea749128a4d0b4e3470c7fb":{
      "scriptId":"u12"},
    "01855e5bc2ac4692abcf0e5acf5b7492":{
      "scriptId":"u13"},
    "8098a3ae54cf495ba2f2176dc0e031ed":{
      "scriptId":"u14"},
    "1ab84e74e91843cbaa08f63df87b271c":{
      "scriptId":"u15"},
    "54675615c98a430ca91f16db19b32c03":{
      "scriptId":"u16"},
    "3e1e4af5e02b47a4bbc39dc021b6ee34":{
      "scriptId":"u17"},
    "54c4909bd74e4b6193296ce54dc9e178":{
      "scriptId":"u18"},
    "c06cadd47c2d4000b7f7a32034f36e18":{
      "scriptId":"u19"},
    "312926a47a4a4dcba56a6e802d5df984":{
      "scriptId":"u20"},
    "dba4558858eb49abaffa6a054f8a0369":{
      "scriptId":"u21"},
    "dbf5afce2c12487397bd7659e9737e91":{
      "scriptId":"u22"},
    "a9e6f094be044182ab2884bb1a787b76":{
      "scriptId":"u23"},
    "3ac90e943c0c4e879b15208f35bd37e7":{
      "scriptId":"u24"},
    "02f9d682716d449789fed675a0fe9583":{
      "scriptId":"u25"},
    "b0c848d12dfb44b6bb404089d6d156a8":{
      "scriptId":"u26"},
    "b684c1a092a541cfa36a9ad6a78c24c2":{
      "scriptId":"u27"},
    "633c8e6f85b94c2683557beb3b8ee6e6":{
      "scriptId":"u28"},
    "a96647cf95bf414ba88c7c78069b3f2b":{
      "scriptId":"u29"},
    "1f946ded63e846469ceff17d86326085":{
      "scriptId":"u30"},
    "69a0e62f701d4b5882da1ad3718a903e":{
      "scriptId":"u31"},
    "f3c192efb22a4c3487196510bea966e6":{
      "scriptId":"u32"},
    "054c5db3f4f64786b42a2af62d932989":{
      "scriptId":"u33"},
    "a2ba1a1b5d11463d8c4327a077d6f71f":{
      "scriptId":"u34"},
    "c79837f102364d998dac9752d49ffd46":{
      "scriptId":"u35"},
    "a83b678a72fa447983da63c8be09c054":{
      "scriptId":"u36"},
    "4e328195f08e49d8bad018b6b30190e7":{
      "scriptId":"u37"},
    "1884ef86bd4e40d29fe5de943cdbeb46":{
      "scriptId":"u38"},
    "72cff80f16ab467686ebb6e5bef1e191":{
      "scriptId":"u39"},
    "38149476b8ee4a4d89dbc54dd9c403cb":{
      "scriptId":"u40"},
    "bf3af86c138045fab4579382eec34d38":{
      "scriptId":"u41"},
    "0f4d5f1da7124538a5da9964595581e5":{
      "scriptId":"u42"},
    "1c4a04e2c6ff4138928626406adcca72":{
      "scriptId":"u43"},
    "0d15e93f51b04e86af63fc0e800ad62d":{
      "scriptId":"u44"},
    "783e115e5bba4a96a7ba02bf613dceb5":{
      "scriptId":"u45"},
    "6f93768670c14489a7d31516d4fb916f":{
      "scriptId":"u46"},
    "0e4e816191fd4c8ebbc2d7122e0ad344":{
      "scriptId":"u47"},
    "1b3868493efe430ea29a81eccadc9f5b":{
      "scriptId":"u48"},
    "e1763ee89c0b4d7db5c1bb1e5907eeb5":{
      "scriptId":"u49"},
    "0f8f63e6f47f40188254363ddca65b7b":{
      "scriptId":"u50"},
    "44515a3675f1414cb7e90ab5718b7650":{
      "scriptId":"u51"},
    "c41dd45f91944da69e99809fe96117f4":{
      "scriptId":"u52"},
    "decc05dac7094d82aed368656db645f7":{
      "scriptId":"u53"},
    "a729b2a921b942ea922f38ce847900cf":{
      "scriptId":"u54"},
    "0dde0e4564b041ccb55a87652bd67a07":{
      "scriptId":"u55"},
    "ebaaf72c2e694a028c6872805a038b2c":{
      "scriptId":"u56"},
    "a518d321b7e1442d972ddf2b775d3b8b":{
      "scriptId":"u57"},
    "0efc385913bd4d23969fd2d4e66e57d2":{
      "scriptId":"u58"},
    "ceb34110389e4398ac59b91456ec7c2b":{
      "scriptId":"u59"},
    "43330ed3472b41898197626ae04b8642":{
      "scriptId":"u60"},
    "517496a710454ade97d5f384af3a01e0":{
      "scriptId":"u61"},
    "e0d30dee27ca4c2c87dbbbb84a09b430":{
      "scriptId":"u62"},
    "a00d340ce1a64c9b961721ea8ada3045":{
      "scriptId":"u63"},
    "396d0247c8004d6c8960b1f936256f82":{
      "scriptId":"u64"},
    "f6a298d3497c4f5bbe2247137ec21845":{
      "scriptId":"u65"},
    "e9fc431fd676425b86f64442227c0236":{
      "scriptId":"u66"},
    "d108b01da6c64dccb7d6c1b00b139700":{
      "scriptId":"u67"},
    "9a45506d835d41f4bead8da850b9354d":{
      "scriptId":"u68"},
    "00fe1b772c2649fd8ab3ef354a649e93":{
      "scriptId":"u69"},
    "29313c7bfba147ac9a0ebaf6c919ab87":{
      "scriptId":"u70"},
    "57fe353fde9944ea961ccdda69f6b279":{
      "scriptId":"u71"},
    "12a65b1340134fd3814ccbb7110c2a62":{
      "scriptId":"u72"},
    "fb9fa0bff94945838ed1a31bcd240572":{
      "scriptId":"u73"},
    "b4ff56ded0be4a008f3a562d541d9aeb":{
      "scriptId":"u74"},
    "e0d2631221f948d6b15058ceb31a617d":{
      "scriptId":"u75"},
    "9fac8cd4ef9c43068a562e40aeeb95db":{
      "scriptId":"u76"},
    "6f6ea554a32d4097a00cfd65617d3aae":{
      "scriptId":"u77"},
    "c3a1204361124906ab40f8698e743409":{
      "scriptId":"u78"},
    "0f81ec6be9204c419a018b2e19e56d6d":{
      "scriptId":"u79"},
    "f26f97872169436ba04fa020a2e3beb6":{
      "scriptId":"u80"},
    "b2d7fe3e38a64d7c90f91084877bca00":{
      "scriptId":"u81"},
    "830d4b5ced98463ba4b4347768412931":{
      "scriptId":"u82"},
    "0e5157ba0ad14c4d98bec8224ba860d7":{
      "scriptId":"u83"},
    "b70e394f5b4f4aa685d0b1c50f4761d6":{
      "scriptId":"u84"},
    "ac4a93d6361149d6a7f0a63a65c32ee2":{
      "scriptId":"u85"},
    "3182a47acaf0454cb173a6373d7153f4":{
      "scriptId":"u86"},
    "fd4153e218c54488bad6b0ab04e5414d":{
      "scriptId":"u87"},
    "2af56a590a39499885120b4f4d40608c":{
      "scriptId":"u88"},
    "2abdb0ebf99a4fb3826eb24a7b09c223":{
      "scriptId":"u89"},
    "0a1183953c43474c853fda4693705cc1":{
      "scriptId":"u90"},
    "06f04a866cb949c1b1e0cd9110b1831a":{
      "scriptId":"u91"},
    "75a41293a8b6423ea987c0efef93be86":{
      "scriptId":"u92"},
    "6417ab00cc2443489da51234270ab22c":{
      "scriptId":"u93"},
    "d82813efbdf548dca81d62852d069b3a":{
      "scriptId":"u94"},
    "3a337546282b42cabfac9d25ea28bd8d":{
      "scriptId":"u95"},
    "fa6ce49fe1f34fac9b4c26f7d629a177":{
      "scriptId":"u96"},
    "34e18a4e43aa4163a53f42bfc337bc31":{
      "scriptId":"u97"},
    "2d808f7a84044365b67960fedd2b95cd":{
      "scriptId":"u98"},
    "095e562d7b82438d917f37f4d9dd0a93":{
      "scriptId":"u99"},
    "d5b15a0ac51f45aebcfd238b3c63926e":{
      "scriptId":"u100"},
    "e656a7e3ea4842828dc0af814d20dbb9":{
      "scriptId":"u101"},
    "036623de81e647b89e8ec6c58ad4bb16":{
      "scriptId":"u102"},
    "497177a2e614430da8e912cc46f23429":{
      "scriptId":"u103"},
    "836db493d27d4f61aba6f46830392325":{
      "scriptId":"u104"},
    "b9e473ae81004eaea122f4d237cff66f":{
      "scriptId":"u105"},
    "d364964749214754a3da7481e1fa023b":{
      "scriptId":"u106"},
    "e23a74b693da495bbfedbd0e5a157c6d":{
      "scriptId":"u107"},
    "e56a11872c6f49f1a23281f77c14bacf":{
      "scriptId":"u108"},
    "00e2dbf498ad42de9a6bb96e9555cc93":{
      "scriptId":"u109"},
    "5a6db17541da41e68925fc98e332ea3f":{
      "scriptId":"u110"},
    "5c27fc16283e46b39c9f8fcfd90cf440":{
      "scriptId":"u111"},
    "73ef90d05b8640769bea450b410fbaea":{
      "scriptId":"u112"},
    "4f69a17a2b674ee0a3643999605e82b1":{
      "scriptId":"u113"},
    "2f473b00cfcb4f9183e5f1793b1db3d3":{
      "scriptId":"u114"},
    "9354d9cd138e4615abaddab5be385653":{
      "scriptId":"u115"}}});