$axure.loadCurrentPage({
  "url":"应用设置.html",
  "generationDate":new Date(1458553417030.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7a8515cf61a14aa5a20b98845bc7c966",
    "type":"Axure:Page",
    "name":"应用设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0fd5bea7097347cda610e3fb822ec7a9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":210}},
          "adaptiveStyles":{
},
          "masterId":"f73d698e06464df78e2f277ca77e6c60"},
{
          "id":"60c81a5bedfb494db28cb7668d70572a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":394},
            "size":{
              "width":975,
              "height":466}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d385164805d14bf9b255448ccc981cb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":394},
                "size":{
                  "width":975,
                  "height":466}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用设置/u43.png"}},
{
          "id":"cfecf32beef6401c960843fcd4f51041",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":630,
              "y":425},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a16e55fcaaa4576b455b91fb82dab12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":630,
                  "y":425},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb64f8b7a3004444adedff559025a5b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":602,
              "y":507},
            "size":{
              "width":141,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f384c5320214cab973346716ad7c778",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":602,
                  "y":507},
                "size":{
                  "width":141,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"352a1f9d53d6418dbc45d9608e8ca209",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":531,
              "y":597},
            "size":{
              "width":212,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"718aaeabebbb4af5a5b8a617fc542719",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":531,
                  "y":597},
                "size":{
                  "width":212,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41151e1f91a840deb12a1dfeb179d167",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":602,
              "y":792},
            "size":{
              "width":141,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"678fa71eac644026968c6e73bde6aeee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":602,
                  "y":792},
                "size":{
                  "width":141,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad5567d5bec34176b900bbfeaef5e373",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":782,
              "y":425},
            "size":{
              "width":302,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"e83094a2121a4ab08dc5fbc5db74350a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":782,
              "y":498},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9c788b998c7451db69c8b1fce9b8323",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":782,
                  "y":498},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用设置/u54.png"}},
{
          "id":"c077249baca245b6ad263fa18334485a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":782,
              "y":600},
            "size":{
              "width":297,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"946208a460b949e2b4fb2f34b8b78c99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":782,
                  "y":600},
                "size":{
                  "width":297,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用设置/u56.png"}},
{
          "id":"7bb17cca222643508ab14be3b7504c55",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1114,
              "y":427},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"598f55ceac07473391692408842f6dcd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":438,
              "y":660},
            "size":{
              "width":308,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a39137847a8248d0abc7150c056422d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":438,
                  "y":660},
                "size":{
                  "width":308,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1d908ec18124c95b56ce5a9611c8f81",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":782,
              "y":663},
            "size":{
              "width":297,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d5666684e324d509967c9b82eb03b61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":782,
                  "y":663},
                "size":{
                  "width":297,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用设置/u56.png"}},
{
          "id":"5132c8ae9ede467ba67243f943a69c4d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":782,
              "y":792},
            "size":{
              "width":90,
              "height":33}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 应用删除确认",
                      "target":{
                        "targetType":"page",
                        "url":"应用删除确认.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"6f6518a044964462b37333285867115f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":1450,
              "y":210},
            "size":{
              "width":430,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d8466d17edb43039441b526f1c0ac13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":1450,
                  "y":210},
                "size":{
                  "width":430,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u88.png"}},
{
          "id":"450ecc25736440d68ae2c920473142f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":538,
              "y":727},
            "size":{
              "width":199,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e90e55b475124f68930f6fe975da8d48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":538,
                  "y":727},
                "size":{
                  "width":199,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0295637bb7148fa866d93af943b0172",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":782,
              "y":725},
            "size":{
              "width":128,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9edd6efbd924e2db4a22d195cf08ccf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":782,
                  "y":725},
                "size":{
                  "width":128,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用设置/u68.png"}}]}},
  "masters":{
    "f73d698e06464df78e2f277ca77e6c60":{
      "packageId":"f73d698e06464df78e2f277ca77e6c60",
      "type":"Axure:Master",
      "name":"控制台头部框架",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1a8ee24928a94860889c9b047390fbf5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "opacity":"0.3",
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "size":{
                "width":1219,
                "height":930},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f6d5da329001418bad0c45f297bae802",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "opacity":"0.3",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "size":{
                    "width":1219,
                    "height":930},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/应用设置/u1.png"}},
{
            "id":"2b596599a1a2483d84e1634a29aaddec",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":100},
              "size":{
                "width":1219,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/帮助/u43_line.png"}},
{
            "id":"06a4f09ba941472c84ee4ff1c0e16d57",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":797,
                "y":41},
              "size":{
                "width":235,
                "height":33}},
            "adaptiveStyles":{
}},
{
            "id":"2d1981c2bb3a4bbf98d29d5eb4a95f05",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":1031,
                "y":41},
              "size":{
                "width":44,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5c489b146ee44a60b5c40b1930b87fea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":1031,
                    "y":41},
                  "size":{
                    "width":44,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 支付查询",
                        "target":{
                          "targetType":"page",
                          "url":"支付查询.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u45.png"}},
{
            "id":"014e382808854576ac2a5acf6f38b3a2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":35,
                "y":20},
              "size":{
                "width":125,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f984bdbcccaa4abf9aac379604b9f79d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":35,
                    "y":20},
                  "size":{
                    "width":125,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/帮助/u47.png"}},
{
            "id":"09c4937ed6844893bf4a19ae7fcb6637",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1147,
                "y":30},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aa7310f048d8440d82e9fb58dffe258a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1147,
                    "y":30},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u66.png"}},
{
            "id":"34dbe10428ea41ee8cdbb51d7c3ed73a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "location":{
                "x":200,
                "y":41},
              "size":{
                "width":85,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"75e5676d5e144345b4afc81cd6c00d1e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "location":{
                    "x":200,
                    "y":41},
                  "size":{
                    "width":85,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页（控制台）",
                        "target":{
                          "targetType":"page",
                          "url":"首页（控制台）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1ca0ab308cb043d29a39532870348bc8",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":297,
                "y":51},
              "size":{
                "width":23,
                "height":18}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e5cb1b54f0444dcaa8287c88b30ce81b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":297,
                    "y":51},
                  "size":{
                    "width":23,
                    "height":18}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/基本信息（个人呈现）/u25.png"}},
{
            "id":"59565fd155404fd087e51bcb3b8ceb97",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":323,
                "y":45},
              "size":{
                "width":97,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13823699df9d415380fe6b2f3d00fb35",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":323,
                    "y":45},
                  "size":{
                    "width":97,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"605de75946a24d95b684f993a7f6ad55",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":442,
                "y":49},
              "size":{
                "width":23,
                "height":18}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e8228405980441f7a72035454d5f7935",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":442,
                    "y":49},
                  "size":{
                    "width":23,
                    "height":18}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/基本信息（个人呈现）/u25.png"}},
{
            "id":"820860e588cd4af3ae78284ddd63919b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":465,
                "y":44},
              "size":{
                "width":41,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7b2310bbfbdc40dbb3e46fb905d8dfde",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":465,
                    "y":44},
                  "size":{
                    "width":41,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a2a9edf511b04234929b917b016ddb6b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":422,
                "y":50},
              "size":{
                "width":16,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"43226eb6ed254f369986d85d7e2dfe5c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":422,
                    "y":50},
                  "size":{
                    "width":16,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle 应用选择",
                        "objectsToFades":[{
                            "objectPath":["fb749e8082bd4d74bd5870d3c68d974f"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/应用设置/u21.png"}},
{
            "id":"5d81d9693543430bba2efaf7426207c8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":680,
                "y":36},
              "size":{
                "width":50,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dcd37788d84c4d47bfcf05ff917c206f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":680,
                    "y":36},
                  "size":{
                    "width":50,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/帮助/u55.png"}},
{
            "id":"fcdd9f24623747709c69b6ad0e7e80dd",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":508,
                "y":50},
              "size":{
                "width":16,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4313aa7229094c86965ae8cb0a0adb14",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":508,
                    "y":50},
                  "size":{
                    "width":16,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle 操作方式",
                        "objectsToFades":[{
                            "objectPath":["ae1fcf57d46043f98c2706608c5e2f95"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/应用设置/u21.png"}},
{
            "id":"ae1fcf57d46043f98c2706608c5e2f95",
            "label":"操作方式",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":453,
                "y":97},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"d3219cc2308d47a4aa9b4893dca6c30c",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"b3edda47af754c9ebbefbe5fad270a06",
                    "label":"",
                    "parentDynamicPanel":"ae1fcf57d46043f98c2706608c5e2f95",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":74,
                        "height":85}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"fc35079c726e4782ae1d4e64b728b325",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ae1fcf57d46043f98c2706608c5e2f95",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":74,
                            "height":85}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/应用设置/u28.png"}},
{
                    "id":"0253fe835bc541b580ec72a73e5fa3ca",
                    "label":"",
                    "parentDynamicPanel":"ae1fcf57d46043f98c2706608c5e2f95",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "location":{
                        "x":22,
                        "y":10},
                      "size":{
                        "width":29,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"cf6774928fd0438a87ba99c728246f8a",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ae1fcf57d46043f98c2706608c5e2f95",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "location":{
                            "x":22,
                            "y":10},
                          "size":{
                            "width":29,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"033f189a92924add82ab0b12ad78bcda",
                    "label":"",
                    "parentDynamicPanel":"ae1fcf57d46043f98c2706608c5e2f95",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "location":{
                        "x":21,
                        "y":44},
                      "size":{
                        "width":29,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"eb2a1e33f7d84607b955cb8d0bf054ec",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ae1fcf57d46043f98c2706608c5e2f95",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "location":{
                            "x":21,
                            "y":44},
                          "size":{
                            "width":29,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}]}]},
{
            "id":"fb749e8082bd4d74bd5870d3c68d974f",
            "label":"应用选择",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":323,
                "y":93},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"f9f4098dfa334d0a885953b7a55dda9a",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"aef104deff654441937f3c6b24d0466b",
                    "label":"",
                    "parentDynamicPanel":"fb749e8082bd4d74bd5870d3c68d974f",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":96,
                        "height":120}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a5884c74b73a432fbda3c35b22e24923",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fb749e8082bd4d74bd5870d3c68d974f",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":96,
                            "height":120}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/应用设置/u35.png"}},
{
                    "id":"688e10527eb0438eb943179c46e019c3",
                    "label":"",
                    "parentDynamicPanel":"fb749e8082bd4d74bd5870d3c68d974f",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "location":{
                        "x":2,
                        "y":10},
                      "size":{
                        "width":84,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2289a2646d2f4e56a4a2d208d087e8f8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fb749e8082bd4d74bd5870d3c68d974f",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "location":{
                            "x":2,
                            "y":10},
                          "size":{
                            "width":84,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"f44c87262221477eb55f76e75d1e584a",
                    "label":"",
                    "parentDynamicPanel":"fb749e8082bd4d74bd5870d3c68d974f",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "location":{
                        "x":2,
                        "y":44},
                      "size":{
                        "width":84,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a4042af3879e4086a09b3d6543575371",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fb749e8082bd4d74bd5870d3c68d974f",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "location":{
                            "x":2,
                            "y":44},
                          "size":{
                            "width":84,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"1e08709d4afa44e79996463013d6b875",
                    "label":"",
                    "parentDynamicPanel":"fb749e8082bd4d74bd5870d3c68d974f",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "location":{
                        "x":6,
                        "y":80},
                      "size":{
                        "width":84,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"985d0e9376ed43b2a2b871e489e7e707",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fb749e8082bd4d74bd5870d3c68d974f",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "location":{
                            "x":6,
                            "y":80},
                          "size":{
                            "width":84,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}]}]}]}}},
  "objectPaths":{
    "0fd5bea7097347cda610e3fb822ec7a9":{
      "scriptId":"u0",
      "1a8ee24928a94860889c9b047390fbf5":{
        "scriptId":"u1"},
      "f6d5da329001418bad0c45f297bae802":{
        "scriptId":"u2"},
      "2b596599a1a2483d84e1634a29aaddec":{
        "scriptId":"u3"},
      "06a4f09ba941472c84ee4ff1c0e16d57":{
        "scriptId":"u4"},
      "2d1981c2bb3a4bbf98d29d5eb4a95f05":{
        "scriptId":"u5"},
      "5c489b146ee44a60b5c40b1930b87fea":{
        "scriptId":"u6"},
      "014e382808854576ac2a5acf6f38b3a2":{
        "scriptId":"u7"},
      "f984bdbcccaa4abf9aac379604b9f79d":{
        "scriptId":"u8"},
      "09c4937ed6844893bf4a19ae7fcb6637":{
        "scriptId":"u9"},
      "aa7310f048d8440d82e9fb58dffe258a":{
        "scriptId":"u10"},
      "34dbe10428ea41ee8cdbb51d7c3ed73a":{
        "scriptId":"u11"},
      "75e5676d5e144345b4afc81cd6c00d1e":{
        "scriptId":"u12"},
      "1ca0ab308cb043d29a39532870348bc8":{
        "scriptId":"u13"},
      "e5cb1b54f0444dcaa8287c88b30ce81b":{
        "scriptId":"u14"},
      "59565fd155404fd087e51bcb3b8ceb97":{
        "scriptId":"u15"},
      "13823699df9d415380fe6b2f3d00fb35":{
        "scriptId":"u16"},
      "605de75946a24d95b684f993a7f6ad55":{
        "scriptId":"u17"},
      "e8228405980441f7a72035454d5f7935":{
        "scriptId":"u18"},
      "820860e588cd4af3ae78284ddd63919b":{
        "scriptId":"u19"},
      "7b2310bbfbdc40dbb3e46fb905d8dfde":{
        "scriptId":"u20"},
      "a2a9edf511b04234929b917b016ddb6b":{
        "scriptId":"u21"},
      "43226eb6ed254f369986d85d7e2dfe5c":{
        "scriptId":"u22"},
      "5d81d9693543430bba2efaf7426207c8":{
        "scriptId":"u23"},
      "dcd37788d84c4d47bfcf05ff917c206f":{
        "scriptId":"u24"},
      "fcdd9f24623747709c69b6ad0e7e80dd":{
        "scriptId":"u25"},
      "4313aa7229094c86965ae8cb0a0adb14":{
        "scriptId":"u26"},
      "ae1fcf57d46043f98c2706608c5e2f95":{
        "scriptId":"u27"},
      "b3edda47af754c9ebbefbe5fad270a06":{
        "scriptId":"u28"},
      "fc35079c726e4782ae1d4e64b728b325":{
        "scriptId":"u29"},
      "0253fe835bc541b580ec72a73e5fa3ca":{
        "scriptId":"u30"},
      "cf6774928fd0438a87ba99c728246f8a":{
        "scriptId":"u31"},
      "033f189a92924add82ab0b12ad78bcda":{
        "scriptId":"u32"},
      "eb2a1e33f7d84607b955cb8d0bf054ec":{
        "scriptId":"u33"},
      "fb749e8082bd4d74bd5870d3c68d974f":{
        "scriptId":"u34"},
      "aef104deff654441937f3c6b24d0466b":{
        "scriptId":"u35"},
      "a5884c74b73a432fbda3c35b22e24923":{
        "scriptId":"u36"},
      "688e10527eb0438eb943179c46e019c3":{
        "scriptId":"u37"},
      "2289a2646d2f4e56a4a2d208d087e8f8":{
        "scriptId":"u38"},
      "f44c87262221477eb55f76e75d1e584a":{
        "scriptId":"u39"},
      "a4042af3879e4086a09b3d6543575371":{
        "scriptId":"u40"},
      "1e08709d4afa44e79996463013d6b875":{
        "scriptId":"u41"},
      "985d0e9376ed43b2a2b871e489e7e707":{
        "scriptId":"u42"}},
    "60c81a5bedfb494db28cb7668d70572a":{
      "scriptId":"u43"},
    "d385164805d14bf9b255448ccc981cb7":{
      "scriptId":"u44"},
    "cfecf32beef6401c960843fcd4f51041":{
      "scriptId":"u45"},
    "0a16e55fcaaa4576b455b91fb82dab12":{
      "scriptId":"u46"},
    "eb64f8b7a3004444adedff559025a5b5":{
      "scriptId":"u47"},
    "3f384c5320214cab973346716ad7c778":{
      "scriptId":"u48"},
    "352a1f9d53d6418dbc45d9608e8ca209":{
      "scriptId":"u49"},
    "718aaeabebbb4af5a5b8a617fc542719":{
      "scriptId":"u50"},
    "41151e1f91a840deb12a1dfeb179d167":{
      "scriptId":"u51"},
    "678fa71eac644026968c6e73bde6aeee":{
      "scriptId":"u52"},
    "ad5567d5bec34176b900bbfeaef5e373":{
      "scriptId":"u53"},
    "e83094a2121a4ab08dc5fbc5db74350a":{
      "scriptId":"u54"},
    "a9c788b998c7451db69c8b1fce9b8323":{
      "scriptId":"u55"},
    "c077249baca245b6ad263fa18334485a":{
      "scriptId":"u56"},
    "946208a460b949e2b4fb2f34b8b78c99":{
      "scriptId":"u57"},
    "7bb17cca222643508ab14be3b7504c55":{
      "scriptId":"u58"},
    "598f55ceac07473391692408842f6dcd":{
      "scriptId":"u59"},
    "a39137847a8248d0abc7150c056422d1":{
      "scriptId":"u60"},
    "e1d908ec18124c95b56ce5a9611c8f81":{
      "scriptId":"u61"},
    "0d5666684e324d509967c9b82eb03b61":{
      "scriptId":"u62"},
    "5132c8ae9ede467ba67243f943a69c4d":{
      "scriptId":"u63"},
    "6f6518a044964462b37333285867115f":{
      "scriptId":"u64"},
    "7d8466d17edb43039441b526f1c0ac13":{
      "scriptId":"u65"},
    "450ecc25736440d68ae2c920473142f5":{
      "scriptId":"u66"},
    "e90e55b475124f68930f6fe975da8d48":{
      "scriptId":"u67"},
    "c0295637bb7148fa866d93af943b0172":{
      "scriptId":"u68"},
    "a9edd6efbd924e2db4a22d195cf08ccf":{
      "scriptId":"u69"}}});