$axure.loadCurrentPage({
  "url":"签约协议.html",
  "generationDate":new Date(1458553416023.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b20364a0814c4a86a3a18178a2aba76b",
    "type":"Axure:Page",
    "name":"签约协议",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c9381d3f6ead46c3835b114d48e0b944",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":200,
              "y":200},
            "size":{
              "width":1219,
              "height":790},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74de990aa8c5479c9b7a356231c96948",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.3",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":200,
                  "y":200},
                "size":{
                  "width":1219,
                  "height":790},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签约协议/u0.png"}},
{
          "id":"d5274dec77474a928f1c5b0c121dca19",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":300},
            "size":{
              "width":1219,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/帮助/u43_line.png"}},
{
          "id":"09d9dac909fe4d2188e6450c1d11d8c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":220},
            "size":{
              "width":125,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f76940988f414f2f89f22e467ddc828a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":235,
                  "y":220},
                "size":{
                  "width":125,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u47.png"}},
{
          "id":"7ceafeb506a1418ca9aad2ec10cd0e33",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":387,
              "y":237},
            "size":{
              "width":113,
              "height":43},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3604b1759b044a498f2a7273f9dcca7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":387,
                  "y":237},
                "size":{
                  "width":113,
                  "height":43},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页（控制台）",
                      "target":{
                        "targetType":"page",
                        "url":"首页（控制台）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u49.png"}},
{
          "id":"7f8ac056ca4148d3b360a1eea9ba937e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":521,
              "y":237},
            "size":{
              "width":113,
              "height":43},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb43f9d7768f494e89d8cb46b4b5944f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":521,
                  "y":237},
                "size":{
                  "width":113,
                  "height":43},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 渠道管理",
                      "target":{
                        "targetType":"page",
                        "url":"渠道管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u49.png"}},
{
          "id":"aad5c38d59144073870d269c4ffa6d43",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":655,
              "y":237},
            "size":{
              "width":113,
              "height":43},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8abdf78a3084669bb486f80b0cf3569",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":655,
                  "y":237},
                "size":{
                  "width":113,
                  "height":43},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 提现",
                      "target":{
                        "targetType":"page",
                        "url":"提现.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u49.png"}},
{
          "id":"b77a3affe3b8441bb39c3ed01793c6cb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1350,
              "y":230},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a744f9bbca024cf8a218472707ebe8c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1350,
                  "y":230},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u57.png"}},
{
          "id":"66f909ad3749460c89f11ae01d7962b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":306},
            "size":{
              "width":210,
              "height":644}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"315ede6ffdcc4915a65cc8e2cd3b3487",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":306},
                "size":{
                  "width":210,
                  "height":644}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/结算信息/u13.png"}},
{
          "id":"f90104595e3f4115aa8d697d7880f3ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":218,
              "y":352},
            "size":{
              "width":174,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49486f3a2113419ea9544dec0022174f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":218,
                  "y":352},
                "size":{
                  "width":174,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"320ec39ab6f44dea81d09eaf64df8b5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":247,
              "y":398},
            "size":{
              "width":120,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16b60f21f94c4476877d7e6096e955c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":247,
                  "y":398},
                "size":{
                  "width":120,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u64.png"}},
{
          "id":"da718472f85044ccbc37e7182c550439",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":460},
            "size":{
              "width":210,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息（个人呈现）/u19_line.png"}},
{
          "id":"f83d2d57722f4c53a522415c3505c660",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":205,
              "y":524},
            "size":{
              "width":200,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息（个人呈现）/u20_line.png"}},
{
          "id":"eeacb5140b7540a2a02ac42d52347573",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":480},
            "size":{
              "width":42,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbad8e2c117e48daafc23940f2ab10e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":218,
                  "y":480},
                "size":{
                  "width":42,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u21.png"}},
{
          "id":"2f6e0416396f42bab308b8d9a9137228",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":272,
              "y":492},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19e76a7ed5e240419614e6648bb29f7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":272,
                  "y":492},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2f1ea4051f7489398ba04bc5e4d70e9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":366,
              "y":492},
            "size":{
              "width":32,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ef35e1b833246868565608ae0298eb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":366,
                  "y":492},
                "size":{
                  "width":32,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u25.png"}},
{
          "id":"1feda4c5088b4baa89064249513ddc69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":434,
              "y":328},
            "size":{
              "width":946,
              "height":622}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cc7cd1043984afa93a0335beb2eebd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":434,
                  "y":328},
                "size":{
                  "width":946,
                  "height":622}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/结算信息/u27.png"}},
{
          "id":"fb8971b8576c4daaa66fe23fb9113730",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":434,
              "y":328},
            "size":{
              "width":946,
              "height":92}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24ea531f6dc843cb96b455954172ab3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":434,
                  "y":328},
                "size":{
                  "width":946,
                  "height":92}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u29.png"}},
{
          "id":"85f3f81802eb4ac0a57edbb97d508bf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":475,
              "y":364},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edbdd266af5442658c03b52ce073c115",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":475,
                  "y":364},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d1b69fce91142958af5e4b001a8c06b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":205,
              "y":605},
            "size":{
              "width":200,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息（个人呈现）/u20_line.png"}},
{
          "id":"fcaeeea554d042048250c56bd4aa309c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":561},
            "size":{
              "width":42,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7a4279deb4b4cdeb227372d82ff20fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":218,
                  "y":561},
                "size":{
                  "width":42,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u21.png"}},
{
          "id":"6c34374781df4defb5c4c337a75e9bb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":272,
              "y":573},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b46161fd62fc4c5d9e7182ed89108caa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":272,
                  "y":573},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5dc7e78559641ac90448d7491e865dc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":366,
              "y":573},
            "size":{
              "width":32,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c724763b396d4942827ff5211744dbf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":366,
                  "y":573},
                "size":{
                  "width":32,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u25.png"}},
{
          "id":"7761eb21895d476abde201bcacf05d1a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":689},
            "size":{
              "width":200,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息（个人呈现）/u20_line.png"}},
{
          "id":"cbc856cd21d646f3bf7be054a114602f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":217,
              "y":645},
            "size":{
              "width":42,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75543a840063497483ed99b23bb55752",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":217,
                  "y":645},
                "size":{
                  "width":42,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u21.png"}},
{
          "id":"83f8a51078f540b992b6d0fe7bd9f268",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":271,
              "y":657},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4978cafaf7854dada87dda0f9088f043",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":271,
                  "y":657},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7969b52ad08a4bcf8bcd82b9b54b95a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":657},
            "size":{
              "width":32,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdb746b9b9b94954b605d3cc461e6b60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":365,
                  "y":657},
                "size":{
                  "width":32,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u25.png"}},
{
          "id":"f3549f802a92470abf6646acd1887f88",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":207,
              "y":768},
            "size":{
              "width":200,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息（个人呈现）/u20_line.png"}},
{
          "id":"2cc30ea6cfa448059d6f7d3e90ac0a50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":724},
            "size":{
              "width":42,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0ebda1bdaad441b82c8b7753a8eb4ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":724},
                "size":{
                  "width":42,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u21.png"}},
{
          "id":"548363b4bd13445f948dee0cb374bdf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":274,
              "y":736},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"936a7b579c2b4548a51bff87ffef884b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":274,
                  "y":736},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a029647cccbc4c3fbac2730c13bddc53",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":368,
              "y":736},
            "size":{
              "width":32,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3803b2766ba4435b298861e2946107a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":368,
                  "y":736},
                "size":{
                  "width":32,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u25.png"}},
{
          "id":"291c1e7564504292805f8c327bb4db9d",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":450},
            "size":{
              "width":910,
              "height":470}},
          "adaptiveStyles":{
}},
{
          "id":"3bc3bac762794d20ab8ea42aca122ce4",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":475},
            "size":{
              "width":188,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 基本信息（个人呈现）",
                      "target":{
                        "targetType":"page",
                        "url":"基本信息（个人呈现）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"76090575611e4a048be42b83532f546a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":555},
            "size":{
              "width":188,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 结算信息",
                      "target":{
                        "targetType":"page",
                        "url":"结算信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"facd118a12fc4f7aa0b19ee83a26d136",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":639},
            "size":{
              "width":188,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 密码管理",
                      "target":{
                        "targetType":"page",
                        "url":"密码管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a33ee654839348d18b0475b83b5f6e95",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":212.5,
              "y":720.5},
            "size":{
              "width":188,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 签约协议",
                      "target":{
                        "targetType":"page",
                        "url":"签约协议.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "c9381d3f6ead46c3835b114d48e0b944":{
      "scriptId":"u0"},
    "74de990aa8c5479c9b7a356231c96948":{
      "scriptId":"u1"},
    "d5274dec77474a928f1c5b0c121dca19":{
      "scriptId":"u2"},
    "09d9dac909fe4d2188e6450c1d11d8c8":{
      "scriptId":"u3"},
    "f76940988f414f2f89f22e467ddc828a":{
      "scriptId":"u4"},
    "7ceafeb506a1418ca9aad2ec10cd0e33":{
      "scriptId":"u5"},
    "3604b1759b044a498f2a7273f9dcca7c":{
      "scriptId":"u6"},
    "7f8ac056ca4148d3b360a1eea9ba937e":{
      "scriptId":"u7"},
    "fb43f9d7768f494e89d8cb46b4b5944f":{
      "scriptId":"u8"},
    "aad5c38d59144073870d269c4ffa6d43":{
      "scriptId":"u9"},
    "b8abdf78a3084669bb486f80b0cf3569":{
      "scriptId":"u10"},
    "b77a3affe3b8441bb39c3ed01793c6cb":{
      "scriptId":"u11"},
    "a744f9bbca024cf8a218472707ebe8c4":{
      "scriptId":"u12"},
    "66f909ad3749460c89f11ae01d7962b1":{
      "scriptId":"u13"},
    "315ede6ffdcc4915a65cc8e2cd3b3487":{
      "scriptId":"u14"},
    "f90104595e3f4115aa8d697d7880f3ea":{
      "scriptId":"u15"},
    "49486f3a2113419ea9544dec0022174f":{
      "scriptId":"u16"},
    "320ec39ab6f44dea81d09eaf64df8b5f":{
      "scriptId":"u17"},
    "16b60f21f94c4476877d7e6096e955c4":{
      "scriptId":"u18"},
    "da718472f85044ccbc37e7182c550439":{
      "scriptId":"u19"},
    "f83d2d57722f4c53a522415c3505c660":{
      "scriptId":"u20"},
    "eeacb5140b7540a2a02ac42d52347573":{
      "scriptId":"u21"},
    "fbad8e2c117e48daafc23940f2ab10e0":{
      "scriptId":"u22"},
    "2f6e0416396f42bab308b8d9a9137228":{
      "scriptId":"u23"},
    "19e76a7ed5e240419614e6648bb29f7b":{
      "scriptId":"u24"},
    "d2f1ea4051f7489398ba04bc5e4d70e9":{
      "scriptId":"u25"},
    "3ef35e1b833246868565608ae0298eb9":{
      "scriptId":"u26"},
    "1feda4c5088b4baa89064249513ddc69":{
      "scriptId":"u27"},
    "4cc7cd1043984afa93a0335beb2eebd6":{
      "scriptId":"u28"},
    "fb8971b8576c4daaa66fe23fb9113730":{
      "scriptId":"u29"},
    "24ea531f6dc843cb96b455954172ab3f":{
      "scriptId":"u30"},
    "85f3f81802eb4ac0a57edbb97d508bf1":{
      "scriptId":"u31"},
    "edbdd266af5442658c03b52ce073c115":{
      "scriptId":"u32"},
    "7d1b69fce91142958af5e4b001a8c06b":{
      "scriptId":"u33"},
    "fcaeeea554d042048250c56bd4aa309c":{
      "scriptId":"u34"},
    "b7a4279deb4b4cdeb227372d82ff20fe":{
      "scriptId":"u35"},
    "6c34374781df4defb5c4c337a75e9bb0":{
      "scriptId":"u36"},
    "b46161fd62fc4c5d9e7182ed89108caa":{
      "scriptId":"u37"},
    "c5dc7e78559641ac90448d7491e865dc":{
      "scriptId":"u38"},
    "c724763b396d4942827ff5211744dbf2":{
      "scriptId":"u39"},
    "7761eb21895d476abde201bcacf05d1a":{
      "scriptId":"u40"},
    "cbc856cd21d646f3bf7be054a114602f":{
      "scriptId":"u41"},
    "75543a840063497483ed99b23bb55752":{
      "scriptId":"u42"},
    "83f8a51078f540b992b6d0fe7bd9f268":{
      "scriptId":"u43"},
    "4978cafaf7854dada87dda0f9088f043":{
      "scriptId":"u44"},
    "7969b52ad08a4bcf8bcd82b9b54b95a1":{
      "scriptId":"u45"},
    "cdb746b9b9b94954b605d3cc461e6b60":{
      "scriptId":"u46"},
    "f3549f802a92470abf6646acd1887f88":{
      "scriptId":"u47"},
    "2cc30ea6cfa448059d6f7d3e90ac0a50":{
      "scriptId":"u48"},
    "f0ebda1bdaad441b82c8b7753a8eb4ef":{
      "scriptId":"u49"},
    "548363b4bd13445f948dee0cb374bdf0":{
      "scriptId":"u50"},
    "936a7b579c2b4548a51bff87ffef884b":{
      "scriptId":"u51"},
    "a029647cccbc4c3fbac2730c13bddc53":{
      "scriptId":"u52"},
    "e3803b2766ba4435b298861e2946107a":{
      "scriptId":"u53"},
    "291c1e7564504292805f8c327bb4db9d":{
      "scriptId":"u54"},
    "3bc3bac762794d20ab8ea42aca122ce4":{
      "scriptId":"u55"},
    "76090575611e4a048be42b83532f546a":{
      "scriptId":"u56"},
    "facd118a12fc4f7aa0b19ee83a26d136":{
      "scriptId":"u57"},
    "a33ee654839348d18b0475b83b5f6e95":{
      "scriptId":"u58"}}});