$axure.loadCurrentPage({
  "url":"渠道删除确认.html",
  "generationDate":new Date(1458553418671.54),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"aa4c85b867654f9a82bf4c9ff4f58f71",
    "type":"Axure:Page",
    "name":"渠道删除确认",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c6b2d74f1fba4958a5c984ecc91df033",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":235}},
          "adaptiveStyles":{
},
          "masterId":"ce194b8bf61742aea7475dad35671852"},
{
          "id":"e9e7063fb877426683225cc471bb1b0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":312,
              "y":460},
            "size":{
              "width":1009,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c980c17e7df04d3196c179fb4bb7a4f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":312,
                  "y":460},
                "size":{
                  "width":1009,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/渠道管理/u28.png"}},
{
          "id":"6b1ff4ea78764ad38155280e0bbe589d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":352,
              "y":392},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9b872a718b242df977970bd5819146a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":352,
                  "y":392},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8f8310f911044d484145cd8886ff527",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":1164,
              "y":392},
            "size":{
              "width":134,
              "height":38},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ceb0aa9f57b9454bb359bab13c260f66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":1164,
                  "y":392},
                "size":{
                  "width":134,
                  "height":38},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 渠道添加",
                      "target":{
                        "targetType":"page",
                        "url":"渠道添加.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/渠道删除确认/u32.png"}},
{
          "id":"17510c0cf29d4836b236772b47fb9500",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":314,
              "y":461},
            "size":{
              "width":1007,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d59363d4b0f461f831f473357262c12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":314,
                  "y":461},
                "size":{
                  "width":1007,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/渠道管理/u32.png"}},
{
          "id":"d17425bc7c5f4a05ae13e24e2add7bed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":359,
              "y":483},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d9ed964e7bd4622a2a61e162a644108",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":359,
                  "y":483},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91ce93dcd8364ed08262fba7ad365b28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":503,
              "y":483},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f81ae7111aa144e19143bd7743d86a77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":503,
                  "y":483},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a68e52faae1454ba98c5a320ad8dc9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":628,
              "y":483},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ee408a4aab1407dba1566adc6c2ef47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":628,
                  "y":483},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6eef2f431fc64ff29cdf476f3e345af2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":753,
              "y":483},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d698879576a469295821d196e92b73e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":753,
                  "y":483},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef795e1dc9e64b7e9eb208477ee60255",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":883,
              "y":483},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c88afc813c54a358547d0bf31415b04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":883,
                  "y":483},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"833baa480c784cafabea81c5082cf923",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":1015,
              "y":483},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2816f6674ffd4741b14ca1d369d9309e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":1015,
                  "y":483},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a247e21c60e40bdaad938864211c1a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":1211,
              "y":482},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adf815b3543d4943850bd6eb0071debc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":1211,
                  "y":482},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a4bb10f2c8f4cc29021c248c75abd91",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":441,
              "y":461},
            "size":{
              "width":10,
              "height":60}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/渠道管理/u48_line.png"}},
{
          "id":"2ce9d879e3424f539f30fc1465601eaf",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":579,
              "y":460},
            "size":{
              "width":10,
              "height":60}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/渠道管理/u48_line.png"}},
{
          "id":"904a88fa8a704180a869ecfdd3f03a58",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":723,
              "y":460},
            "size":{
              "width":10,
              "height":60}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/渠道管理/u48_line.png"}},
{
          "id":"f938610a469f4d3fa6874b3bde8defe1",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":831,
              "y":460},
            "size":{
              "width":10,
              "height":60}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/渠道管理/u48_line.png"}},
{
          "id":"c242caeaf44740f49572709936222174",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":989,
              "y":461},
            "size":{
              "width":10,
              "height":60}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/渠道管理/u48_line.png"}},
{
          "id":"4719fd49f3084fc58fddf10479952596",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1156,
              "y":461},
            "size":{
              "width":10,
              "height":60}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/渠道管理/u48_line.png"}},
{
          "id":"0b476a99c0e34a4caf4c8c8010a12073",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":518},
            "size":{
              "width":1007,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"414780db505f488d8b24d3ccbc7b5c51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":518},
                "size":{
                  "width":1007,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/渠道管理/u54.png"}},
{
          "id":"f0e6ee3fc87a4de49211485e6e1e4590",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":364,
              "y":541},
            "size":{
              "width":46,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6a61e6c46044482ad23d2978ead5feb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":364,
                  "y":541},
                "size":{
                  "width":46,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a3a42cfafc34270a72cb2142ff38f64",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":450,
              "y":541},
            "size":{
              "width":136,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"549783d95a964b739b56a6d0de838763",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":450,
                  "y":541},
                "size":{
                  "width":136,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f07352ca8f3d4d55bd55ae5c5d264c8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":624,
              "y":541},
            "size":{
              "width":97,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6be2c0c742234e11a297050cf92b0f62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":624,
                  "y":541},
                "size":{
                  "width":97,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40acab6e76174e52ab48e47e854df6d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":755,
              "y":541},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfd91165ddaa474f946e35d8300c659d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":755,
                  "y":541},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef64dfbf524b45f39b8422aef61bf1ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":853,
              "y":541},
            "size":{
              "width":141,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"947adbb56cb84a0893661be9ea566134",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":853,
                  "y":541},
                "size":{
                  "width":141,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad8d08eee50c49dcaf1c7b10d1c0071e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1004,
              "y":541},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82f3672e71d84b36b5efd2eed03c9798",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1004,
                  "y":541},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"951da6ca7e874fc39b33d5527c385f50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1169,
              "y":537},
            "size":{
              "width":68,
              "height":29},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07fb7876b7d748f7808deb3cc30e1baf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1169,
                  "y":537},
                "size":{
                  "width":68,
                  "height":29},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 重置密码",
                      "target":{
                        "targetType":"page",
                        "url":"重置密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/渠道管理/u68.png"}},
{
          "id":"42e94f7743094a25ac67fa05d27d8e6c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":882,
              "y":930},
            "size":{
              "width":439,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74f44f72acf94396b8c5c07b7fea6855",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":882,
                  "y":930},
                "size":{
                  "width":439,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/渠道管理/u70.png"}},
{
          "id":"ce96157f590248d299cab2923dce01c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":580},
            "size":{
              "width":1007,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"933c5b7337574b11850cd0136aa8c08b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":580},
                "size":{
                  "width":1007,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/渠道管理/u54.png"}},
{
          "id":"67a19763036d43c1bd019c64811a2af3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":364,
              "y":603},
            "size":{
              "width":46,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60cc0a1330b34c809bd9073da2f7994a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":364,
                  "y":603},
                "size":{
                  "width":46,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8141e951f332400f8e5c0c7b382ed72c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":450,
              "y":603},
            "size":{
              "width":136,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e55c4a45bf74b0d8b4de2f91c4a8ff1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":450,
                  "y":603},
                "size":{
                  "width":136,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfb90f476f2d47329321ed5b3482e5b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":624,
              "y":603},
            "size":{
              "width":97,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32bb6bdfaa674a9fbdee9387d49fe07f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":624,
                  "y":603},
                "size":{
                  "width":97,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f81cd5db805c4d43a065266989c670b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":755,
              "y":603},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"675f5f76340f4c9f99db41041a09fa48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":755,
                  "y":603},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43e036b3303744ffbcd56ae0a2ccd62d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":853,
              "y":603},
            "size":{
              "width":141,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dca5d8ff68d4f0ba5ccd329ba4849e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":853,
                  "y":603},
                "size":{
                  "width":141,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2235b1ae9024ce18af25ff73ecf7839",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1004,
              "y":603},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cabd74f4fb44dfa84a38c8e9442994d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1004,
                  "y":603},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15c616f77f7a429e9fed72109c67000d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1174,
              "y":599},
            "size":{
              "width":68,
              "height":29},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28cca1d0b78b46d6b4868628276a9ab8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1174,
                  "y":599},
                "size":{
                  "width":68,
                  "height":29},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/渠道管理/u68.png"}},
{
          "id":"723991dca52c4825b5de5d620ef5f77d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1253,
              "y":599},
            "size":{
              "width":53,
              "height":29},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69c6c4906b2d4b7fbbd7d3ebd93716f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1253,
                  "y":599},
                "size":{
                  "width":53,
                  "height":29},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/渠道管理/u88.png"}},
{
          "id":"77437c29323f4f5698f2eec114d14f0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1253,
              "y":537},
            "size":{
              "width":53,
              "height":29},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46b6d1c2a53249bfa1e24ee63832bc95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1253,
                  "y":537},
                "size":{
                  "width":53,
                  "height":29},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/渠道管理/u88.png"}},
{
          "id":"e4b7aa122661473bb2f33dde83dac766",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.4",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":210,
              "y":233},
            "size":{
              "width":1220,
              "height":930}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb3986dbc6594eafb885086fb9ce2de2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.4",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":210,
                  "y":233},
                "size":{
                  "width":1220,
                  "height":930}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改基本信息成功提示/u115.png"}},
{
          "id":"cb65945fdf7741209bf11fa1a841f321",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":531,
              "y":481},
            "size":{
              "width":519,
              "height":342}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"002053ce37014a33a875b10b2959bef2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":531,
                  "y":481},
                "size":{
                  "width":519,
                  "height":342}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用删除确认/u75.png"}},
{
          "id":"127e9ff4f5744dd2ae1df844a865ab4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":531,
              "y":481},
            "size":{
              "width":519,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2592be5d0e7e41e5a0d682979330923f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":531,
                  "y":481},
                "size":{
                  "width":519,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找回原安全密码/u83.png"}},
{
          "id":"cec0f9f6259447a6a83d4c0fbd1959e2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":492},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb84f829387441dea3492954b4e13098",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":492},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 渠道管理",
                      "target":{
                        "targetType":"page",
                        "url":"渠道管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u74.png"}},
{
          "id":"c582b5dd1d27434d87b35d9c343647af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":575,
              "y":583},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e014baad3f2744f98d612e043129f610",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":575,
                  "y":583},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3baf9984831a4f4aac420f2e694238e0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":703,
              "y":583},
            "size":{
              "width":200,
              "height":34}},
          "adaptiveStyles":{
}},
{
          "id":"6d373723815445f58cb4dec8e0271efe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":552,
              "y":663},
            "size":{
              "width":121,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e72abee779bc46f9991da614e9632247",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":552,
                  "y":663},
                "size":{
                  "width":121,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a03cc7b45ef4a749a3f7c3f59a3a29e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":703,
              "y":657},
            "size":{
              "width":200,
              "height":34}},
          "adaptiveStyles":{
}},
{
          "id":"228730906e484c5897989daf1b9bc37b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":930,
              "y":661},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d79ddf3d04144e1aa95bacc73fdc412",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":930,
                  "y":661},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息（个人呈现）/u85.png"}},
{
          "id":"f827bf64aac24aedaaec9819e1b0c068",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":531,
              "y":742},
            "size":{
              "width":519,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户签约-提交成功提醒/u92_line.png"}},
{
          "id":"ce5ebf83f5cb4408b4bd2f9a16aa416e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":720,
              "y":770},
            "size":{
              "width":120,
              "height":37},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f580678b86114548b0e71022b6ea8a36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":720,
                  "y":770},
                "size":{
                  "width":120,
                  "height":37},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 渠道管理",
                      "target":{
                        "targetType":"page",
                        "url":"渠道管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户签约-提交成功提醒/u93.png"}},
{
          "id":"d6e28ac46ad64b5995e65465f6131229",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":627},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"318dd1b700dd4151a9e5273ede54da30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":627},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1de7fa9b320647af81405ba0f43df46a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":702,
              "y":627},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5db539f67df44c26a5d425e632cd2cec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":702,
                  "y":627},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u81.png"}},
{
          "id":"44f9475f626041ed9df63531a9ce582f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":708},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ab2f76beea843feb1813358d4e8263f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":708},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d6c4314d0b548869694fb4133e94472",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":702,
              "y":708},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14c57c39fbcb452f907ae78ddb871a10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":702,
                  "y":708},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u81.png"}}]}},
  "masters":{
    "ce194b8bf61742aea7475dad35671852":{
      "packageId":"ce194b8bf61742aea7475dad35671852",
      "type":"Axure:Master",
      "name":"头部框架",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1a8ee24928a94860889c9b047390fbf5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "opacity":"0.3",
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "size":{
                "width":1219,
                "height":740},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f6d5da329001418bad0c45f297bae802",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "opacity":"0.3",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "size":{
                    "width":1219,
                    "height":740},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/帮助/u41.png"}},
{
            "id":"2b596599a1a2483d84e1634a29aaddec",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":100},
              "size":{
                "width":1219,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/帮助/u43_line.png"}},
{
            "id":"06a4f09ba941472c84ee4ff1c0e16d57",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":797,
                "y":41},
              "size":{
                "width":235,
                "height":33}},
            "adaptiveStyles":{
}},
{
            "id":"2d1981c2bb3a4bbf98d29d5eb4a95f05",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":1031,
                "y":41},
              "size":{
                "width":44,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5c489b146ee44a60b5c40b1930b87fea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":1031,
                    "y":41},
                  "size":{
                    "width":44,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 支付查询",
                        "target":{
                          "targetType":"page",
                          "url":"支付查询.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u45.png"}},
{
            "id":"014e382808854576ac2a5acf6f38b3a2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":35,
                "y":20},
              "size":{
                "width":125,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f984bdbcccaa4abf9aac379604b9f79d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":35,
                    "y":20},
                  "size":{
                    "width":125,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/帮助/u47.png"}},
{
            "id":"bececc72e4864233aa56bbeb0067e5a5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":187,
                "y":37},
              "size":{
                "width":113,
                "height":43},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"665d02781c8d4d96a2ccf54f489faf8d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":187,
                    "y":37},
                  "size":{
                    "width":113,
                    "height":43},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页（控制台）",
                        "target":{
                          "targetType":"page",
                          "url":"首页（控制台）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u49.png"}},
{
            "id":"5677bc86a0564221862e5fb5edc25a28",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":321,
                "y":37},
              "size":{
                "width":113,
                "height":43},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a67b7f0a523b4de4af12f9a03eba2cc1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":321,
                    "y":37},
                  "size":{
                    "width":113,
                    "height":43},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 渠道管理",
                        "target":{
                          "targetType":"page",
                          "url":"渠道管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u49.png"}},
{
            "id":"40f50ee05dec42038ace8903a7be2aa8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":455,
                "y":37},
              "size":{
                "width":113,
                "height":43},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"209a6b3bfa1a42e38bc030da67bf54fa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":455,
                    "y":37},
                  "size":{
                    "width":113,
                    "height":43},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 提现",
                        "target":{
                          "targetType":"page",
                          "url":"提现.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u49.png"}},
{
            "id":"f7852bcc4c5a4921802ef94e6d848264",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":623,
                "y":40},
              "size":{
                "width":50,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da463ba93a7b4aec8326c16acf8da252",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":623,
                    "y":40},
                  "size":{
                    "width":50,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 帮助",
                        "target":{
                          "targetType":"page",
                          "url":"帮助.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u55.png"}},
{
            "id":"75f88fef079b47a09a5869837b83bf72",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1150,
                "y":30},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e78ad31a00344180aede2de040f4a718",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1150,
                    "y":30},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle 右侧边栏",
                        "objectsToFades":[{
                            "objectPath":["4c67581e5b9c41d2bed24e008a7eaf41"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u57.png"}},
{
            "id":"4c67581e5b9c41d2bed24e008a7eaf41",
            "label":"右侧边栏",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":1019,
                "y":105},
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"735f9a5466874ed29256b29c16e25def",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"718082d5a20f450d9c84bd2103096cf6",
                    "label":"",
                    "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":200,
                        "height":205}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b1ccd05daa8b42a3bfb0dbd5953ba989",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":200,
                            "height":205}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/帮助/u60.png"}},
{
                    "id":"9654f5fb424e410187206b64ad418cc3",
                    "label":"",
                    "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Negreta', 'Arial'",
                      "fontSize":"18px",
                      "fontWeight":"700",
                      "location":{
                        "x":12,
                        "y":26},
                      "size":{
                        "width":174,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"90a4735f986b4a6182c99e43389f1406",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Negreta', 'Arial'",
                          "fontSize":"18px",
                          "fontWeight":"700",
                          "location":{
                            "x":12,
                            "y":26},
                          "size":{
                            "width":174,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"b8ee2d90d06e4e538a40ae52e9ffc07e",
                    "label":"",
                    "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontSize":"16px",
                      "location":{
                        "x":41,
                        "y":73},
                      "size":{
                        "width":120,
                        "height":30},
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2d867bb2072e457e8c918d09ae3ddac6",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"16px",
                          "location":{
                            "x":41,
                            "y":73},
                          "size":{
                            "width":120,
                            "height":30},
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 基本信息（个人呈现）",
                                "target":{
                                  "targetType":"page",
                                  "url":"基本信息（个人呈现）.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/帮助/u64.png"}},
{
                    "id":"09c4937ed6844893bf4a19ae7fcb6637",
                    "label":"",
                    "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":75,
                        "y":128},
                      "size":{
                        "width":50,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"aa7310f048d8440d82e9fb58dffe258a",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":75,
                            "y":128},
                          "size":{
                            "width":50,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/帮助/u66.png"}}]}]}]}}},
  "objectPaths":{
    "c6b2d74f1fba4958a5c984ecc91df033":{
      "scriptId":"u0",
      "1a8ee24928a94860889c9b047390fbf5":{
        "scriptId":"u1"},
      "f6d5da329001418bad0c45f297bae802":{
        "scriptId":"u2"},
      "2b596599a1a2483d84e1634a29aaddec":{
        "scriptId":"u3"},
      "06a4f09ba941472c84ee4ff1c0e16d57":{
        "scriptId":"u4"},
      "2d1981c2bb3a4bbf98d29d5eb4a95f05":{
        "scriptId":"u5"},
      "5c489b146ee44a60b5c40b1930b87fea":{
        "scriptId":"u6"},
      "014e382808854576ac2a5acf6f38b3a2":{
        "scriptId":"u7"},
      "f984bdbcccaa4abf9aac379604b9f79d":{
        "scriptId":"u8"},
      "bececc72e4864233aa56bbeb0067e5a5":{
        "scriptId":"u9"},
      "665d02781c8d4d96a2ccf54f489faf8d":{
        "scriptId":"u10"},
      "5677bc86a0564221862e5fb5edc25a28":{
        "scriptId":"u11"},
      "a67b7f0a523b4de4af12f9a03eba2cc1":{
        "scriptId":"u12"},
      "40f50ee05dec42038ace8903a7be2aa8":{
        "scriptId":"u13"},
      "209a6b3bfa1a42e38bc030da67bf54fa":{
        "scriptId":"u14"},
      "f7852bcc4c5a4921802ef94e6d848264":{
        "scriptId":"u15"},
      "da463ba93a7b4aec8326c16acf8da252":{
        "scriptId":"u16"},
      "75f88fef079b47a09a5869837b83bf72":{
        "scriptId":"u17"},
      "e78ad31a00344180aede2de040f4a718":{
        "scriptId":"u18"},
      "4c67581e5b9c41d2bed24e008a7eaf41":{
        "scriptId":"u19"},
      "718082d5a20f450d9c84bd2103096cf6":{
        "scriptId":"u20"},
      "b1ccd05daa8b42a3bfb0dbd5953ba989":{
        "scriptId":"u21"},
      "9654f5fb424e410187206b64ad418cc3":{
        "scriptId":"u22"},
      "90a4735f986b4a6182c99e43389f1406":{
        "scriptId":"u23"},
      "b8ee2d90d06e4e538a40ae52e9ffc07e":{
        "scriptId":"u24"},
      "2d867bb2072e457e8c918d09ae3ddac6":{
        "scriptId":"u25"},
      "09c4937ed6844893bf4a19ae7fcb6637":{
        "scriptId":"u26"},
      "aa7310f048d8440d82e9fb58dffe258a":{
        "scriptId":"u27"}},
    "e9e7063fb877426683225cc471bb1b0e":{
      "scriptId":"u28"},
    "c980c17e7df04d3196c179fb4bb7a4f4":{
      "scriptId":"u29"},
    "6b1ff4ea78764ad38155280e0bbe589d":{
      "scriptId":"u30"},
    "d9b872a718b242df977970bd5819146a":{
      "scriptId":"u31"},
    "b8f8310f911044d484145cd8886ff527":{
      "scriptId":"u32"},
    "ceb0aa9f57b9454bb359bab13c260f66":{
      "scriptId":"u33"},
    "17510c0cf29d4836b236772b47fb9500":{
      "scriptId":"u34"},
    "5d59363d4b0f461f831f473357262c12":{
      "scriptId":"u35"},
    "d17425bc7c5f4a05ae13e24e2add7bed":{
      "scriptId":"u36"},
    "7d9ed964e7bd4622a2a61e162a644108":{
      "scriptId":"u37"},
    "91ce93dcd8364ed08262fba7ad365b28":{
      "scriptId":"u38"},
    "f81ae7111aa144e19143bd7743d86a77":{
      "scriptId":"u39"},
    "4a68e52faae1454ba98c5a320ad8dc9f":{
      "scriptId":"u40"},
    "8ee408a4aab1407dba1566adc6c2ef47":{
      "scriptId":"u41"},
    "6eef2f431fc64ff29cdf476f3e345af2":{
      "scriptId":"u42"},
    "9d698879576a469295821d196e92b73e":{
      "scriptId":"u43"},
    "ef795e1dc9e64b7e9eb208477ee60255":{
      "scriptId":"u44"},
    "4c88afc813c54a358547d0bf31415b04":{
      "scriptId":"u45"},
    "833baa480c784cafabea81c5082cf923":{
      "scriptId":"u46"},
    "2816f6674ffd4741b14ca1d369d9309e":{
      "scriptId":"u47"},
    "9a247e21c60e40bdaad938864211c1a5":{
      "scriptId":"u48"},
    "adf815b3543d4943850bd6eb0071debc":{
      "scriptId":"u49"},
    "3a4bb10f2c8f4cc29021c248c75abd91":{
      "scriptId":"u50"},
    "2ce9d879e3424f539f30fc1465601eaf":{
      "scriptId":"u51"},
    "904a88fa8a704180a869ecfdd3f03a58":{
      "scriptId":"u52"},
    "f938610a469f4d3fa6874b3bde8defe1":{
      "scriptId":"u53"},
    "c242caeaf44740f49572709936222174":{
      "scriptId":"u54"},
    "4719fd49f3084fc58fddf10479952596":{
      "scriptId":"u55"},
    "0b476a99c0e34a4caf4c8c8010a12073":{
      "scriptId":"u56"},
    "414780db505f488d8b24d3ccbc7b5c51":{
      "scriptId":"u57"},
    "f0e6ee3fc87a4de49211485e6e1e4590":{
      "scriptId":"u58"},
    "b6a61e6c46044482ad23d2978ead5feb":{
      "scriptId":"u59"},
    "2a3a42cfafc34270a72cb2142ff38f64":{
      "scriptId":"u60"},
    "549783d95a964b739b56a6d0de838763":{
      "scriptId":"u61"},
    "f07352ca8f3d4d55bd55ae5c5d264c8a":{
      "scriptId":"u62"},
    "6be2c0c742234e11a297050cf92b0f62":{
      "scriptId":"u63"},
    "40acab6e76174e52ab48e47e854df6d5":{
      "scriptId":"u64"},
    "cfd91165ddaa474f946e35d8300c659d":{
      "scriptId":"u65"},
    "ef64dfbf524b45f39b8422aef61bf1ef":{
      "scriptId":"u66"},
    "947adbb56cb84a0893661be9ea566134":{
      "scriptId":"u67"},
    "ad8d08eee50c49dcaf1c7b10d1c0071e":{
      "scriptId":"u68"},
    "82f3672e71d84b36b5efd2eed03c9798":{
      "scriptId":"u69"},
    "951da6ca7e874fc39b33d5527c385f50":{
      "scriptId":"u70"},
    "07fb7876b7d748f7808deb3cc30e1baf":{
      "scriptId":"u71"},
    "42e94f7743094a25ac67fa05d27d8e6c":{
      "scriptId":"u72"},
    "74f44f72acf94396b8c5c07b7fea6855":{
      "scriptId":"u73"},
    "ce96157f590248d299cab2923dce01c8":{
      "scriptId":"u74"},
    "933c5b7337574b11850cd0136aa8c08b":{
      "scriptId":"u75"},
    "67a19763036d43c1bd019c64811a2af3":{
      "scriptId":"u76"},
    "60cc0a1330b34c809bd9073da2f7994a":{
      "scriptId":"u77"},
    "8141e951f332400f8e5c0c7b382ed72c":{
      "scriptId":"u78"},
    "2e55c4a45bf74b0d8b4de2f91c4a8ff1":{
      "scriptId":"u79"},
    "cfb90f476f2d47329321ed5b3482e5b9":{
      "scriptId":"u80"},
    "32bb6bdfaa674a9fbdee9387d49fe07f":{
      "scriptId":"u81"},
    "f81cd5db805c4d43a065266989c670b5":{
      "scriptId":"u82"},
    "675f5f76340f4c9f99db41041a09fa48":{
      "scriptId":"u83"},
    "43e036b3303744ffbcd56ae0a2ccd62d":{
      "scriptId":"u84"},
    "0dca5d8ff68d4f0ba5ccd329ba4849e4":{
      "scriptId":"u85"},
    "c2235b1ae9024ce18af25ff73ecf7839":{
      "scriptId":"u86"},
    "3cabd74f4fb44dfa84a38c8e9442994d":{
      "scriptId":"u87"},
    "15c616f77f7a429e9fed72109c67000d":{
      "scriptId":"u88"},
    "28cca1d0b78b46d6b4868628276a9ab8":{
      "scriptId":"u89"},
    "723991dca52c4825b5de5d620ef5f77d":{
      "scriptId":"u90"},
    "69c6c4906b2d4b7fbbd7d3ebd93716f1":{
      "scriptId":"u91"},
    "77437c29323f4f5698f2eec114d14f0a":{
      "scriptId":"u92"},
    "46b6d1c2a53249bfa1e24ee63832bc95":{
      "scriptId":"u93"},
    "e4b7aa122661473bb2f33dde83dac766":{
      "scriptId":"u94"},
    "cb3986dbc6594eafb885086fb9ce2de2":{
      "scriptId":"u95"},
    "cb65945fdf7741209bf11fa1a841f321":{
      "scriptId":"u96"},
    "002053ce37014a33a875b10b2959bef2":{
      "scriptId":"u97"},
    "127e9ff4f5744dd2ae1df844a865ab4b":{
      "scriptId":"u98"},
    "2592be5d0e7e41e5a0d682979330923f":{
      "scriptId":"u99"},
    "cec0f9f6259447a6a83d4c0fbd1959e2":{
      "scriptId":"u100"},
    "bb84f829387441dea3492954b4e13098":{
      "scriptId":"u101"},
    "c582b5dd1d27434d87b35d9c343647af":{
      "scriptId":"u102"},
    "e014baad3f2744f98d612e043129f610":{
      "scriptId":"u103"},
    "3baf9984831a4f4aac420f2e694238e0":{
      "scriptId":"u104"},
    "6d373723815445f58cb4dec8e0271efe":{
      "scriptId":"u105"},
    "e72abee779bc46f9991da614e9632247":{
      "scriptId":"u106"},
    "6a03cc7b45ef4a749a3f7c3f59a3a29e":{
      "scriptId":"u107"},
    "228730906e484c5897989daf1b9bc37b":{
      "scriptId":"u108"},
    "1d79ddf3d04144e1aa95bacc73fdc412":{
      "scriptId":"u109"},
    "f827bf64aac24aedaaec9819e1b0c068":{
      "scriptId":"u110"},
    "ce5ebf83f5cb4408b4bd2f9a16aa416e":{
      "scriptId":"u111"},
    "f580678b86114548b0e71022b6ea8a36":{
      "scriptId":"u112"},
    "d6e28ac46ad64b5995e65465f6131229":{
      "scriptId":"u113"},
    "318dd1b700dd4151a9e5273ede54da30":{
      "scriptId":"u114"},
    "1de7fa9b320647af81405ba0f43df46a":{
      "scriptId":"u115"},
    "5db539f67df44c26a5d425e632cd2cec":{
      "scriptId":"u116"},
    "44f9475f626041ed9df63531a9ce582f":{
      "scriptId":"u117"},
    "7ab2f76beea843feb1813358d4e8263f":{
      "scriptId":"u118"},
    "2d6c4314d0b548869694fb4133e94472":{
      "scriptId":"u119"},
    "14c57c39fbcb452f907ae78ddb871a10":{
      "scriptId":"u120"}}});