$axure.loadCurrentPage({
  "url":"充值记录.html",
  "generationDate":new Date(1468318605697.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"03419ad2ec5a4b589c238072e4412862",
    "type":"Axure:Page",
    "name":"充值记录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1e0c483aa5f545b1a893232f07621f32",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":51},
            "size":{
              "width":1180,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1800b94d17194b209f8e1bfd20ee1039",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":51},
                "size":{
                  "width":1180,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易记录/u0.png"}},
{
          "id":"592c4ab1e2dd4d6a814d36da3006a048",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":72},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af37e9ca48594f3ab8a4f4cd53f4f0dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":98,
                  "y":72},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b90c7af1127409fb513bf0d4b22a27b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":73},
            "size":{
              "width":328,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76b5cd1348c74db489e21a1e501d555e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":73},
                "size":{
                  "width":328,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4fb60b7197bf4e10be78da81acbbf172",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1150,
              "y":72},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95ab92e56e5e4d838702f3f4b2f4bb5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1150,
                  "y":72},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ffd6ce98c5d141c8802dff21c8ed3cd7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":210},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"885dec474af446c5af0af476db0275bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":210},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"582a1c46b5a74372ae328a1a75e3b160",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":136},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff404758c65a4cbc99e8cecf4356f7a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":136},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46d678420b584c0e960080b7401b1fe8",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":210},
            "size":{
              "width":1170,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7247e2ae798d4bd895dad05d8ae103ad",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d62f2381373740ca9ac6ccafd3040b0d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/充值记录/u13.png"}},
{
              "id":"e951aaac37b24571b132b0fc746e114f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":167,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"63732927f8364a61bdc26b675f6e466e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":167,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/充值记录/u27.png"}},
{
              "id":"6d47fbd271eb4c87b89c9ab2cb32a3ab",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"55004b7197b44241a759ed2fd2bd1235",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/充值记录/u41.png"}},
{
              "id":"ad76b99e92f344be99766d8db8c8f977",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":261,
                  "y":0},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fa71124ed202472bb9acc3ef7e69658b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":261,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/充值记录/u17.png"}},
{
              "id":"15049c6bdb074067a4bcb0252cbad305",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":261,
                  "y":30},
                "size":{
                  "width":125,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3eb0fef0500249d999cf6a236f6a7f7f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF008000,
                      "opacity":1},
                    "location":{
                      "x":261,
                      "y":30},
                    "size":{
                      "width":125,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/充值记录/u31.png"}},
{
              "id":"ddbc08f648654ee7988d69e6ee169fb3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":261,
                  "y":66},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c602245d29ff416cb958db720110cfaf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3300,
                      "opacity":1},
                    "location":{
                      "x":261,
                      "y":66},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/充值记录/u45.png"}},
{
              "id":"8427673251b04779bd4fa39761c856cd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":750,
                  "y":0},
                "size":{
                  "width":252,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"67d2798cef1b4821b7feacfac84a19d5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":750,
                      "y":0},
                    "size":{
                      "width":252,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/充值记录/u23.png"}},
{
              "id":"ae60a255da8641fb880459d64d801b89",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":750,
                  "y":30},
                "size":{
                  "width":252,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e85d831df4b742ba8583b1ba0e2e57aa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":750,
                      "y":30},
                    "size":{
                      "width":252,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/充值记录/u37.png"}},
{
              "id":"3657a68e246a44dcb512c9ddf5c8c5ec",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":750,
                  "y":66},
                "size":{
                  "width":252,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8183b8fc6fb042c0bcdbe18b4ff04fe9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":750,
                      "y":66},
                    "size":{
                      "width":252,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/充值记录/u51.png"}},
{
              "id":"34a98205adb54a179d90af3dfb87c70e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1002,
                  "y":0},
                "size":{
                  "width":168,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b59e7ddbd1aa47f08d67cc42ad42cb44",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":1002,
                      "y":0},
                    "size":{
                      "width":168,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/充值记录/u25.png"}},
{
              "id":"e62f009e27e34d479e1dad79aa6aa602",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1002,
                  "y":30},
                "size":{
                  "width":168,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a1d2803e869749c5bb30c1a4dd66cc01",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":1002,
                      "y":30},
                    "size":{
                      "width":168,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/充值记录/u39.png"}},
{
              "id":"edeee9c10ae94a59bc2a778c0ea56558",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1002,
                  "y":66},
                "size":{
                  "width":168,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"13e6533cea6a4c16b10c6e9ac3262aca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":1002,
                      "y":66},
                    "size":{
                      "width":168,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/充值记录/u53.png"}},
{
              "id":"628970b730854584bf2c74dacb602fd7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":0},
                "size":{
                  "width":94,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c4bfd989c23148deb75a20ec9b3001ec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":167,
                      "y":0},
                    "size":{
                      "width":94,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/充值记录/u15.png"}},
{
              "id":"c29cffa8351c42ceacaddf004b17a841",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":30},
                "size":{
                  "width":94,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7b6a5bca038345febff7f5e9433f4b04",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":167,
                      "y":30},
                    "size":{
                      "width":94,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/交易记录/u19.png"}},
{
              "id":"faef579d234d4ad59ab5be5727b3b5e6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":167,
                  "y":66},
                "size":{
                  "width":94,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9649e7f4db1b40659964ff0f591158e6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":167,
                      "y":66},
                    "size":{
                      "width":94,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/充值记录/u43.png"}},
{
              "id":"ce6769f9d6f540439b5ec018b67ed9fa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":512,
                  "y":0},
                "size":{
                  "width":238,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9fb61f9fe3dc4f749d0545f790396f3d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":512,
                      "y":0},
                    "size":{
                      "width":238,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/充值记录/u21.png"}},
{
              "id":"68fccf3e398540289979c038fca50214",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":512,
                  "y":30},
                "size":{
                  "width":238,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"29d322a9b8ae48d1ae5bf0b390b9449c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":512,
                      "y":30},
                    "size":{
                      "width":238,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/充值记录/u35.png"}},
{
              "id":"f8b314b4bf394ed58a9641b4ffbf34e4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":512,
                  "y":66},
                "size":{
                  "width":238,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6036dbf78dbc41c4bb8a0920aeb34b81",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":512,
                      "y":66},
                    "size":{
                      "width":238,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/充值记录/u49.png"}},
{
              "id":"ebb711ae665c47ab84df5f8445e73c94",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":386,
                  "y":0},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"25336a66661f44b3b5f1da857704a4ab",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":386,
                      "y":0},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/充值记录/u19.png"}},
{
              "id":"bf919396e844477d8f8749d333e9469b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":386,
                  "y":30},
                "size":{
                  "width":126,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b8d5f5c479424894a84cedbfbc67390c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":386,
                      "y":30},
                    "size":{
                      "width":126,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/充值记录/u33.png"}},
{
              "id":"b1ee9532d5e444c5a633ee3de436bfe7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":386,
                  "y":66},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f21d5e451bf04e03a19e88071f50f1b4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":386,
                      "y":66},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/充值记录/u47.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "1e0c483aa5f545b1a893232f07621f32":{
      "scriptId":"u0"},
    "1800b94d17194b209f8e1bfd20ee1039":{
      "scriptId":"u1"},
    "592c4ab1e2dd4d6a814d36da3006a048":{
      "scriptId":"u2"},
    "af37e9ca48594f3ab8a4f4cd53f4f0dd":{
      "scriptId":"u3"},
    "2b90c7af1127409fb513bf0d4b22a27b":{
      "scriptId":"u4"},
    "76b5cd1348c74db489e21a1e501d555e":{
      "scriptId":"u5"},
    "4fb60b7197bf4e10be78da81acbbf172":{
      "scriptId":"u6"},
    "95ab92e56e5e4d838702f3f4b2f4bb5c":{
      "scriptId":"u7"},
    "ffd6ce98c5d141c8802dff21c8ed3cd7":{
      "scriptId":"u8"},
    "885dec474af446c5af0af476db0275bf":{
      "scriptId":"u9"},
    "582a1c46b5a74372ae328a1a75e3b160":{
      "scriptId":"u10"},
    "ff404758c65a4cbc99e8cecf4356f7a6":{
      "scriptId":"u11"},
    "46d678420b584c0e960080b7401b1fe8":{
      "scriptId":"u12"},
    "7247e2ae798d4bd895dad05d8ae103ad":{
      "scriptId":"u13"},
    "d62f2381373740ca9ac6ccafd3040b0d":{
      "scriptId":"u14"},
    "628970b730854584bf2c74dacb602fd7":{
      "scriptId":"u15"},
    "c4bfd989c23148deb75a20ec9b3001ec":{
      "scriptId":"u16"},
    "ad76b99e92f344be99766d8db8c8f977":{
      "scriptId":"u17"},
    "fa71124ed202472bb9acc3ef7e69658b":{
      "scriptId":"u18"},
    "ebb711ae665c47ab84df5f8445e73c94":{
      "scriptId":"u19"},
    "25336a66661f44b3b5f1da857704a4ab":{
      "scriptId":"u20"},
    "ce6769f9d6f540439b5ec018b67ed9fa":{
      "scriptId":"u21"},
    "9fb61f9fe3dc4f749d0545f790396f3d":{
      "scriptId":"u22"},
    "8427673251b04779bd4fa39761c856cd":{
      "scriptId":"u23"},
    "67d2798cef1b4821b7feacfac84a19d5":{
      "scriptId":"u24"},
    "34a98205adb54a179d90af3dfb87c70e":{
      "scriptId":"u25"},
    "b59e7ddbd1aa47f08d67cc42ad42cb44":{
      "scriptId":"u26"},
    "e951aaac37b24571b132b0fc746e114f":{
      "scriptId":"u27"},
    "63732927f8364a61bdc26b675f6e466e":{
      "scriptId":"u28"},
    "c29cffa8351c42ceacaddf004b17a841":{
      "scriptId":"u29"},
    "7b6a5bca038345febff7f5e9433f4b04":{
      "scriptId":"u30"},
    "15049c6bdb074067a4bcb0252cbad305":{
      "scriptId":"u31"},
    "3eb0fef0500249d999cf6a236f6a7f7f":{
      "scriptId":"u32"},
    "bf919396e844477d8f8749d333e9469b":{
      "scriptId":"u33"},
    "b8d5f5c479424894a84cedbfbc67390c":{
      "scriptId":"u34"},
    "68fccf3e398540289979c038fca50214":{
      "scriptId":"u35"},
    "29d322a9b8ae48d1ae5bf0b390b9449c":{
      "scriptId":"u36"},
    "ae60a255da8641fb880459d64d801b89":{
      "scriptId":"u37"},
    "e85d831df4b742ba8583b1ba0e2e57aa":{
      "scriptId":"u38"},
    "e62f009e27e34d479e1dad79aa6aa602":{
      "scriptId":"u39"},
    "a1d2803e869749c5bb30c1a4dd66cc01":{
      "scriptId":"u40"},
    "6d47fbd271eb4c87b89c9ab2cb32a3ab":{
      "scriptId":"u41"},
    "55004b7197b44241a759ed2fd2bd1235":{
      "scriptId":"u42"},
    "faef579d234d4ad59ab5be5727b3b5e6":{
      "scriptId":"u43"},
    "9649e7f4db1b40659964ff0f591158e6":{
      "scriptId":"u44"},
    "ddbc08f648654ee7988d69e6ee169fb3":{
      "scriptId":"u45"},
    "c602245d29ff416cb958db720110cfaf":{
      "scriptId":"u46"},
    "b1ee9532d5e444c5a633ee3de436bfe7":{
      "scriptId":"u47"},
    "f21d5e451bf04e03a19e88071f50f1b4":{
      "scriptId":"u48"},
    "f8b314b4bf394ed58a9641b4ffbf34e4":{
      "scriptId":"u49"},
    "6036dbf78dbc41c4bb8a0920aeb34b81":{
      "scriptId":"u50"},
    "3657a68e246a44dcb512c9ddf5c8c5ec":{
      "scriptId":"u51"},
    "8183b8fc6fb042c0bcdbe18b4ff04fe9":{
      "scriptId":"u52"},
    "edeee9c10ae94a59bc2a778c0ea56558":{
      "scriptId":"u53"},
    "13e6533cea6a4c16b10c6e9ac3262aca":{
      "scriptId":"u54"}}});