$axure.loadCurrentPage({
  "url":"商户签约-提交成功提醒.html",
  "generationDate":new Date(1461745746580.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b6e4b41f4cf54e60a73bd0e3e1b575bd",
    "type":"Axure:Page",
    "name":"商户签约-提交成功提醒",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ddb13204f896471fa98d64393c3ec64b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":1610,
              "y":200},
            "size":{
              "width":430,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ca614bc2ffd473a950fa98bcbdb6b50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":1610,
                  "y":200},
                "size":{
                  "width":430,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u88.png"}},
{
          "id":"9f24e5f09bf3412fad27b14e58b00bc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":200},
            "size":{
              "width":1360,
              "height":810}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2b1946ab699445ab3ccebf5626dffe8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":200},
                "size":{
                  "width":1360,
                  "height":810}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-结算信息/u0.png"}},
{
          "id":"3f598a35585e4ec09c59f8fbcc924f94",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":472,
              "y":497},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98f830ce2c1a4667ba9d9c770c0cc0ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":472,
                  "y":497},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a627e27490cd4354931b0ae7230ff800",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":472,
              "y":434},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea0302dcd28146688cabafecd7858555",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":472,
                  "y":434},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da7c867da59442649a3e8c14804d7b62",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":582,
              "y":497},
            "size":{
              "width":220,
              "height":23}},
          "adaptiveStyles":{
}},
{
          "id":"f1ee083fc72642f2a39b1eaacc59d6c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":944,
              "y":435},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75a52ec0e80a4f20b0f1d72931c25208",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":944,
                  "y":435},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"adcbe3fcd6af401082a23fd496cf7e5c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":1055,
              "y":435},
            "size":{
              "width":220,
              "height":23}},
          "adaptiveStyles":{
}},
{
          "id":"2ec99df105b14c10a5ba46b19d631ebc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":485,
              "y":377},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"080f7afa17d04b8c9b66cf809f747840",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":485,
                  "y":377},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6193da3277a94fb3bd62cd083bacab41",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":442,
              "y":569},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2064c95f9b444ff783d636c5cc99e58c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":442,
                  "y":569},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c211ac0c8a1c47f08fc3fb1d75e35159",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":582,
              "y":569},
            "size":{
              "width":195,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"10009d6cf9c646aebf5e4904c32bdab6",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":797,
              "y":569},
            "size":{
              "width":180,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"59de0114044842e1ad4ba0aae6ee4ce5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":446,
              "y":660},
            "size":{
              "width":838,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户签约-基本信息（个人）/u33_line.png"}},
{
          "id":"a59475f377fb447fa49b56577ef81c30",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":811},
            "size":{
              "width":838,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户签约-基本信息（个人）/u33_line.png"}},
{
          "id":"a4565c384a764dc99942cb11c0b386f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":705,
              "y":896},
            "size":{
              "width":272,
              "height":42},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30f87f177e724c9392cc2dcf59660fca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":705,
                  "y":896},
                "size":{
                  "width":272,
                  "height":42},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u56.png"}},
{
          "id":"f5610f18ddf248b3933cc3b0f397919d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":927,
              "y":380},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa9c17d0f3704aa3b4169993f521303b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":927,
                  "y":380},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e98335695a8243029976793f50ecaea1",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1145,
              "y":383},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3ee1f52f1a24bff8c7f6fda3fba3cad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1145,
                  "y":383},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"a88950d00201444bade28cd77e86b41a",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1045,
              "y":383},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"528c57fe55a1486c845e2da2f06e5617",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1045,
                  "y":383},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"2c7597e6f05d44d892b2dba26f8416a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":587,
              "y":379},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"232b509f1ee844e8bbb262205e39da6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":587,
                  "y":379},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5f59d0fa918493c96eaac1fe197d02d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":582,
              "y":434},
            "size":{
              "width":220,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"63e3bd192e3545ba966c948e0c95a3bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":454,
              "y":701},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"925c1ab68f764aada233e821b40e6bc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":454,
                  "y":701},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24d533dd64384b70830eb3812cac9417",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":578,
              "y":703},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a83c965e5a3408b88afb506f75de5d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":578,
                  "y":703},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d65aa5be01940bb81025658e28f38e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":928,
              "y":704},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90716878bbfa4e00b43aff4443a2d0ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":928,
                  "y":704},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42eca5f2fdba4a6c93db61ffabb90714",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":1042,
              "y":704},
            "size":{
              "width":220,
              "height":23}},
          "adaptiveStyles":{
}},
{
          "id":"13f469525f844c27b9efbf05e364fdfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":467},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21f12b4f485445239d1fe18c41ffd9eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":467},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c557e5c3d45451881c0e463f61f75a7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":582,
              "y":467},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"100a13754c2841cdb168e82fdb134410",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":582,
                  "y":467},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u69.png"}},
{
          "id":"0f9b56d01b1d4f7da20edf9427dfc58e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1073,
              "y":468},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ccff8d5682d4f69ae39d2127f83f2b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1073,
                  "y":468},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"970c733302c84f56aca87cdf9a336f64",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1055,
              "y":468},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1987ca0ba13e43dda69c66a516afb06a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1055,
                  "y":468},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u69.png"}},
{
          "id":"0a34fdf6646149d0915fc4cffe53cdb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":520},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5d8a3a5d94e4b16b11218e9cbb469fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":520},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c66cc801b5e444c59428ab6eb987ea8a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":582,
              "y":520},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d65143da8d04917abd64a8d288ec6a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":582,
                  "y":520},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u69.png"}},
{
          "id":"b65268ee858d487897128d166b060859",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":608},
            "size":{
              "width":131,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db2bbf103d114d61b2681dfa8ce74e0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":608},
                "size":{
                  "width":131,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3aec24a0601846bc9f74b21f34234644",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":582,
              "y":608},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a08b6d3a78174201b902f998433831e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":582,
                  "y":608},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u69.png"}},
{
          "id":"d7c694f6a3e549e4a0c78a09da4dd9fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":553},
            "size":{
              "width":37,
              "height":39},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ea2be630e7e4fcdac0d638fac7e20ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":553},
                "size":{
                  "width":37,
                  "height":39},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-结算信息/u48.png"}},
{
          "id":"47a1b587452b483a9f2c26382aef6732",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":292,
              "y":565},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af819d95edb1496893bae7e2f2c815de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":292,
                  "y":565},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"643a83779559463482e1dc743afaeef1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":247,
              "y":782},
            "size":{
              "width":37,
              "height":39},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4597d96c1ec48c190b3045f094f8428",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":247,
                  "y":782},
                "size":{
                  "width":37,
                  "height":39},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-结算信息/u52.png"}},
{
          "id":"4fdb6dffc809457f9e5f7809fc91e59d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":292,
              "y":787},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"934442e8d11f4ee289f56754482fe4bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":292,
                  "y":787},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"843c373994b3429e892e41e9aa8dab7c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":595},
            "size":{
              "width":10,
              "height":182}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户签约-结算信息/u56_line.png"}},
{
          "id":"5dcce50803af4a339ca6d8bddba62817",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":329},
            "size":{
              "width":37,
              "height":39},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef0928aebe1e47958b24b33b9f3a27e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":329},
                "size":{
                  "width":37,
                  "height":39},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-结算信息/u48.png"}},
{
          "id":"c54dec982aef4c93a91c5df0f943da84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":292,
              "y":335},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90618131c60b4fdbad85e0c0162480b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":292,
                  "y":335},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e4cf311356c46fa8a084fce3d251344",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":371},
            "size":{
              "width":10,
              "height":182}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户签约-结算信息/u56_line.png"}},
{
          "id":"ece304f56847490dbf11bf768e51024a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":337},
            "size":{
              "width":23,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fb609ddf29940cbbdf4b0701a7720f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":337},
                "size":{
                  "width":23,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u120.png"}},
{
          "id":"1fa66553b8924334bc055d2f4ad4ec00",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":254,
              "y":558},
            "size":{
              "width":23,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ae5dea980bd484f8281649f454e8738",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":254,
                  "y":558},
                "size":{
                  "width":23,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u120.png"}},
{
          "id":"c376ee638a41429b8cf54e65e14271ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":871,
              "y":232},
            "size":{
              "width":145,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d188f9a589d489dbb83e131169d2b62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":871,
                  "y":232},
                "size":{
                  "width":145,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40166d946f3f4d84b79a28215ffb3b64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":220},
            "size":{
              "width":126,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ba2f7e45d8240f589fb71b3754126da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":235,
                  "y":220},
                "size":{
                  "width":126,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户管理-技术协议/u23.png"}},
{
          "id":"6cc01b3b9a9a4d359d3922ee63f55d3d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1453,
              "y":230},
            "size":{
              "width":51,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4ceecb6cf03474590585a6bc987e262",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1453,
                  "y":230},
                "size":{
                  "width":51,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u53.png"}},
{
          "id":"4104f4af32784f8497bee4efb57f04ce",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":298},
            "size":{
              "width":1350,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户签约-基本信息（企业）/u153_line.png"}},
{
          "id":"dc16fc51a0474a90b11187fa6f6b8398",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.4",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":204.5,
              "y":200},
            "size":{
              "width":1351,
              "height":810}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ed74a6547ea40a280a6fcda6231ebad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.4",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":204.5,
                  "y":200},
                "size":{
                  "width":1351,
                  "height":810}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-提交成功提醒/u79.png"}},
{
          "id":"b2616ebd52014713ae648b165f84d94d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":555,
              "y":468},
            "size":{
              "width":519,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a55a8446574846458de926174fb8c5cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":555,
                  "y":468},
                "size":{
                  "width":519,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-提交成功提醒/u81.png"}},
{
          "id":"a50d61f678094982bfb1e157126287b4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":555,
              "y":627},
            "size":{
              "width":519,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户签约-提交成功提醒/u83_line.png"}},
{
          "id":"e7ac96a1acc74033a09a3e440099b479",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":744,
              "y":655},
            "size":{
              "width":120,
              "height":37},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e82e01a3968e4010b07168b5b4ec0fbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":744,
                  "y":655},
                "size":{
                  "width":120,
                  "height":37},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页（控制台）",
                      "target":{
                        "targetType":"page",
                        "url":"首页（控制台）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户签约-提交成功提醒/u84.png"}},
{
          "id":"c96183a576da4873a1f4229d46aadd4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":671,
              "y":522},
            "size":{
              "width":365,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2aeb7d52b4d5490d9694f8323e819c36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":671,
                  "y":522},
                "size":{
                  "width":365,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ddb13204f896471fa98d64393c3ec64b":{
      "scriptId":"u0"},
    "4ca614bc2ffd473a950fa98bcbdb6b50":{
      "scriptId":"u1"},
    "9f24e5f09bf3412fad27b14e58b00bc1":{
      "scriptId":"u2"},
    "b2b1946ab699445ab3ccebf5626dffe8":{
      "scriptId":"u3"},
    "3f598a35585e4ec09c59f8fbcc924f94":{
      "scriptId":"u4"},
    "98f830ce2c1a4667ba9d9c770c0cc0ff":{
      "scriptId":"u5"},
    "a627e27490cd4354931b0ae7230ff800":{
      "scriptId":"u6"},
    "ea0302dcd28146688cabafecd7858555":{
      "scriptId":"u7"},
    "da7c867da59442649a3e8c14804d7b62":{
      "scriptId":"u8"},
    "f1ee083fc72642f2a39b1eaacc59d6c8":{
      "scriptId":"u9"},
    "75a52ec0e80a4f20b0f1d72931c25208":{
      "scriptId":"u10"},
    "adcbe3fcd6af401082a23fd496cf7e5c":{
      "scriptId":"u11"},
    "2ec99df105b14c10a5ba46b19d631ebc":{
      "scriptId":"u12"},
    "080f7afa17d04b8c9b66cf809f747840":{
      "scriptId":"u13"},
    "6193da3277a94fb3bd62cd083bacab41":{
      "scriptId":"u14"},
    "2064c95f9b444ff783d636c5cc99e58c":{
      "scriptId":"u15"},
    "c211ac0c8a1c47f08fc3fb1d75e35159":{
      "scriptId":"u16"},
    "10009d6cf9c646aebf5e4904c32bdab6":{
      "scriptId":"u17"},
    "59de0114044842e1ad4ba0aae6ee4ce5":{
      "scriptId":"u18"},
    "a59475f377fb447fa49b56577ef81c30":{
      "scriptId":"u19"},
    "a4565c384a764dc99942cb11c0b386f9":{
      "scriptId":"u20"},
    "30f87f177e724c9392cc2dcf59660fca":{
      "scriptId":"u21"},
    "f5610f18ddf248b3933cc3b0f397919d":{
      "scriptId":"u22"},
    "aa9c17d0f3704aa3b4169993f521303b":{
      "scriptId":"u23"},
    "e98335695a8243029976793f50ecaea1":{
      "scriptId":"u24"},
    "e3ee1f52f1a24bff8c7f6fda3fba3cad":{
      "scriptId":"u25"},
    "a88950d00201444bade28cd77e86b41a":{
      "scriptId":"u26"},
    "528c57fe55a1486c845e2da2f06e5617":{
      "scriptId":"u27"},
    "2c7597e6f05d44d892b2dba26f8416a5":{
      "scriptId":"u28"},
    "232b509f1ee844e8bbb262205e39da6d":{
      "scriptId":"u29"},
    "c5f59d0fa918493c96eaac1fe197d02d":{
      "scriptId":"u30"},
    "63e3bd192e3545ba966c948e0c95a3bb":{
      "scriptId":"u31"},
    "925c1ab68f764aada233e821b40e6bc2":{
      "scriptId":"u32"},
    "24d533dd64384b70830eb3812cac9417":{
      "scriptId":"u33"},
    "0a83c965e5a3408b88afb506f75de5d7":{
      "scriptId":"u34"},
    "1d65aa5be01940bb81025658e28f38e1":{
      "scriptId":"u35"},
    "90716878bbfa4e00b43aff4443a2d0ed":{
      "scriptId":"u36"},
    "42eca5f2fdba4a6c93db61ffabb90714":{
      "scriptId":"u37"},
    "13f469525f844c27b9efbf05e364fdfe":{
      "scriptId":"u38"},
    "21f12b4f485445239d1fe18c41ffd9eb":{
      "scriptId":"u39"},
    "5c557e5c3d45451881c0e463f61f75a7":{
      "scriptId":"u40"},
    "100a13754c2841cdb168e82fdb134410":{
      "scriptId":"u41"},
    "0f9b56d01b1d4f7da20edf9427dfc58e":{
      "scriptId":"u42"},
    "7ccff8d5682d4f69ae39d2127f83f2b0":{
      "scriptId":"u43"},
    "970c733302c84f56aca87cdf9a336f64":{
      "scriptId":"u44"},
    "1987ca0ba13e43dda69c66a516afb06a":{
      "scriptId":"u45"},
    "0a34fdf6646149d0915fc4cffe53cdb9":{
      "scriptId":"u46"},
    "b5d8a3a5d94e4b16b11218e9cbb469fe":{
      "scriptId":"u47"},
    "c66cc801b5e444c59428ab6eb987ea8a":{
      "scriptId":"u48"},
    "0d65143da8d04917abd64a8d288ec6a7":{
      "scriptId":"u49"},
    "b65268ee858d487897128d166b060859":{
      "scriptId":"u50"},
    "db2bbf103d114d61b2681dfa8ce74e0d":{
      "scriptId":"u51"},
    "3aec24a0601846bc9f74b21f34234644":{
      "scriptId":"u52"},
    "a08b6d3a78174201b902f998433831e6":{
      "scriptId":"u53"},
    "d7c694f6a3e549e4a0c78a09da4dd9fc":{
      "scriptId":"u54"},
    "9ea2be630e7e4fcdac0d638fac7e20ae":{
      "scriptId":"u55"},
    "47a1b587452b483a9f2c26382aef6732":{
      "scriptId":"u56"},
    "af819d95edb1496893bae7e2f2c815de":{
      "scriptId":"u57"},
    "643a83779559463482e1dc743afaeef1":{
      "scriptId":"u58"},
    "d4597d96c1ec48c190b3045f094f8428":{
      "scriptId":"u59"},
    "4fdb6dffc809457f9e5f7809fc91e59d":{
      "scriptId":"u60"},
    "934442e8d11f4ee289f56754482fe4bb":{
      "scriptId":"u61"},
    "843c373994b3429e892e41e9aa8dab7c":{
      "scriptId":"u62"},
    "5dcce50803af4a339ca6d8bddba62817":{
      "scriptId":"u63"},
    "ef0928aebe1e47958b24b33b9f3a27e8":{
      "scriptId":"u64"},
    "c54dec982aef4c93a91c5df0f943da84":{
      "scriptId":"u65"},
    "90618131c60b4fdbad85e0c0162480b6":{
      "scriptId":"u66"},
    "0e4cf311356c46fa8a084fce3d251344":{
      "scriptId":"u67"},
    "ece304f56847490dbf11bf768e51024a":{
      "scriptId":"u68"},
    "0fb609ddf29940cbbdf4b0701a7720f6":{
      "scriptId":"u69"},
    "1fa66553b8924334bc055d2f4ad4ec00":{
      "scriptId":"u70"},
    "8ae5dea980bd484f8281649f454e8738":{
      "scriptId":"u71"},
    "c376ee638a41429b8cf54e65e14271ed":{
      "scriptId":"u72"},
    "9d188f9a589d489dbb83e131169d2b62":{
      "scriptId":"u73"},
    "40166d946f3f4d84b79a28215ffb3b64":{
      "scriptId":"u74"},
    "8ba2f7e45d8240f589fb71b3754126da":{
      "scriptId":"u75"},
    "6cc01b3b9a9a4d359d3922ee63f55d3d":{
      "scriptId":"u76"},
    "b4ceecb6cf03474590585a6bc987e262":{
      "scriptId":"u77"},
    "4104f4af32784f8497bee4efb57f04ce":{
      "scriptId":"u78"},
    "dc16fc51a0474a90b11187fa6f6b8398":{
      "scriptId":"u79"},
    "0ed74a6547ea40a280a6fcda6231ebad":{
      "scriptId":"u80"},
    "b2616ebd52014713ae648b165f84d94d":{
      "scriptId":"u81"},
    "a55a8446574846458de926174fb8c5cf":{
      "scriptId":"u82"},
    "a50d61f678094982bfb1e157126287b4":{
      "scriptId":"u83"},
    "e7ac96a1acc74033a09a3e440099b479":{
      "scriptId":"u84"},
    "e82e01a3968e4010b07168b5b4ec0fbc":{
      "scriptId":"u85"},
    "c96183a576da4873a1f4229d46aadd4d":{
      "scriptId":"u86"},
    "2aeb7d52b4d5490d9694f8323e819c36":{
      "scriptId":"u87"}}});