$axure.loadCurrentPage({
  "url":"交易详情（第一版不做）.html",
  "generationDate":new Date(1458553423028.79),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2ddd02c5f9674eb4bf5bc5e64b8dcc03",
    "type":"Axure:Page",
    "name":"交易详情（第一版不做）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"159b40c825494560b7825160d9f2627c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":210,
              "y":210},
            "size":{
              "width":1219,
              "height":1040},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90a55fdcf2c94cb2a50699e5e22da386",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.3",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":210,
                  "y":210},
                "size":{
                  "width":1219,
                  "height":1040},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易详情（第一版不做）/u0.png"}},
{
          "id":"13537b5e6f3c4aadadba13948edc0b59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":740,
              "y":253},
            "size":{
              "width":145,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7e5ea91565e4f7d817d2def3c2f31f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":740,
                  "y":253},
                "size":{
                  "width":145,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e9560ef18d2456593391cc910c469dd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":310},
            "size":{
              "width":1150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/渠道添加/u4_line.png"}},
{
          "id":"1c88e56025ef420ca0047d1dde7812b4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":245},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45fe05ab03534387b7645840e915aa6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":245},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 渠道管理",
                      "target":{
                        "targetType":"page",
                        "url":"渠道管理.html",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/渠道添加/u5.png"}},
{
          "id":"0db0be30e33e41b1b931b3bce3da86a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":246,
              "y":330},
            "size":{
              "width":1140,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36c252a9eef04033ac1638bd15301031",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":246,
                  "y":330},
                "size":{
                  "width":1140,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付查询/u40.png"}},
{
          "id":"17694e283a2c4548b018553c929b6bda",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":292,
              "y":346},
            "size":{
              "width":151,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f883d9bd2d614bb38974c71bcc729ead",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":292,
                  "y":346},
                "size":{
                  "width":151,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付查询/u42.png"}},
{
          "id":"e6278834933d4cd4a68933882b958044",
          "label":"日期筛选",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":292,
              "y":379},
            "size":{
              "width":150,
              "height":50},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90c1c5549c284a68bb75002b8d84f56b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":292,
                  "y":379},
                "size":{
                  "width":150,
                  "height":50},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付查询/日期筛选_u318.png"}},
{
          "id":"f5e318afc23e4fd0822c78bfde5021e4",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":346},
            "size":{
              "width":26,
              "height":31}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"fadeWidget",
                      "description":"Toggle 日期筛选",
                      "objectsToFades":[{
                          "objectPath":["e6278834933d4cd4a68933882b958044"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"a633200dbe6845b48b38da6848f72279",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1296,
              "y":350},
            "size":{
              "width":63,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4a2a5f40cc54a558e0252161a6d2a89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1296,
                  "y":350},
                "size":{
                  "width":63,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付查询/u46.png"}},
{
          "id":"fbf6f911041d44e2845e4dbb1e71654c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1213,
              "y":350},
            "size":{
              "width":63,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"262db817f49b4090b8f9ac64dbd1c4b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1213,
                  "y":350},
                "size":{
                  "width":63,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付查询/u46.png"}},
{
          "id":"f3944e369e924a1db0586293fad690e0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":563,
              "y":344},
            "size":{
              "width":130,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"d8103bd6ae474ce1ace8c7a892339a3e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":953,
              "y":1150},
            "size":{
              "width":437,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"401e1af12ea24a5d9488c4c2dee9d787",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":953,
                  "y":1150},
                "size":{
                  "width":437,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现记录/u16.png"}},
{
          "id":"969a33ef27014ed2993ef7f0ebfb8bb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":480,
              "y":352},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b29191e099a442deb3605a72b937e358",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":480,
                  "y":352},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4b7068b71c9439f91f125a701c9b446",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":740,
              "y":348},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"605352695b384e7fbb6f70471215af37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":740,
                  "y":348},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f9f71fee58e4c5db50e96e9a9724a2a",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":348},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b4bb16f044c245a893d05c92c65565da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":980,
              "y":350},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4b106e99e3e486ebe7fe87d124c9564",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":980,
                  "y":350},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98a76eaef2b44d15a82600854d2b975d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":1080,
              "y":350},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b449c704b0224e9fb173bd251a1fdb55",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":246,
              "y":410},
            "size":{
              "width":1140,
              "height":330}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"278d9cff8351415e8578533d2267b98a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":246,
                  "y":410},
                "size":{
                  "width":1140,
                  "height":330}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账户明细（第一版不做）/u29.png"}},
{
          "id":"d22731fa9f0545198bea6c6f61ecc2c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.4",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":210,
              "y":210},
            "size":{
              "width":1220,
              "height":930}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e971742039a146d98154ab9ed9e7d803",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.4",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":210,
                  "y":210},
                "size":{
                  "width":1220,
                  "height":930}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改基本信息成功提示/u115.png"}},
{
          "id":"a2b6afa073154caf9fb4864112dfe59a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":421,
              "y":513},
            "size":{
              "width":790,
              "height":187}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"276fe8de79134c24a5834e782e4986a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":421,
                  "y":513},
                "size":{
                  "width":790,
                  "height":187}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易详情（第一版不做）/u33.png"}},
{
          "id":"d505b5772748493fbd9770c3ccb7db6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":1457,
              "y":210},
            "size":{
              "width":430,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38f216ac13f04c3db97cd2fc34838525",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":1457,
                  "y":210},
                "size":{
                  "width":430,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u88.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "159b40c825494560b7825160d9f2627c":{
      "scriptId":"u0"},
    "90a55fdcf2c94cb2a50699e5e22da386":{
      "scriptId":"u1"},
    "13537b5e6f3c4aadadba13948edc0b59":{
      "scriptId":"u2"},
    "c7e5ea91565e4f7d817d2def3c2f31f5":{
      "scriptId":"u3"},
    "1e9560ef18d2456593391cc910c469dd":{
      "scriptId":"u4"},
    "1c88e56025ef420ca0047d1dde7812b4":{
      "scriptId":"u5"},
    "45fe05ab03534387b7645840e915aa6f":{
      "scriptId":"u6"},
    "0db0be30e33e41b1b931b3bce3da86a6":{
      "scriptId":"u7"},
    "36c252a9eef04033ac1638bd15301031":{
      "scriptId":"u8"},
    "17694e283a2c4548b018553c929b6bda":{
      "scriptId":"u9"},
    "f883d9bd2d614bb38974c71bcc729ead":{
      "scriptId":"u10"},
    "e6278834933d4cd4a68933882b958044":{
      "scriptId":"u11"},
    "90c1c5549c284a68bb75002b8d84f56b":{
      "scriptId":"u12"},
    "f5e318afc23e4fd0822c78bfde5021e4":{
      "scriptId":"u13"},
    "a633200dbe6845b48b38da6848f72279":{
      "scriptId":"u14"},
    "f4a2a5f40cc54a558e0252161a6d2a89":{
      "scriptId":"u15"},
    "fbf6f911041d44e2845e4dbb1e71654c":{
      "scriptId":"u16"},
    "262db817f49b4090b8f9ac64dbd1c4b8":{
      "scriptId":"u17"},
    "f3944e369e924a1db0586293fad690e0":{
      "scriptId":"u18"},
    "d8103bd6ae474ce1ace8c7a892339a3e":{
      "scriptId":"u19"},
    "401e1af12ea24a5d9488c4c2dee9d787":{
      "scriptId":"u20"},
    "969a33ef27014ed2993ef7f0ebfb8bb4":{
      "scriptId":"u21"},
    "b29191e099a442deb3605a72b937e358":{
      "scriptId":"u22"},
    "f4b7068b71c9439f91f125a701c9b446":{
      "scriptId":"u23"},
    "605352695b384e7fbb6f70471215af37":{
      "scriptId":"u24"},
    "9f9f71fee58e4c5db50e96e9a9724a2a":{
      "scriptId":"u25"},
    "b4bb16f044c245a893d05c92c65565da":{
      "scriptId":"u26"},
    "a4b106e99e3e486ebe7fe87d124c9564":{
      "scriptId":"u27"},
    "98a76eaef2b44d15a82600854d2b975d":{
      "scriptId":"u28"},
    "b449c704b0224e9fb173bd251a1fdb55":{
      "scriptId":"u29"},
    "278d9cff8351415e8578533d2267b98a":{
      "scriptId":"u30"},
    "d22731fa9f0545198bea6c6f61ecc2c2":{
      "scriptId":"u31"},
    "e971742039a146d98154ab9ed9e7d803":{
      "scriptId":"u32"},
    "a2b6afa073154caf9fb4864112dfe59a":{
      "scriptId":"u33"},
    "276fe8de79134c24a5834e782e4986a4":{
      "scriptId":"u34"},
    "d505b5772748493fbd9770c3ccb7db6c":{
      "scriptId":"u35"},
    "38f216ac13f04c3db97cd2fc34838525":{
      "scriptId":"u36"}}});