$axure.loadCurrentPage({
  "url":"应用添加（android）.html",
  "generationDate":new Date(1461745747942.46),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7cc039ca217f414bb77af7f8d58f6147",
    "type":"Axure:Page",
    "name":"应用添加（android）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d48a95eba8294a5492533a322ea6b688",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":280}},
          "adaptiveStyles":{
},
          "masterId":"ce194b8bf61742aea7475dad35671852"},
{
          "id":"bb6b3a7bcda64e17ae424226baba8280",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":416},
            "size":{
              "width":210,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98a21821bbe0444ba8256f51b7f2dfaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":416},
                "size":{
                  "width":210,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u0.png"}},
{
          "id":"88ff99d722744acfa3aa810db384c025",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":372,
              "y":454},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0996edd936ac4fb894f3982c0378fa73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":372,
                  "y":454},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72351b1cd3de4685aca69fc1ce73c4ae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":369,
              "y":621},
            "size":{
              "width":45,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3828f3eec7984d09b667793e37aaa947",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":369,
                  "y":621},
                "size":{
                  "width":45,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 支付查询",
                      "target":{
                        "targetType":"page",
                        "url":"支付查询.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u6.png"}},
{
          "id":"ec2676659d124618a3f820353ae382f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":377,
              "y":658},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd9d648ed7884b1c81121f01a9194ca0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":377,
                  "y":658},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59d6c52d047a42cf820d1f5f551d08bc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":437,
              "y":621},
            "size":{
              "width":45,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e14ceed6da243bbbbf092bc52d5266d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":437,
                  "y":621},
                "size":{
                  "width":45,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u14.png"}},
{
          "id":"09a3cbeeb3cf4a319818ce70bf06171b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":445,
              "y":658},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c647a694d044483b1d7c40e0d783050",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":445,
                  "y":658},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56620596397b468a897957d9cf69017f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":420},
            "size":{
              "width":210,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58281f607ce44cb4ba299f1169bc80a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":420},
                "size":{
                  "width":210,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u0.png"}},
{
          "id":"65c38ef43be74d9fb5883184c6427392",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":678,
              "y":458},
            "size":{
              "width":97,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2fd97452d374e0683e2946d5a2e92cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":678,
                  "y":458},
                "size":{
                  "width":97,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"652facb1315d4d8b870f57e92eb58452",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":673,
              "y":626},
            "size":{
              "width":45,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4863a78f46884c8f9698ad41debdb60d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":673,
                  "y":626},
                "size":{
                  "width":45,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u6.png"}},
{
          "id":"5396b3ef18a64128bcd9197e182b8760",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":681,
              "y":662},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40716085ef3d4817b84767aa146ad14b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":681,
                  "y":662},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac6ff2a0f7924a6a98e069e69952862f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":736,
              "y":626},
            "size":{
              "width":45,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ac5ba01280040c1b5f62cc188b05643",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":736,
                  "y":626},
                "size":{
                  "width":45,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u14.png"}},
{
          "id":"9ba3a4a5d8d64001b9db2e291f33a34b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":744,
              "y":662},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6095b1bdafea43ee865ac2424234a173",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":744,
                  "y":662},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fefe77b558214f3ca8bb767d66c19d0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":420},
            "size":{
              "width":210,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b8695068e9b4548b9b0e57974ffbe1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":420},
                "size":{
                  "width":210,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u0.png"}},
{
          "id":"2ee62cb009bd4806aee946c583a0f011",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":987,
              "y":514},
            "size":{
              "width":90,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20e06c84fb2f4358a9127df261c5772b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":987,
                  "y":514},
                "size":{
                  "width":90,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u38.png"}},
{
          "id":"61fdbcdfd3bc46c7a18cde4d73f8ed32",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":1500,
              "y":290},
            "size":{
              "width":430,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1310da45aa0466ca91795e39a800e5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":1500,
                  "y":290},
                "size":{
                  "width":430,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u88.png"}},
{
          "id":"5e3f954e32d34649adc2941f0e869932",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":346,
              "y":512},
            "size":{
              "width":54,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60793451932d460a95e5a7667bc50ea2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":346,
                  "y":512},
                "size":{
                  "width":54,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页（控制台）/u58.png"}},
{
          "id":"4d9c8da9e60747c086fbbaf73a7d0b49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":428,
              "y":520},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6b410a1dc5446fbaee3971faa3608f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":428,
                  "y":520},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb3d24095c0a4782969723bedb7b1038",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":335,
              "y":554},
            "size":{
              "width":78,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fc8e924106545d4aa59b6eb1ef325df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":335,
                  "y":554},
                "size":{
                  "width":78,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页（控制台）/u62.png"}},
{
          "id":"379781865a7f4dab84d83186792ba38f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":435,
              "y":562},
            "size":{
              "width":36,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f91ce8873c1429abbf57a7bea972375",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":435,
                  "y":562},
                "size":{
                  "width":36,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e4650825f874dc7a92514cef919e0eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":736,
              "y":520},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdedf37958df4769b2e857b8f50f2f2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":736,
                  "y":520},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51d4b7a860e04e39b90aac3c80998f32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":744,
              "y":562},
            "size":{
              "width":36,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbbbb0e30eba48f6a73f6fbbcba2437a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":744,
                  "y":562},
                "size":{
                  "width":36,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7817e01e3a064661942bc051c01b93ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":659,
              "y":518},
            "size":{
              "width":54,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"035b6885a551462fb688da6cac30f3ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":659,
                  "y":518},
                "size":{
                  "width":54,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页（控制台）/u58.png"}},
{
          "id":"53a57e6931c6499fb0a4231906ceb5fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":648,
              "y":560},
            "size":{
              "width":78,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d348c303abd94e1daa07b10935242db8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":648,
                  "y":560},
                "size":{
                  "width":78,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页（控制台）/u62.png"}},
{
          "id":"a59df812b92d464baf9b1c16c54b7194",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":247,
              "y":280},
            "size":{
              "width":1246,
              "height":740}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caa662952d554b3389885416e372889b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":247,
                  "y":280},
                "size":{
                  "width":1246,
                  "height":740}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用添加（pc_h5）/u74.png"}},
{
          "id":"cf0a1a13fa074d359893d3cd1a9781a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":582,
              "y":498},
            "size":{
              "width":598,
              "height":472}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ecc7c2fbeb146b0b5d83cf3969ba832",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":582,
                  "y":498},
                "size":{
                  "width":598,
                  "height":472}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用添加（android）/u76.png"}},
{
          "id":"cd940fda902f4f508478f29408fff7f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":836,
              "y":518},
            "size":{
              "width":101,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a97aaed849c4af791a036baf8eda1d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":836,
                  "y":518},
                "size":{
                  "width":101,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b54a202dae654212a5f6f3f55adb673c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.6",
            "location":{
              "x":582,
              "y":552},
            "size":{
              "width":598,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/应用添加（pc_h5）/u80_line.png"}},
{
          "id":"877153230007476bbe194935420a78c4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":792,
              "y":639},
            "size":{
              "width":194,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"e4c785227ac94715b751f5f72e198429",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.6",
            "location":{
              "x":586,
              "y":898},
            "size":{
              "width":590,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/应用添加（pc_h5）/u82_line.png"}},
{
          "id":"bb3cebfebc7f4c7b93b1ca831d112712",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":824,
              "y":920},
            "size":{
              "width":115,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40b37a16967f4cafb3373ff0b244777c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":824,
                  "y":920},
                "size":{
                  "width":115,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页（控制台）",
                      "target":{
                        "targetType":"page",
                        "url":"首页（控制台）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/应用添加（pc_h5）/u83.png"}},
{
          "id":"78303dc309c64a90a90315b766589353",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":792,
              "y":588},
            "size":{
              "width":197,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"dcc7ec26dc2840afae5c71725a84e250",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":1500,
              "y":290},
            "size":{
              "width":430,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd612a9bf5944c82ba64f493f9cc5e0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":1500,
                  "y":290},
                "size":{
                  "width":430,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助/u88.png"}},
{
          "id":"5e68fc6282bf4c9e8ea3d32a23ac8f07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":679},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e3edc8ca96f4637958b6354f9babaeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":840,
                  "y":679},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d3c9fd584e44006bb8b78de9d317541",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":822,
              "y":675},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"566c3b8e88944fb280d853d12d826f51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":822,
                  "y":675},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u69.png"}},
{
          "id":"486a1e2af18f487c83bb0e35f0e6b2c0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":789,
              "y":709},
            "size":{
              "width":194,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"0c2c60536b6c47968c39d448491bd566",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":827,
              "y":746},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c97bfed708a40f99b6d3869a6c65d3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":827,
                  "y":746},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"280f7fdd48b748609cdd50078f120a5c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":809,
              "y":746},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3dd8ac6db854776b595554ef1595219",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":809,
                  "y":746},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u69.png"}},
{
          "id":"521c3fbc75654896a056ec2c517262cb",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":779,
              "y":774},
            "size":{
              "width":194,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"c567fb9a7dc74378b79cddd5f06281b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":827,
              "y":814},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d7ea4a25bb14b3598b26a303e77f9c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":827,
                  "y":814},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe3382b26b4d455e9c810171cadc75db",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":809,
              "y":814},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29f56f5804904498ac22a75f735bf93a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":809,
                  "y":814},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u69.png"}},
{
          "id":"b461f304f314486c856c695b75954948",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1112,
              "y":498},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83433b1286d940fab1ccedb00f40ef63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1112,
                  "y":498},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页（控制台）",
                      "target":{
                        "targetType":"page",
                        "url":"首页（控制台）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/帮助/u74.png"}},
{
          "id":"8fec656dbde64267874913ecadedc095",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":664,
              "y":588},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffdff873ba1d42f1a8ea745de806c43e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":664,
                  "y":588},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27ad213cfbc24a7092320a473d327da5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":666,
              "y":639},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d822688991d4056b0a89c6aac58fde8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":666,
                  "y":639},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13fcbd043f144f6fb05404b53ab98459",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":623,
              "y":710},
            "size":{
              "width":141,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d21747f1d42b4ff8812ad7238641c86f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":623,
                  "y":710},
                "size":{
                  "width":141,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef1433e81eb0484992d211091c4b4037",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":659,
              "y":777},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"922cc8e5b2414f029253cb13c80f2822",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":659,
                  "y":777},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6e5dc904da34cdda1d19a6e84d0330f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":996,
              "y":715},
            "size":{
              "width":145,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f08f4179f6b34c9980582a612be10168",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":996,
                  "y":715},
                "size":{
                  "width":145,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"177f4e385a654da08bfdec3632695255",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":996,
              "y":780},
            "size":{
              "width":145,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a7408b4b0854a6ab2c285dc455de166",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":996,
                  "y":780},
                "size":{
                  "width":145,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b443379b264341a0a392f3d2cc74dc21",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":779,
              "y":838},
            "size":{
              "width":194,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"2b7d725f38944d608fcf170f6975c301",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":827,
              "y":878},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ca8636fdbc747b0b4576a88f11fa2a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":827,
                  "y":878},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9b82d8cd56447759c1281d6adf4122b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":809,
              "y":878},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6555d125f38845509fa484443ec8b3ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":809,
                  "y":878},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户签约-基本信息（个人）/u69.png"}},
{
          "id":"c2102eb0996c426fa74bfc6d246052a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":659,
              "y":841},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2816b5e6ed0f4e54aae07cf5ff3bc6c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":659,
                  "y":841},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b298218e86e64861bdcaf39ec411a84c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":996,
              "y":844},
            "size":{
              "width":145,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20fc534dffea4159890468c9bf12bd3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":996,
                  "y":844},
                "size":{
                  "width":145,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "ce194b8bf61742aea7475dad35671852":{
      "packageId":"ce194b8bf61742aea7475dad35671852",
      "type":"Axure:Master",
      "name":"头部框架",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1a8ee24928a94860889c9b047390fbf5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "opacity":"0.3",
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "size":{
                "width":1219,
                "height":1020},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f6d5da329001418bad0c45f297bae802",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "opacity":"0.3",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "size":{
                    "width":1219,
                    "height":1020},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/帮助/u41.png"}},
{
            "id":"2b596599a1a2483d84e1634a29aaddec",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":100},
              "size":{
                "width":1219,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/帮助/u43_line.png"}},
{
            "id":"06a4f09ba941472c84ee4ff1c0e16d57",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":855,
                "y":41},
              "size":{
                "width":203,
                "height":33}},
            "adaptiveStyles":{
}},
{
            "id":"2d1981c2bb3a4bbf98d29d5eb4a95f05",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":1058,
                "y":41},
              "size":{
                "width":38,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5c489b146ee44a60b5c40b1930b87fea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":1058,
                    "y":41},
                  "size":{
                    "width":38,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 支付查询",
                        "target":{
                          "targetType":"page",
                          "url":"支付查询.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u45.png"}},
{
            "id":"014e382808854576ac2a5acf6f38b3a2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":35,
                "y":20},
              "size":{
                "width":125,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f984bdbcccaa4abf9aac379604b9f79d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":35,
                    "y":20},
                  "size":{
                    "width":125,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/帮助/u47.png"}},
{
            "id":"bececc72e4864233aa56bbeb0067e5a5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":187,
                "y":37},
              "size":{
                "width":73,
                "height":43},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"665d02781c8d4d96a2ccf54f489faf8d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":187,
                    "y":37},
                  "size":{
                    "width":73,
                    "height":43},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页（控制台）",
                        "target":{
                          "targetType":"page",
                          "url":"首页（控制台）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u49.png"}},
{
            "id":"f7852bcc4c5a4921802ef94e6d848264",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":747,
                "y":40},
              "size":{
                "width":50,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da463ba93a7b4aec8326c16acf8da252",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":747,
                    "y":40},
                  "size":{
                    "width":50,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 帮助",
                        "target":{
                          "targetType":"page",
                          "url":"帮助.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u51.png"}},
{
            "id":"75f88fef079b47a09a5869837b83bf72",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1150,
                "y":30},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e78ad31a00344180aede2de040f4a718",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1150,
                    "y":30},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle 右侧边栏",
                        "objectsToFades":[{
                            "objectPath":["4c67581e5b9c41d2bed24e008a7eaf41"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u53.png"}},
{
            "id":"4c67581e5b9c41d2bed24e008a7eaf41",
            "label":"右侧边栏",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":1019,
                "y":105},
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"735f9a5466874ed29256b29c16e25def",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"718082d5a20f450d9c84bd2103096cf6",
                    "label":"",
                    "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":200,
                        "height":205}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b1ccd05daa8b42a3bfb0dbd5953ba989",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":200,
                            "height":205}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/帮助/u56.png"}},
{
                    "id":"9654f5fb424e410187206b64ad418cc3",
                    "label":"",
                    "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Negreta', 'Arial'",
                      "fontSize":"18px",
                      "fontWeight":"700",
                      "location":{
                        "x":12,
                        "y":26},
                      "size":{
                        "width":174,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"90a4735f986b4a6182c99e43389f1406",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Negreta', 'Arial'",
                          "fontSize":"18px",
                          "fontWeight":"700",
                          "location":{
                            "x":12,
                            "y":26},
                          "size":{
                            "width":174,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"b8ee2d90d06e4e538a40ae52e9ffc07e",
                    "label":"",
                    "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontSize":"16px",
                      "location":{
                        "x":41,
                        "y":73},
                      "size":{
                        "width":120,
                        "height":30},
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2d867bb2072e457e8c918d09ae3ddac6",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"16px",
                          "location":{
                            "x":41,
                            "y":73},
                          "size":{
                            "width":120,
                            "height":30},
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 基本信息（个人呈现）",
                                "target":{
                                  "targetType":"page",
                                  "url":"基本信息（个人呈现）.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/帮助/u60.png"}},
{
                    "id":"09c4937ed6844893bf4a19ae7fcb6637",
                    "label":"",
                    "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":75,
                        "y":128},
                      "size":{
                        "width":50,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"aa7310f048d8440d82e9fb58dffe258a",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"4c67581e5b9c41d2bed24e008a7eaf41",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":75,
                            "y":128},
                          "size":{
                            "width":50,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/帮助/u62.png"}}]}]},
{
            "id":"aaa8451fb0384ee78285cd70dbd3ac43",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":301,
                "y":41},
              "size":{
                "width":93,
                "height":40},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b70af69fec064387a9c5b3322fb2146a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":301,
                    "y":41},
                  "size":{
                    "width":93,
                    "height":40},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/帮助/u64.png"}},
{
            "id":"861b3c8487af4ee0950251a48b2c6762",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":654,
                "y":46},
              "size":{
                "width":74,
                "height":30},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b711ccb25389454aa756897a2ff7e007",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":654,
                    "y":46},
                  "size":{
                    "width":74,
                    "height":30},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/帮助/u66.png"}}]}}},
  "objectPaths":{
    "d48a95eba8294a5492533a322ea6b688":{
      "scriptId":"u0",
      "1a8ee24928a94860889c9b047390fbf5":{
        "scriptId":"u1"},
      "f6d5da329001418bad0c45f297bae802":{
        "scriptId":"u2"},
      "2b596599a1a2483d84e1634a29aaddec":{
        "scriptId":"u3"},
      "06a4f09ba941472c84ee4ff1c0e16d57":{
        "scriptId":"u4"},
      "2d1981c2bb3a4bbf98d29d5eb4a95f05":{
        "scriptId":"u5"},
      "5c489b146ee44a60b5c40b1930b87fea":{
        "scriptId":"u6"},
      "014e382808854576ac2a5acf6f38b3a2":{
        "scriptId":"u7"},
      "f984bdbcccaa4abf9aac379604b9f79d":{
        "scriptId":"u8"},
      "bececc72e4864233aa56bbeb0067e5a5":{
        "scriptId":"u9"},
      "665d02781c8d4d96a2ccf54f489faf8d":{
        "scriptId":"u10"},
      "f7852bcc4c5a4921802ef94e6d848264":{
        "scriptId":"u11"},
      "da463ba93a7b4aec8326c16acf8da252":{
        "scriptId":"u12"},
      "75f88fef079b47a09a5869837b83bf72":{
        "scriptId":"u13"},
      "e78ad31a00344180aede2de040f4a718":{
        "scriptId":"u14"},
      "4c67581e5b9c41d2bed24e008a7eaf41":{
        "scriptId":"u15"},
      "718082d5a20f450d9c84bd2103096cf6":{
        "scriptId":"u16"},
      "b1ccd05daa8b42a3bfb0dbd5953ba989":{
        "scriptId":"u17"},
      "9654f5fb424e410187206b64ad418cc3":{
        "scriptId":"u18"},
      "90a4735f986b4a6182c99e43389f1406":{
        "scriptId":"u19"},
      "b8ee2d90d06e4e538a40ae52e9ffc07e":{
        "scriptId":"u20"},
      "2d867bb2072e457e8c918d09ae3ddac6":{
        "scriptId":"u21"},
      "09c4937ed6844893bf4a19ae7fcb6637":{
        "scriptId":"u22"},
      "aa7310f048d8440d82e9fb58dffe258a":{
        "scriptId":"u23"},
      "aaa8451fb0384ee78285cd70dbd3ac43":{
        "scriptId":"u24"},
      "b70af69fec064387a9c5b3322fb2146a":{
        "scriptId":"u25"},
      "861b3c8487af4ee0950251a48b2c6762":{
        "scriptId":"u26"},
      "b711ccb25389454aa756897a2ff7e007":{
        "scriptId":"u27"}},
    "bb6b3a7bcda64e17ae424226baba8280":{
      "scriptId":"u28"},
    "98a21821bbe0444ba8256f51b7f2dfaa":{
      "scriptId":"u29"},
    "88ff99d722744acfa3aa810db384c025":{
      "scriptId":"u30"},
    "0996edd936ac4fb894f3982c0378fa73":{
      "scriptId":"u31"},
    "72351b1cd3de4685aca69fc1ce73c4ae":{
      "scriptId":"u32"},
    "3828f3eec7984d09b667793e37aaa947":{
      "scriptId":"u33"},
    "ec2676659d124618a3f820353ae382f3":{
      "scriptId":"u34"},
    "bd9d648ed7884b1c81121f01a9194ca0":{
      "scriptId":"u35"},
    "59d6c52d047a42cf820d1f5f551d08bc":{
      "scriptId":"u36"},
    "5e14ceed6da243bbbbf092bc52d5266d":{
      "scriptId":"u37"},
    "09a3cbeeb3cf4a319818ce70bf06171b":{
      "scriptId":"u38"},
    "7c647a694d044483b1d7c40e0d783050":{
      "scriptId":"u39"},
    "56620596397b468a897957d9cf69017f":{
      "scriptId":"u40"},
    "58281f607ce44cb4ba299f1169bc80a4":{
      "scriptId":"u41"},
    "65c38ef43be74d9fb5883184c6427392":{
      "scriptId":"u42"},
    "a2fd97452d374e0683e2946d5a2e92cb":{
      "scriptId":"u43"},
    "652facb1315d4d8b870f57e92eb58452":{
      "scriptId":"u44"},
    "4863a78f46884c8f9698ad41debdb60d":{
      "scriptId":"u45"},
    "5396b3ef18a64128bcd9197e182b8760":{
      "scriptId":"u46"},
    "40716085ef3d4817b84767aa146ad14b":{
      "scriptId":"u47"},
    "ac6ff2a0f7924a6a98e069e69952862f":{
      "scriptId":"u48"},
    "4ac5ba01280040c1b5f62cc188b05643":{
      "scriptId":"u49"},
    "9ba3a4a5d8d64001b9db2e291f33a34b":{
      "scriptId":"u50"},
    "6095b1bdafea43ee865ac2424234a173":{
      "scriptId":"u51"},
    "fefe77b558214f3ca8bb767d66c19d0d":{
      "scriptId":"u52"},
    "6b8695068e9b4548b9b0e57974ffbe1a":{
      "scriptId":"u53"},
    "2ee62cb009bd4806aee946c583a0f011":{
      "scriptId":"u54"},
    "20e06c84fb2f4358a9127df261c5772b":{
      "scriptId":"u55"},
    "61fdbcdfd3bc46c7a18cde4d73f8ed32":{
      "scriptId":"u56"},
    "d1310da45aa0466ca91795e39a800e5c":{
      "scriptId":"u57"},
    "5e3f954e32d34649adc2941f0e869932":{
      "scriptId":"u58"},
    "60793451932d460a95e5a7667bc50ea2":{
      "scriptId":"u59"},
    "4d9c8da9e60747c086fbbaf73a7d0b49":{
      "scriptId":"u60"},
    "e6b410a1dc5446fbaee3971faa3608f4":{
      "scriptId":"u61"},
    "cb3d24095c0a4782969723bedb7b1038":{
      "scriptId":"u62"},
    "3fc8e924106545d4aa59b6eb1ef325df":{
      "scriptId":"u63"},
    "379781865a7f4dab84d83186792ba38f":{
      "scriptId":"u64"},
    "9f91ce8873c1429abbf57a7bea972375":{
      "scriptId":"u65"},
    "7e4650825f874dc7a92514cef919e0eb":{
      "scriptId":"u66"},
    "bdedf37958df4769b2e857b8f50f2f2f":{
      "scriptId":"u67"},
    "51d4b7a860e04e39b90aac3c80998f32":{
      "scriptId":"u68"},
    "dbbbb0e30eba48f6a73f6fbbcba2437a":{
      "scriptId":"u69"},
    "7817e01e3a064661942bc051c01b93ed":{
      "scriptId":"u70"},
    "035b6885a551462fb688da6cac30f3ac":{
      "scriptId":"u71"},
    "53a57e6931c6499fb0a4231906ceb5fd":{
      "scriptId":"u72"},
    "d348c303abd94e1daa07b10935242db8":{
      "scriptId":"u73"},
    "a59df812b92d464baf9b1c16c54b7194":{
      "scriptId":"u74"},
    "caa662952d554b3389885416e372889b":{
      "scriptId":"u75"},
    "cf0a1a13fa074d359893d3cd1a9781a3":{
      "scriptId":"u76"},
    "7ecc7c2fbeb146b0b5d83cf3969ba832":{
      "scriptId":"u77"},
    "cd940fda902f4f508478f29408fff7f2":{
      "scriptId":"u78"},
    "7a97aaed849c4af791a036baf8eda1d4":{
      "scriptId":"u79"},
    "b54a202dae654212a5f6f3f55adb673c":{
      "scriptId":"u80"},
    "877153230007476bbe194935420a78c4":{
      "scriptId":"u81"},
    "e4c785227ac94715b751f5f72e198429":{
      "scriptId":"u82"},
    "bb3cebfebc7f4c7b93b1ca831d112712":{
      "scriptId":"u83"},
    "40b37a16967f4cafb3373ff0b244777c":{
      "scriptId":"u84"},
    "78303dc309c64a90a90315b766589353":{
      "scriptId":"u85"},
    "dcc7ec26dc2840afae5c71725a84e250":{
      "scriptId":"u86"},
    "bd612a9bf5944c82ba64f493f9cc5e0c":{
      "scriptId":"u87"},
    "5e68fc6282bf4c9e8ea3d32a23ac8f07":{
      "scriptId":"u88"},
    "0e3edc8ca96f4637958b6354f9babaeb":{
      "scriptId":"u89"},
    "1d3c9fd584e44006bb8b78de9d317541":{
      "scriptId":"u90"},
    "566c3b8e88944fb280d853d12d826f51":{
      "scriptId":"u91"},
    "486a1e2af18f487c83bb0e35f0e6b2c0":{
      "scriptId":"u92"},
    "0c2c60536b6c47968c39d448491bd566":{
      "scriptId":"u93"},
    "1c97bfed708a40f99b6d3869a6c65d3e":{
      "scriptId":"u94"},
    "280f7fdd48b748609cdd50078f120a5c":{
      "scriptId":"u95"},
    "e3dd8ac6db854776b595554ef1595219":{
      "scriptId":"u96"},
    "521c3fbc75654896a056ec2c517262cb":{
      "scriptId":"u97"},
    "c567fb9a7dc74378b79cddd5f06281b1":{
      "scriptId":"u98"},
    "5d7ea4a25bb14b3598b26a303e77f9c4":{
      "scriptId":"u99"},
    "fe3382b26b4d455e9c810171cadc75db":{
      "scriptId":"u100"},
    "29f56f5804904498ac22a75f735bf93a":{
      "scriptId":"u101"},
    "b461f304f314486c856c695b75954948":{
      "scriptId":"u102"},
    "83433b1286d940fab1ccedb00f40ef63":{
      "scriptId":"u103"},
    "8fec656dbde64267874913ecadedc095":{
      "scriptId":"u104"},
    "ffdff873ba1d42f1a8ea745de806c43e":{
      "scriptId":"u105"},
    "27ad213cfbc24a7092320a473d327da5":{
      "scriptId":"u106"},
    "2d822688991d4056b0a89c6aac58fde8":{
      "scriptId":"u107"},
    "13fcbd043f144f6fb05404b53ab98459":{
      "scriptId":"u108"},
    "d21747f1d42b4ff8812ad7238641c86f":{
      "scriptId":"u109"},
    "ef1433e81eb0484992d211091c4b4037":{
      "scriptId":"u110"},
    "922cc8e5b2414f029253cb13c80f2822":{
      "scriptId":"u111"},
    "a6e5dc904da34cdda1d19a6e84d0330f":{
      "scriptId":"u112"},
    "f08f4179f6b34c9980582a612be10168":{
      "scriptId":"u113"},
    "177f4e385a654da08bfdec3632695255":{
      "scriptId":"u114"},
    "2a7408b4b0854a6ab2c285dc455de166":{
      "scriptId":"u115"},
    "b443379b264341a0a392f3d2cc74dc21":{
      "scriptId":"u116"},
    "2b7d725f38944d608fcf170f6975c301":{
      "scriptId":"u117"},
    "0ca8636fdbc747b0b4576a88f11fa2a1":{
      "scriptId":"u118"},
    "a9b82d8cd56447759c1281d6adf4122b":{
      "scriptId":"u119"},
    "6555d125f38845509fa484443ec8b3ba":{
      "scriptId":"u120"},
    "c2102eb0996c426fa74bfc6d246052a4":{
      "scriptId":"u121"},
    "2816b5e6ed0f4e54aae07cf5ff3bc6c6":{
      "scriptId":"u122"},
    "b298218e86e64861bdcaf39ec411a84c":{
      "scriptId":"u123"},
    "20fc534dffea4159890468c9bf12bd3e":{
      "scriptId":"u124"}}});